# Datasets {#datasets}

* [disgust.csv](data/disgust.csv) 
    Three domain disgust questionnaire
    * [dplyr lesson](#data-disgust)
* [disgust_cors.csv](data/disgust_cors.csv) 
    Correlations between questions on the three domain disgust questionnaire (calculated from [disgust.csv](data/disgust.csv))
    * [ggplot exercise](exercises/03_ggplot_exercise.Rmd)
* [disgust_scores.csv](data/disgust_scores.csv)
    Subscale scores for the three domain disgust questionnaire (calculated from [disgust.csv](data/disgust.csv))
    * [data exercise](exercises/02_data_exercise.Rmd)
    * [ggplot exercise](exercises/03_ggplot_exercise.Rmd)
    * [joins exercise](exercises/06_joins_exercise.Rmd)
* [EMBU_mother.csv](data/EMBU_mother.csv)
    EMBU parenting questionnaire (not used in chapters yet)
* [empathizing.csv](data/empathizing.csv)
    Empathizing questionnaire (not used in chapters yet)
* [eye_descriptions.csv](data/eye_descriptions.csv)
    Text descriptions of eyes
    * [tidyr exercise](exercises/04_tidyr_exercise.Rmd)
    * [dplyr exercise](exercises/05_dplyr_exercise.Rmd)
* [family_composition.csv](data/family_composition.csv)
    Parents' ages and number of siblings of different types
    * [tidyr exercise](exercises/04_tidyr_exercise.Rmd)
    * [dplyr exercise](exercises/05_dplyr_exercise.Rmd)
* [infmort.csv](data/infmort.csv)
    Infant mortality by country and year
    * [tidyr lesson](#data-infmort)
* [matmort.xls](data/matmort.xls)
    Maternal mortality by country and year
    * [tidyr lesson](#data-matmort)
* [personality.csv](data/personality.csv)
    Five-factor personality questionnaire
    * [tidyr lesson](#data-personality)
* [personality_scores.csv](data/personality_scores.csv)
    Subscale scores on the five-factor personality questionnaire (calculated from [personality.csv](data/personality.csv))
    * [joins exercise](exercises/06_joins_exercise.Rmd)
* [sensation_seeking.csv](data/sensation_seeking.csv)
    Sensation-seeking questionnaire
    * [tidyr exercise](exercises/04_tidyr_exercise.Rmd)
* [sortmasc.csv](data/sortmasc.csv)
    Data for face sorting task where 5 versions of averaged faces of varying masculinity are sorted in order of preference (not used in chapters yet)
* [systemizing.csv](data/systemizing.csv)
    Systemizing questionnaire (not used in chapters yet)
* [users.csv](data/users.csv)
    ID, sex, and birthday for participants in most questionnaires
    * [joins exercise](exercises/06_joins_exercise.Rmd)
* [users2.csv](data/users2.csv)
    ID, sex, and birthday for participants in other questionnaires
    * [joins exercise](exercises/06_joins_exercise.Rmd)