<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Tidy Data | Data Skills for Reproducible Science</title>
  <meta name="description" content="This course provides an overview of skills needed for reproducible research and open science using the statistical programming language R. Students will learn about data visualisation, data tidying and wrangling, archiving, iteration and functions, probability and data simulations, general linear models, and reproducible workflows. Learning is reinforced through weekly assignments that involve working with different types of data." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Tidy Data | Data Skills for Reproducible Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This course provides an overview of skills needed for reproducible research and open science using the statistical programming language R. Students will learn about data visualisation, data tidying and wrangling, archiving, iteration and functions, probability and data simulations, general linear models, and reproducible workflows. Learning is reinforced through weekly assignments that involve working with different types of data." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Tidy Data | Data Skills for Reproducible Science" />
  
  <meta name="twitter:description" content="This course provides an overview of skills needed for reproducible research and open science using the statistical programming language R. Students will learn about data visualisation, data tidying and wrangling, archiving, iteration and functions, probability and data simulations, general linear models, and reproducible workflows. Learning is reinforced through weekly assignments that involve working with different types of data." />
  



<meta name="date" content="2020-09-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ggplot.html"/>
<link rel="next" href="dplyr.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Skills for Reproducible Science</a></li>
<li><a href="https://zenodo.org/badge/latestdoi/166541547"><img src="https://zenodo.org/badge/166541547.svg" alt="DOI"></a></li>
<li><a href="https://www.youtube.com/playlist?list=PLA2iRWVwbpTIweEBHD2dOKjZHK1atRmXt">Video Playlist</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i>Overview</a><ul>
<li class="chapter" data-level="0.1" data-path="overview.html"><a href="overview.html#course-aims"><i class="fa fa-check"></i><b>0.1</b> Course Aims</a></li>
<li class="chapter" data-level="0.2" data-path="overview.html"><a href="overview.html#intended-learning-outcomes"><i class="fa fa-check"></i><b>0.2</b> Intended Learning Outcomes</a></li>
<li class="chapter" data-level="0.3" data-path="overview.html"><a href="overview.html#course-resources"><i class="fa fa-check"></i><b>0.3</b> Course Resources</a></li>
<li class="chapter" data-level="0.4" data-path="overview.html"><a href="overview.html#course-outline"><i class="fa fa-check"></i><b>0.4</b> Course Outline</a></li>
<li class="chapter" data-level="0.5" data-path="overview.html"><a href="overview.html#formative-exercises"><i class="fa fa-check"></i><b>0.5</b> Formative Exercises</a></li>
<li class="chapter" data-level="0.6" data-path="overview.html"><a href="overview.html#other-resources"><i class="fa fa-check"></i><b>0.6</b> Other Resources</a><ul>
<li class="chapter" data-level="0.6.1" data-path="overview.html"><a href="overview.html#online-tutorials"><i class="fa fa-check"></i><b>0.6.1</b> Online tutorials</a></li>
<li class="chapter" data-level="0.6.2" data-path="overview.html"><a href="overview.html#cheat-sheets"><i class="fa fa-check"></i><b>0.6.2</b> Cheat sheets</a></li>
<li class="chapter" data-level="0.6.3" data-path="overview.html"><a href="overview.html#other"><i class="fa fa-check"></i><b>0.6.3</b> Other</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>1.2</b> Resources</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#what-is-r"><i class="fa fa-check"></i><b>1.3</b> What is R?</a><ul>
<li class="chapter" data-level="1.3.1" data-path="intro.html"><a href="intro.html#rconsole"><i class="fa fa-check"></i><b>1.3.1</b> The Base R Console</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#rstudio_ide"><i class="fa fa-check"></i><b>1.3.2</b> RStudio</a></li>
<li class="chapter" data-level="1.3.3" data-path="intro.html"><a href="intro.html#configure-rstudio"><i class="fa fa-check"></i><b>1.3.3</b> Configure RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#getting-started"><i class="fa fa-check"></i><b>1.4</b> Getting Started</a><ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#console"><i class="fa fa-check"></i><b>1.4.1</b> Console commands</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#vars"><i class="fa fa-check"></i><b>1.4.2</b> Objects</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#the-environment"><i class="fa fa-check"></i><b>1.4.3</b> The environment</a></li>
<li class="chapter" data-level="1.4.4" data-path="intro.html"><a href="intro.html#whitespace"><i class="fa fa-check"></i><b>1.4.4</b> Whitespace</a></li>
<li class="chapter" data-level="1.4.5" data-path="intro.html"><a href="intro.html#function_syx"><i class="fa fa-check"></i><b>1.4.5</b> Function syntax</a></li>
<li class="chapter" data-level="1.4.6" data-path="intro.html"><a href="intro.html#help"><i class="fa fa-check"></i><b>1.4.6</b> Getting help</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#install-package"><i class="fa fa-check"></i><b>1.5</b> Add-on packages</a><ul>
<li class="chapter" data-level="1.5.1" data-path="intro.html"><a href="intro.html#installing-a-package"><i class="fa fa-check"></i><b>1.5.1</b> Installing a package</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro.html"><a href="intro.html#loading-a-package"><i class="fa fa-check"></i><b>1.5.2</b> Loading a package</a></li>
<li class="chapter" data-level="1.5.3" data-path="intro.html"><a href="intro.html#install-from-github"><i class="fa fa-check"></i><b>1.5.3</b> Install from GitHub</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#projects"><i class="fa fa-check"></i><b>1.6</b> Organising a project</a><ul>
<li class="chapter" data-level="1.6.1" data-path="intro.html"><a href="intro.html#structure"><i class="fa fa-check"></i><b>1.6.1</b> Structure</a></li>
<li class="chapter" data-level="1.6.2" data-path="intro.html"><a href="intro.html#rmarkdown"><i class="fa fa-check"></i><b>1.6.2</b> Reproducible reports with R Markdown</a></li>
<li class="chapter" data-level="1.6.3" data-path="intro.html"><a href="intro.html#working-directory"><i class="fa fa-check"></i><b>1.6.3</b> Working Directory</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#glossary1"><i class="fa fa-check"></i><b>1.7</b> Glossary</a></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>1.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>2</b> Working with Data</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>2.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>2.2</b> Resources</a></li>
<li class="chapter" data-level="2.3" data-path="data.html"><a href="data.html#setup"><i class="fa fa-check"></i><b>2.3</b> Setup</a></li>
<li class="chapter" data-level="2.4" data-path="data.html"><a href="data.html#data-tables"><i class="fa fa-check"></i><b>2.4</b> Data tables</a><ul>
<li class="chapter" data-level="2.4.1" data-path="data.html"><a href="data.html#builtin"><i class="fa fa-check"></i><b>2.4.1</b> Built-in data</a></li>
<li class="chapter" data-level="2.4.2" data-path="data.html"><a href="data.html#import_data"><i class="fa fa-check"></i><b>2.4.2</b> Importing data</a></li>
<li class="chapter" data-level="2.4.3" data-path="data.html"><a href="data.html#creating-data"><i class="fa fa-check"></i><b>2.4.3</b> Creating data</a></li>
<li class="chapter" data-level="2.4.4" data-path="data.html"><a href="data.html#writing-data"><i class="fa fa-check"></i><b>2.4.4</b> Writing Data</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data.html"><a href="data.html#data_types"><i class="fa fa-check"></i><b>2.5</b> Basic data types</a><ul>
<li class="chapter" data-level="2.5.1" data-path="data.html"><a href="data.html#numeric-data"><i class="fa fa-check"></i><b>2.5.1</b> Numeric data</a></li>
<li class="chapter" data-level="2.5.2" data-path="data.html"><a href="data.html#character-data"><i class="fa fa-check"></i><b>2.5.2</b> Character data</a></li>
<li class="chapter" data-level="2.5.3" data-path="data.html"><a href="data.html#logical-data"><i class="fa fa-check"></i><b>2.5.3</b> Logical Data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="data.html"><a href="data.html#containers"><i class="fa fa-check"></i><b>2.6</b> Basic container types</a><ul>
<li class="chapter" data-level="2.6.1" data-path="data.html"><a href="data.html#vectors"><i class="fa fa-check"></i><b>2.6.1</b> Vectors</a></li>
<li class="chapter" data-level="2.6.2" data-path="data.html"><a href="data.html#lists"><i class="fa fa-check"></i><b>2.6.2</b> Lists</a></li>
<li class="chapter" data-level="2.6.3" data-path="data.html"><a href="data.html#tables"><i class="fa fa-check"></i><b>2.6.3</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="data.html"><a href="data.html#troubleshooting"><i class="fa fa-check"></i><b>2.7</b> Troubleshooting</a></li>
<li class="chapter" data-level="2.8" data-path="data.html"><a href="data.html#glossary2"><i class="fa fa-check"></i><b>2.8</b> Glossary</a></li>
<li class="chapter" data-level="2.9" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>2.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>3</b> Data Visualisation</a><ul>
<li class="chapter" data-level="3.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>3.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="3.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>3.1.1</b> Basic</a></li>
<li class="chapter" data-level="3.1.2" data-path="ggplot.html"><a href="ggplot.html#intermediate"><i class="fa fa-check"></i><b>3.1.2</b> Intermediate</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>3.2</b> Resources</a></li>
<li class="chapter" data-level="3.3" data-path="data.html"><a href="data.html#setup"><i class="fa fa-check"></i><b>3.3</b> Setup</a></li>
<li class="chapter" data-level="3.4" data-path="ggplot.html"><a href="ggplot.html#vartypes"><i class="fa fa-check"></i><b>3.4</b> Common Variable Combinations</a></li>
<li class="chapter" data-level="3.5" data-path="ggplot.html"><a href="ggplot.html#basic-plots"><i class="fa fa-check"></i><b>3.5</b> Basic Plots</a></li>
<li class="chapter" data-level="3.6" data-path="ggplot.html"><a href="ggplot.html#ggplots"><i class="fa fa-check"></i><b>3.6</b> GGplots</a></li>
<li class="chapter" data-level="3.7" data-path="ggplot.html"><a href="ggplot.html#common-plot-types"><i class="fa fa-check"></i><b>3.7</b> Common Plot Types</a><ul>
<li class="chapter" data-level="3.7.1" data-path="ggplot.html"><a href="ggplot.html#geom_bar"><i class="fa fa-check"></i><b>3.7.1</b> Bar plot</a></li>
<li class="chapter" data-level="3.7.2" data-path="ggplot.html"><a href="ggplot.html#geom_density"><i class="fa fa-check"></i><b>3.7.2</b> Density plot</a></li>
<li class="chapter" data-level="3.7.3" data-path="ggplot.html"><a href="ggplot.html#geom_freqpoly"><i class="fa fa-check"></i><b>3.7.3</b> Frequency polygons</a></li>
<li class="chapter" data-level="3.7.4" data-path="ggplot.html"><a href="ggplot.html#geom_histogram"><i class="fa fa-check"></i><b>3.7.4</b> Histogram</a></li>
<li class="chapter" data-level="3.7.5" data-path="ggplot.html"><a href="ggplot.html#geom_col"><i class="fa fa-check"></i><b>3.7.5</b> Column plot</a></li>
<li class="chapter" data-level="3.7.6" data-path="ggplot.html"><a href="ggplot.html#geom_boxplot"><i class="fa fa-check"></i><b>3.7.6</b> Boxplot</a></li>
<li class="chapter" data-level="3.7.7" data-path="ggplot.html"><a href="ggplot.html#geom_violin"><i class="fa fa-check"></i><b>3.7.7</b> Violin plot</a></li>
<li class="chapter" data-level="3.7.8" data-path="ggplot.html"><a href="ggplot.html#vertical_intervals"><i class="fa fa-check"></i><b>3.7.8</b> Vertical intervals</a></li>
<li class="chapter" data-level="3.7.9" data-path="ggplot.html"><a href="ggplot.html#geom_point"><i class="fa fa-check"></i><b>3.7.9</b> Scatter plot</a></li>
<li class="chapter" data-level="3.7.10" data-path="ggplot.html"><a href="ggplot.html#geom_smooth"><i class="fa fa-check"></i><b>3.7.10</b> Line graph</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="ggplot.html"><a href="ggplot.html#customisation"><i class="fa fa-check"></i><b>3.8</b> Customisation</a><ul>
<li class="chapter" data-level="3.8.1" data-path="ggplot.html"><a href="ggplot.html#custom-labels"><i class="fa fa-check"></i><b>3.8.1</b> Labels</a></li>
<li class="chapter" data-level="3.8.2" data-path="ggplot.html"><a href="ggplot.html#custom-colours"><i class="fa fa-check"></i><b>3.8.2</b> Colours</a></li>
<li class="chapter" data-level="3.8.3" data-path="ggplot.html"><a href="ggplot.html#themes"><i class="fa fa-check"></i><b>3.8.3</b> Themes</a></li>
<li class="chapter" data-level="3.8.4" data-path="ggplot.html"><a href="ggplot.html#ggsave"><i class="fa fa-check"></i><b>3.8.4</b> Save as file</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="ggplot.html"><a href="ggplot.html#combo_plots"><i class="fa fa-check"></i><b>3.9</b> Combination Plots</a><ul>
<li class="chapter" data-level="3.9.1" data-path="ggplot.html"><a href="ggplot.html#violinbox-plot"><i class="fa fa-check"></i><b>3.9.1</b> Violinbox plot</a></li>
<li class="chapter" data-level="3.9.2" data-path="ggplot.html"><a href="ggplot.html#violin-point-range-plot"><i class="fa fa-check"></i><b>3.9.2</b> Violin-point-range plot</a></li>
<li class="chapter" data-level="3.9.3" data-path="ggplot.html"><a href="ggplot.html#violin-jitter-plot"><i class="fa fa-check"></i><b>3.9.3</b> Violin-jitter plot</a></li>
<li class="chapter" data-level="3.9.4" data-path="ggplot.html"><a href="ggplot.html#scatter-line-graph"><i class="fa fa-check"></i><b>3.9.4</b> Scatter-line graph</a></li>
<li class="chapter" data-level="3.9.5" data-path="ggplot.html"><a href="ggplot.html#cowplot"><i class="fa fa-check"></i><b>3.9.5</b> Grid of plots</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="ggplot.html"><a href="ggplot.html#overlap"><i class="fa fa-check"></i><b>3.10</b> Overlapping Discrete Data</a><ul>
<li class="chapter" data-level="3.10.1" data-path="ggplot.html"><a href="ggplot.html#reducing-opacity"><i class="fa fa-check"></i><b>3.10.1</b> Reducing Opacity</a></li>
<li class="chapter" data-level="3.10.2" data-path="ggplot.html"><a href="ggplot.html#geom_count"><i class="fa fa-check"></i><b>3.10.2</b> Proportional Dot Plots</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="ggplot.html"><a href="ggplot.html#overlapping-continuous-data"><i class="fa fa-check"></i><b>3.11</b> Overlapping Continuous Data</a><ul>
<li class="chapter" data-level="3.11.1" data-path="ggplot.html"><a href="ggplot.html#geom_density2d"><i class="fa fa-check"></i><b>3.11.1</b> 2D Density Plot</a></li>
<li class="chapter" data-level="3.11.2" data-path="ggplot.html"><a href="ggplot.html#geom_bin2d"><i class="fa fa-check"></i><b>3.11.2</b> 2D Histogram</a></li>
<li class="chapter" data-level="3.11.3" data-path="ggplot.html"><a href="ggplot.html#geom_hex"><i class="fa fa-check"></i><b>3.11.3</b> Hexagonal Heatmap</a></li>
<li class="chapter" data-level="3.11.4" data-path="ggplot.html"><a href="ggplot.html#geom_tile"><i class="fa fa-check"></i><b>3.11.4</b> Correlation Heatmap</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="ggplot.html"><a href="ggplot.html#plotly"><i class="fa fa-check"></i><b>3.12</b> Interactive Plots</a></li>
<li class="chapter" data-level="3.13" data-path="ggplot.html"><a href="ggplot.html#glossary3"><i class="fa fa-check"></i><b>3.13</b> Glossary</a></li>
<li class="chapter" data-level="3.14" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>3.14</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tidyr.html"><a href="tidyr.html"><i class="fa fa-check"></i><b>4</b> Tidy Data</a><ul>
<li class="chapter" data-level="4.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>4.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="4.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>4.1.1</b> Basic</a></li>
<li class="chapter" data-level="4.1.2" data-path="tidyr.html"><a href="tidyr.html#advanced"><i class="fa fa-check"></i><b>4.1.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>4.2</b> Resources</a></li>
<li class="chapter" data-level="4.3" data-path="data.html"><a href="data.html#setup"><i class="fa fa-check"></i><b>4.3</b> Setup</a></li>
<li class="chapter" data-level="4.4" data-path="tidyr.html"><a href="tidyr.html#tidy-data"><i class="fa fa-check"></i><b>4.4</b> Tidy Data</a><ul>
<li class="chapter" data-level="4.4.1" data-path="tidyr.html"><a href="tidyr.html#three-rules"><i class="fa fa-check"></i><b>4.4.1</b> Three Rules</a></li>
<li class="chapter" data-level="4.4.2" data-path="tidyr.html"><a href="tidyr.html#wide_long"><i class="fa fa-check"></i><b>4.4.2</b> Wide versus long</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="tidyr.html"><a href="tidyr.html#pivot"><i class="fa fa-check"></i><b>4.5</b> Pivot Functions</a><ul>
<li class="chapter" data-level="4.5.1" data-path="tidyr.html"><a href="tidyr.html#load-data"><i class="fa fa-check"></i><b>4.5.1</b> Load Data</a></li>
<li class="chapter" data-level="4.5.2" data-path="tidyr.html"><a href="tidyr.html#pivot_longer"><i class="fa fa-check"></i><b>4.5.2</b> pivot_longer()</a></li>
<li class="chapter" data-level="4.5.3" data-path="tidyr.html"><a href="tidyr.html#pivot_wider"><i class="fa fa-check"></i><b>4.5.3</b> pivot_wider()</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="tidyr.html"><a href="tidyr.html#tidy-verbs"><i class="fa fa-check"></i><b>4.6</b> Tidy Verbs</a><ul>
<li class="chapter" data-level="4.6.1" data-path="tidyr.html"><a href="tidyr.html#gather"><i class="fa fa-check"></i><b>4.6.1</b> gather()</a></li>
<li class="chapter" data-level="4.6.2" data-path="tidyr.html"><a href="tidyr.html#separate"><i class="fa fa-check"></i><b>4.6.2</b> separate()</a></li>
<li class="chapter" data-level="4.6.3" data-path="tidyr.html"><a href="tidyr.html#unite"><i class="fa fa-check"></i><b>4.6.3</b> unite()</a></li>
<li class="chapter" data-level="4.6.4" data-path="tidyr.html"><a href="tidyr.html#spread"><i class="fa fa-check"></i><b>4.6.4</b> spread()</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="tidyr.html"><a href="tidyr.html#pipes"><i class="fa fa-check"></i><b>4.7</b> Pipes</a></li>
<li class="chapter" data-level="4.8" data-path="tidyr.html"><a href="tidyr.html#more-complex-example"><i class="fa fa-check"></i><b>4.8</b> More Complex Example</a><ul>
<li class="chapter" data-level="4.8.1" data-path="tidyr.html"><a href="tidyr.html#load-data-1"><i class="fa fa-check"></i><b>4.8.1</b> Load Data</a></li>
<li class="chapter" data-level="4.8.2" data-path="tidyr.html"><a href="tidyr.html#wide-to-long"><i class="fa fa-check"></i><b>4.8.2</b> Wide to Long</a></li>
<li class="chapter" data-level="4.8.3" data-path="tidyr.html"><a href="tidyr.html#one-piece-of-data-per-column"><i class="fa fa-check"></i><b>4.8.3</b> One Piece of Data per Column</a></li>
<li class="chapter" data-level="4.8.4" data-path="tidyr.html"><a href="tidyr.html#all-in-one-step"><i class="fa fa-check"></i><b>4.8.4</b> All in one step</a></li>
<li class="chapter" data-level="4.8.5" data-path="tidyr.html"><a href="tidyr.html#columns-by-year"><i class="fa fa-check"></i><b>4.8.5</b> Columns by Year</a></li>
<li class="chapter" data-level="4.8.6" data-path="tidyr.html"><a href="tidyr.html#experimentum-data"><i class="fa fa-check"></i><b>4.8.6</b> Experimentum Data</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="tidyr.html"><a href="tidyr.html#glossary4"><i class="fa fa-check"></i><b>4.9</b> Glossary</a></li>
<li class="chapter" data-level="4.10" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>4.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dplyr.html"><a href="dplyr.html"><i class="fa fa-check"></i><b>5</b> Data Wrangling</a><ul>
<li class="chapter" data-level="5.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>5.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="5.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>5.1.1</b> Basic</a></li>
<li class="chapter" data-level="5.1.2" data-path="ggplot.html"><a href="ggplot.html#intermediate"><i class="fa fa-check"></i><b>5.1.2</b> Intermediate</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>5.2</b> Resources</a></li>
<li class="chapter" data-level="5.3" data-path="data.html"><a href="data.html#setup"><i class="fa fa-check"></i><b>5.3</b> Setup</a><ul>
<li class="chapter" data-level="5.3.1" data-path="dplyr.html"><a href="dplyr.html#data-disgust"><i class="fa fa-check"></i><b>5.3.1</b> The <code>disgust</code> dataset</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="dplyr.html"><a href="dplyr.html#six-main-dplyr-verbs"><i class="fa fa-check"></i><b>5.4</b> Six main dplyr verbs</a><ul>
<li class="chapter" data-level="5.4.1" data-path="dplyr.html"><a href="dplyr.html#select"><i class="fa fa-check"></i><b>5.4.1</b> select()</a></li>
<li class="chapter" data-level="5.4.2" data-path="dplyr.html"><a href="dplyr.html#filter"><i class="fa fa-check"></i><b>5.4.2</b> filter()</a></li>
<li class="chapter" data-level="5.4.3" data-path="dplyr.html"><a href="dplyr.html#arrange"><i class="fa fa-check"></i><b>5.4.3</b> arrange()</a></li>
<li class="chapter" data-level="5.4.4" data-path="dplyr.html"><a href="dplyr.html#mutate"><i class="fa fa-check"></i><b>5.4.4</b> mutate()</a></li>
<li class="chapter" data-level="5.4.5" data-path="dplyr.html"><a href="dplyr.html#summarise"><i class="fa fa-check"></i><b>5.4.5</b> summarise()</a></li>
<li class="chapter" data-level="5.4.6" data-path="dplyr.html"><a href="dplyr.html#group_by"><i class="fa fa-check"></i><b>5.4.6</b> group_by()</a></li>
<li class="chapter" data-level="5.4.7" data-path="dplyr.html"><a href="dplyr.html#all-together"><i class="fa fa-check"></i><b>5.4.7</b> All Together</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="dplyr.html"><a href="dplyr.html#additional-dplyr-one-table-verbs"><i class="fa fa-check"></i><b>5.5</b> Additional dplyr one-table verbs</a><ul>
<li class="chapter" data-level="5.5.1" data-path="dplyr.html"><a href="dplyr.html#rename"><i class="fa fa-check"></i><b>5.5.1</b> rename()</a></li>
<li class="chapter" data-level="5.5.2" data-path="dplyr.html"><a href="dplyr.html#distinct"><i class="fa fa-check"></i><b>5.5.2</b> distinct()</a></li>
<li class="chapter" data-level="5.5.3" data-path="dplyr.html"><a href="dplyr.html#count"><i class="fa fa-check"></i><b>5.5.3</b> count()</a></li>
<li class="chapter" data-level="5.5.4" data-path="dplyr.html"><a href="dplyr.html#slice"><i class="fa fa-check"></i><b>5.5.4</b> slice()</a></li>
<li class="chapter" data-level="5.5.5" data-path="dplyr.html"><a href="dplyr.html#pull"><i class="fa fa-check"></i><b>5.5.5</b> pull()</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="dplyr.html"><a href="dplyr.html#window"><i class="fa fa-check"></i><b>5.6</b> Window functions</a><ul>
<li class="chapter" data-level="5.6.1" data-path="dplyr.html"><a href="dplyr.html#ranking-functions"><i class="fa fa-check"></i><b>5.6.1</b> Ranking functions</a></li>
<li class="chapter" data-level="5.6.2" data-path="dplyr.html"><a href="dplyr.html#offset-functions"><i class="fa fa-check"></i><b>5.6.2</b> Offset functions</a></li>
<li class="chapter" data-level="5.6.3" data-path="dplyr.html"><a href="dplyr.html#cumulative-aggregates"><i class="fa fa-check"></i><b>5.6.3</b> Cumulative aggregates</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="dplyr.html"><a href="dplyr.html#glossary5"><i class="fa fa-check"></i><b>5.7</b> Glossary</a></li>
<li class="chapter" data-level="5.8" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>5.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="joins.html"><a href="joins.html"><i class="fa fa-check"></i><b>6</b> Data Relations</a><ul>
<li class="chapter" data-level="6.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>6.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>6.2</b> Resources</a></li>
<li class="chapter" data-level="6.3" data-path="data.html"><a href="data.html#setup"><i class="fa fa-check"></i><b>6.3</b> Setup</a></li>
<li class="chapter" data-level="6.4" data-path="data.html"><a href="data.html#data"><i class="fa fa-check"></i><b>6.4</b> Data</a></li>
<li class="chapter" data-level="6.5" data-path="joins.html"><a href="joins.html#mutating-joins"><i class="fa fa-check"></i><b>6.5</b> Mutating Joins</a><ul>
<li class="chapter" data-level="6.5.1" data-path="joins.html"><a href="joins.html#left_join"><i class="fa fa-check"></i><b>6.5.1</b> left_join()</a></li>
<li class="chapter" data-level="6.5.2" data-path="joins.html"><a href="joins.html#right_join"><i class="fa fa-check"></i><b>6.5.2</b> right_join()</a></li>
<li class="chapter" data-level="6.5.3" data-path="joins.html"><a href="joins.html#inner_join"><i class="fa fa-check"></i><b>6.5.3</b> inner_join()</a></li>
<li class="chapter" data-level="6.5.4" data-path="joins.html"><a href="joins.html#full_join"><i class="fa fa-check"></i><b>6.5.4</b> full_join()</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="joins.html"><a href="joins.html#filtering-joins"><i class="fa fa-check"></i><b>6.6</b> Filtering Joins</a><ul>
<li class="chapter" data-level="6.6.1" data-path="joins.html"><a href="joins.html#semi_join"><i class="fa fa-check"></i><b>6.6.1</b> semi_join()</a></li>
<li class="chapter" data-level="6.6.2" data-path="joins.html"><a href="joins.html#anti_join"><i class="fa fa-check"></i><b>6.6.2</b> anti_join()</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="joins.html"><a href="joins.html#binding-joins"><i class="fa fa-check"></i><b>6.7</b> Binding Joins</a><ul>
<li class="chapter" data-level="6.7.1" data-path="joins.html"><a href="joins.html#bind_rows"><i class="fa fa-check"></i><b>6.7.1</b> bind_rows()</a></li>
<li class="chapter" data-level="6.7.2" data-path="joins.html"><a href="joins.html#bind_cols"><i class="fa fa-check"></i><b>6.7.2</b> bind_cols()</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="joins.html"><a href="joins.html#set-operations"><i class="fa fa-check"></i><b>6.8</b> Set Operations</a><ul>
<li class="chapter" data-level="6.8.1" data-path="joins.html"><a href="joins.html#intersect"><i class="fa fa-check"></i><b>6.8.1</b> intersect()</a></li>
<li class="chapter" data-level="6.8.2" data-path="joins.html"><a href="joins.html#union"><i class="fa fa-check"></i><b>6.8.2</b> union()</a></li>
<li class="chapter" data-level="6.8.3" data-path="joins.html"><a href="joins.html#setdiff"><i class="fa fa-check"></i><b>6.8.3</b> setdiff()</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="joins.html"><a href="joins.html#glossary6"><i class="fa fa-check"></i><b>6.9</b> Glossary</a></li>
<li class="chapter" data-level="6.10" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>6.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="func.html"><a href="func.html"><i class="fa fa-check"></i><b>7</b> Iteration &amp; Functions</a><ul>
<li class="chapter" data-level="7.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>7.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="7.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>7.1.1</b> Basic</a></li>
<li class="chapter" data-level="7.1.2" data-path="ggplot.html"><a href="ggplot.html#intermediate"><i class="fa fa-check"></i><b>7.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="7.1.3" data-path="tidyr.html"><a href="tidyr.html#advanced"><i class="fa fa-check"></i><b>7.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>7.2</b> Resources</a></li>
<li class="chapter" data-level="7.3" data-path="func.html"><a href="func.html#iteration-functions"><i class="fa fa-check"></i><b>7.3</b> Iteration functions</a><ul>
<li class="chapter" data-level="7.3.1" data-path="func.html"><a href="func.html#rep"><i class="fa fa-check"></i><b>7.3.1</b> rep()</a></li>
<li class="chapter" data-level="7.3.2" data-path="func.html"><a href="func.html#seq"><i class="fa fa-check"></i><b>7.3.2</b> seq()</a></li>
<li class="chapter" data-level="7.3.3" data-path="func.html"><a href="func.html#replicate"><i class="fa fa-check"></i><b>7.3.3</b> replicate()</a></li>
<li class="chapter" data-level="7.3.4" data-path="func.html"><a href="func.html#map-apply"><i class="fa fa-check"></i><b>7.3.4</b> map() and apply() functions</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="func.html"><a href="func.html#custom-functions"><i class="fa fa-check"></i><b>7.4</b> Custom functions</a><ul>
<li class="chapter" data-level="7.4.1" data-path="func.html"><a href="func.html#structure-function"><i class="fa fa-check"></i><b>7.4.1</b> Structuring a function</a></li>
<li class="chapter" data-level="7.4.2" data-path="func.html"><a href="func.html#arguments"><i class="fa fa-check"></i><b>7.4.2</b> Arguments</a></li>
<li class="chapter" data-level="7.4.3" data-path="func.html"><a href="func.html#defaults"><i class="fa fa-check"></i><b>7.4.3</b> Argument defaults</a></li>
<li class="chapter" data-level="7.4.4" data-path="func.html"><a href="func.html#scope"><i class="fa fa-check"></i><b>7.4.4</b> Scope</a></li>
<li class="chapter" data-level="7.4.5" data-path="func.html"><a href="func.html#warnings-errors"><i class="fa fa-check"></i><b>7.4.5</b> Warnings and errors</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="func.html"><a href="func.html#iterating-your-own-functions"><i class="fa fa-check"></i><b>7.5</b> Iterating your own functions</a><ul>
<li class="chapter" data-level="7.5.1" data-path="func.html"><a href="func.html#rnorm"><i class="fa fa-check"></i><b>7.5.1</b> rnorm()</a></li>
<li class="chapter" data-level="7.5.2" data-path="func.html"><a href="func.html#tibbletibble"><i class="fa fa-check"></i><b>7.5.2</b> tibble::tibble()</a></li>
<li class="chapter" data-level="7.5.3" data-path="func.html"><a href="func.html#t.test"><i class="fa fa-check"></i><b>7.5.3</b> t.test()</a></li>
<li class="chapter" data-level="7.5.4" data-path="func.html"><a href="func.html#broomtidy"><i class="fa fa-check"></i><b>7.5.4</b> broom::tidy()</a></li>
<li class="chapter" data-level="7.5.5" data-path="func.html"><a href="func.html#custom-function-t_sim"><i class="fa fa-check"></i><b>7.5.5</b> Custom function: t_sim()</a></li>
<li class="chapter" data-level="7.5.6" data-path="func.html"><a href="func.html#iterate-t_sim"><i class="fa fa-check"></i><b>7.5.6</b> Iterate t_sim()</a></li>
<li class="chapter" data-level="7.5.7" data-path="func.html"><a href="func.html#seed"><i class="fa fa-check"></i><b>7.5.7</b> Set seed</a></li>
<li class="chapter" data-level="7.5.8" data-path="func.html"><a href="func.html#add-arguments"><i class="fa fa-check"></i><b>7.5.8</b> Add arguments</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="func.html"><a href="func.html#glossary7"><i class="fa fa-check"></i><b>7.6</b> Glossary</a></li>
<li class="chapter" data-level="7.7" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="sim.html"><a href="sim.html"><i class="fa fa-check"></i><b>8</b> Probability &amp; Simulation</a><ul>
<li class="chapter" data-level="8.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>8.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="8.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>8.1.1</b> Basic</a></li>
<li class="chapter" data-level="8.1.2" data-path="ggplot.html"><a href="ggplot.html#intermediate"><i class="fa fa-check"></i><b>8.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="8.1.3" data-path="tidyr.html"><a href="tidyr.html#advanced"><i class="fa fa-check"></i><b>8.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>8.2</b> Resources</a></li>
<li class="chapter" data-level="8.3" data-path="sim.html"><a href="sim.html#distributions"><i class="fa fa-check"></i><b>8.3</b> Distributions</a><ul>
<li class="chapter" data-level="8.3.1" data-path="sim.html"><a href="sim.html#uniform"><i class="fa fa-check"></i><b>8.3.1</b> Uniform Distribution</a></li>
<li class="chapter" data-level="8.3.2" data-path="sim.html"><a href="sim.html#binomial"><i class="fa fa-check"></i><b>8.3.2</b> Binomial Distribution</a></li>
<li class="chapter" data-level="8.3.3" data-path="sim.html"><a href="sim.html#normal"><i class="fa fa-check"></i><b>8.3.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="8.3.4" data-path="sim.html"><a href="sim.html#bivariate-normal"><i class="fa fa-check"></i><b>8.3.4</b> Bivariate Normal</a></li>
<li class="chapter" data-level="8.3.5" data-path="sim.html"><a href="sim.html#mvnorm"><i class="fa fa-check"></i><b>8.3.5</b> Multivariate Normal</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sim.html"><a href="sim.html#example"><i class="fa fa-check"></i><b>8.4</b> Example</a><ul>
<li class="chapter" data-level="8.4.1" data-path="sim.html"><a href="sim.html#load-wrangle"><i class="fa fa-check"></i><b>8.4.1</b> Load &amp; wrangle</a></li>
<li class="chapter" data-level="8.4.2" data-path="sim.html"><a href="sim.html#plot"><i class="fa fa-check"></i><b>8.4.2</b> Plot</a></li>
<li class="chapter" data-level="8.4.3" data-path="sim.html"><a href="sim.html#get-means-and-sds"><i class="fa fa-check"></i><b>8.4.3</b> Get means and SDs</a></li>
<li class="chapter" data-level="8.4.4" data-path="sim.html"><a href="sim.html#simulate-a-population"><i class="fa fa-check"></i><b>8.4.4</b> Simulate a population</a></li>
<li class="chapter" data-level="8.4.5" data-path="sim.html"><a href="sim.html#analyse-simulated-data"><i class="fa fa-check"></i><b>8.4.5</b> Analyse simulated data</a></li>
<li class="chapter" data-level="8.4.6" data-path="sim.html"><a href="sim.html#replicate-simulation"><i class="fa fa-check"></i><b>8.4.6</b> Replicate simulation</a></li>
<li class="chapter" data-level="8.4.7" data-path="sim.html"><a href="sim.html#one-tailed-prediction"><i class="fa fa-check"></i><b>8.4.7</b> One-tailed prediction</a></li>
<li class="chapter" data-level="8.4.8" data-path="sim.html"><a href="sim.html#range-of-sample-sizes"><i class="fa fa-check"></i><b>8.4.8</b> Range of sample sizes</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="sim.html"><a href="sim.html#glossary8"><i class="fa fa-check"></i><b>8.5</b> Glossary</a></li>
<li class="chapter" data-level="8.6" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>8.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>9</b> Introduction to GLM</a><ul>
<li class="chapter" data-level="9.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>9.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="9.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>9.1.1</b> Basic</a></li>
<li class="chapter" data-level="9.1.2" data-path="ggplot.html"><a href="ggplot.html#intermediate"><i class="fa fa-check"></i><b>9.1.2</b> Intermediate</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>9.2</b> Resources</a></li>
<li class="chapter" data-level="9.3" data-path="data.html"><a href="data.html#setup"><i class="fa fa-check"></i><b>9.3</b> Setup</a></li>
<li class="chapter" data-level="9.4" data-path="glm.html"><a href="glm.html#glm-1"><i class="fa fa-check"></i><b>9.4</b> GLM</a><ul>
<li class="chapter" data-level="9.4.1" data-path="glm.html"><a href="glm.html#what-is-the-glm"><i class="fa fa-check"></i><b>9.4.1</b> What is the GLM?</a></li>
<li class="chapter" data-level="9.4.2" data-path="glm.html"><a href="glm.html#glm-components"><i class="fa fa-check"></i><b>9.4.2</b> Components</a></li>
<li class="chapter" data-level="9.4.3" data-path="glm.html"><a href="glm.html#sim-glm"><i class="fa fa-check"></i><b>9.4.3</b> Simulating data from GLM</a></li>
<li class="chapter" data-level="9.4.4" data-path="glm.html"><a href="glm.html#linear-regression"><i class="fa fa-check"></i><b>9.4.4</b> Linear Regression</a></li>
<li class="chapter" data-level="9.4.5" data-path="glm.html"><a href="glm.html#residuals"><i class="fa fa-check"></i><b>9.4.5</b> Residuals</a></li>
<li class="chapter" data-level="9.4.6" data-path="glm.html"><a href="glm.html#predict"><i class="fa fa-check"></i><b>9.4.6</b> Predict New Values</a></li>
<li class="chapter" data-level="9.4.7" data-path="glm.html"><a href="glm.html#coding-schemes"><i class="fa fa-check"></i><b>9.4.7</b> Coding Categorical Variables</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="glm.html"><a href="glm.html#test-rels"><i class="fa fa-check"></i><b>9.5</b> Relationships among tests</a><ul>
<li class="chapter" data-level="9.5.1" data-path="sim.html"><a href="sim.html#t-test"><i class="fa fa-check"></i><b>9.5.1</b> T-test</a></li>
<li class="chapter" data-level="9.5.2" data-path="glm.html"><a href="glm.html#anova"><i class="fa fa-check"></i><b>9.5.2</b> ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="glm.html"><a href="glm.html#understanding-anova"><i class="fa fa-check"></i><b>9.6</b> Understanding ANOVA</a><ul>
<li class="chapter" data-level="9.6.1" data-path="glm.html"><a href="glm.html#means-variability-and-deviation-scores"><i class="fa fa-check"></i><b>9.6.1</b> Means, Variability, and Deviation Scores</a></li>
<li class="chapter" data-level="9.6.2" data-path="glm.html"><a href="glm.html#decomp"><i class="fa fa-check"></i><b>9.6.2</b> Decomposition matrices</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="glm.html"><a href="glm.html#glossary9"><i class="fa fa-check"></i><b>9.7</b> Glossary</a></li>
<li class="chapter" data-level="9.8" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>9.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="repro.html"><a href="repro.html"><i class="fa fa-check"></i><b>10</b> Reproducible Workflows</a><ul>
<li class="chapter" data-level="10.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>10.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="10.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>10.1.1</b> Basic</a></li>
<li class="chapter" data-level="10.1.2" data-path="ggplot.html"><a href="ggplot.html#intermediate"><i class="fa fa-check"></i><b>10.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="10.1.3" data-path="tidyr.html"><a href="tidyr.html#advanced"><i class="fa fa-check"></i><b>10.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="intro.html"><a href="intro.html#resources"><i class="fa fa-check"></i><b>10.2</b> Resources</a></li>
<li class="chapter" data-level="10.3" data-path="repro.html"><a href="repro.html#r-markdown"><i class="fa fa-check"></i><b>10.3</b> R Markdown</a><ul>
<li class="chapter" data-level="10.3.1" data-path="repro.html"><a href="repro.html#knitr-options"><i class="fa fa-check"></i><b>10.3.1</b> knitr options</a></li>
<li class="chapter" data-level="10.3.2" data-path="repro.html"><a href="repro.html#yaml-header"><i class="fa fa-check"></i><b>10.3.2</b> YAML Header</a></li>
<li class="chapter" data-level="10.3.3" data-path="repro.html"><a href="repro.html#toc-and-document-headers"><i class="fa fa-check"></i><b>10.3.3</b> TOC and Document Headers</a></li>
<li class="chapter" data-level="10.3.4" data-path="repro.html"><a href="repro.html#code-chunks"><i class="fa fa-check"></i><b>10.3.4</b> Code Chunks</a></li>
<li class="chapter" data-level="10.3.5" data-path="repro.html"><a href="repro.html#bibliography"><i class="fa fa-check"></i><b>10.3.5</b> Bibliography</a></li>
<li class="chapter" data-level="10.3.6" data-path="repro.html"><a href="repro.html#output-formats"><i class="fa fa-check"></i><b>10.3.6</b> Output Formats</a></li>
<li class="chapter" data-level="10.3.7" data-path="repro.html"><a href="repro.html#computational-reproducibility"><i class="fa fa-check"></i><b>10.3.7</b> Computational Reproducibility</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="repro.html"><a href="repro.html#glossary10"><i class="fa fa-check"></i><b>10.4</b> Glossary</a></li>
<li class="chapter" data-level="10.5" data-path="repro.html"><a href="repro.html#references"><i class="fa fa-check"></i><b>10.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a><ul>
<li class="chapter" data-level="10.6" data-path="acknowledgements.html"><a href="acknowledgements.html#contributors"><i class="fa fa-check"></i><b>10.6</b> Contributors</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="installingr.html"><a href="installingr.html"><i class="fa fa-check"></i><b>A</b> Installing R</a><ul>
<li class="chapter" data-level="A.1" data-path="installingr.html"><a href="installingr.html#installing-base-r"><i class="fa fa-check"></i><b>A.1</b> Installing Base R</a></li>
<li class="chapter" data-level="A.2" data-path="installingr.html"><a href="installingr.html#installing-rstudio"><i class="fa fa-check"></i><b>A.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="A.3" data-path="installingr.html"><a href="installingr.html#installing-latex"><i class="fa fa-check"></i><b>A.3</b> Installing LaTeX</a></li>
<li class="chapter" data-level="A.4" data-path="installingr.html"><a href="installingr.html#rstudio-online"><i class="fa fa-check"></i><b>A.4</b> RStudio Online</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="symbols.html"><a href="symbols.html"><i class="fa fa-check"></i><b>B</b> Symbols</a></li>
<li class="chapter" data-level="C" data-path="exercise-answers.html"><a href="exercise-answers.html"><i class="fa fa-check"></i><b>C</b> Exercise Answers</a></li>
<li class="chapter" data-level="D" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>D</b> Datasets</a></li>
<li class="chapter" data-level="E" data-path="repro.html"><a href="repro.html#references"><i class="fa fa-check"></i><b>E</b> References</a></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Skills for Reproducible Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tidyr" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Tidy Data</h1>
<p><img src="images/memes/messy_data.jpg" class="meme right"
     alt="A giant demon emerging from fire labelled 'messy data'; in front is a tiny human labelled 'R User'"></p>
<div id="learning-objectives" class="section level2">
<h2><span class="header-section-number">4.1</span> Learning Objectives</h2>
<div id="basic" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Basic</h3>
<ol style="list-style-type: decimal">
<li>Understand the concept of <a href="tidyr.html#tidy-data">tidy data</a> <a href="https://youtu.be/EsSN4OdsNpc" class="video">(video)</a></li>
<li>Be able to convert between long and wide formats using pivot functions <a href="https://youtu.be/4dvLmjhwN8I" class="video">(video)</a>
<ul>
<li><a href="tidyr.html#pivot_longer"><code>pivot_longer()</code></a></li>
<li><a href="tidyr.html#pivot_wider"><code>pivot_wider()</code></a></li>
</ul></li>
<li>Be able to use the 4 basic <code>tidyr</code> verbs <a href="https://youtu.be/oUWjb0JC8zM" class="video">(video)</a>
<ul>
<li><a href="tidyr.html#gather"><code>gather()</code></a></li>
<li><a href="tidyr.html#separate"><code>separate()</code></a></li>
<li><a href="tidyr.html#spread"><code>spread()</code></a></li>
<li><a href="tidyr.html#unite"><code>unite()</code></a></li>
</ul></li>
<li>Be able to chain functions using <a href="tidyr.html#pipes">pipes</a> <a href="https://youtu.be/itfrlLaN4SE" class="video">(video)</a></li>
</ol>
</div>
<div id="advanced" class="section level3">
<h3><span class="header-section-number">4.1.2</span> Advanced</h3>
<ol start="5" style="list-style-type: decimal">
<li>Be able to use <a href="#regex">regular expressions</a> to separate complex columns</li>
</ol>
</div>
</div>
<div id="resources" class="section level2">
<h2><span class="header-section-number">4.2</span> Resources</h2>
<ul>
<li><a href="http://vita.had.co.nz/papers/tidy-data.html">Tidy Data</a></li>
<li><a href="http://r4ds.had.co.nz/tidy-data.html">Chapter 12: Tidy Data</a> in <em>R for Data Science</em></li>
<li><a href="http://r4ds.had.co.nz/pipes.html">Chapter 18: Pipes</a> in <em>R for Data Science</em></li>
<li><a href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">Data wrangling cheat sheet</a></li>
</ul>
</div>
<div id="setup" class="section level2">
<h2><span class="header-section-number">4.3</span> Setup</h2>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="tidyr.html#cb181-1"></a><span class="co"># libraries needed</span></span>
<span id="cb181-2"><a href="tidyr.html#cb181-2"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb181-3"><a href="tidyr.html#cb181-3"></a><span class="kw">library</span>(dataskills)</span>
<span id="cb181-4"><a href="tidyr.html#cb181-4"></a></span>
<span id="cb181-5"><a href="tidyr.html#cb181-5"></a><span class="kw">set.seed</span>(<span class="dv">8675309</span>) <span class="co"># makes sure random numbers are reproducible</span></span></code></pre></div>
</div>
<div id="tidy-data" class="section level2">
<h2><span class="header-section-number">4.4</span> Tidy Data</h2>
<div id="three-rules" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Three Rules</h3>
<ul>
<li>Each <a class='glossary' target='_blank' title='A word that identifies and stores the value of some data for later use.' href='https://psyteachr.github.io/glossary/v#variable'>variable</a> must have its own column</li>
<li>Each <a class='glossary' target='_blank' title='All of the data about a single trial or question.' href='https://psyteachr.github.io/glossary/o#observation'>observation</a> must have its own row</li>
<li>Each <a class='glossary' target='_blank' title='A single number or piece of data.' href='https://psyteachr.github.io/glossary/v#value'>value</a> must have its own cell</li>
</ul>
<p>This table has three observations per row and the <code>total_meanRT</code> column contains two values.</p>
<table>
<caption><span id="tab:unnamed-chunk-1">Table 4.1: </span>Untidy table</caption>
<thead>
<tr class="header">
<th align="right">id</th>
<th align="right">score_1</th>
<th align="right">score_2</th>
<th align="right">score_3</th>
<th align="right">rt_1</th>
<th align="right">rt_2</th>
<th align="right">rt_3</th>
<th align="left">total_meanRT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">4</td>
<td align="right">3</td>
<td align="right">7</td>
<td align="right">857</td>
<td align="right">890</td>
<td align="right">859</td>
<td align="left">14 (869)</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">902</td>
<td align="right">900</td>
<td align="right">959</td>
<td align="left">5 (920)</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">2</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">757</td>
<td align="right">823</td>
<td align="right">901</td>
<td align="left">11 (827)</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">6</td>
<td align="right">2</td>
<td align="right">6</td>
<td align="right">844</td>
<td align="right">788</td>
<td align="right">624</td>
<td align="left">14 (752)</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">1</td>
<td align="right">7</td>
<td align="right">2</td>
<td align="right">659</td>
<td align="right">764</td>
<td align="right">690</td>
<td align="left">10 (704)</td>
</tr>
</tbody>
</table>
<p>This is the tidy version.</p>
<table>
<caption><span id="tab:unnamed-chunk-1">Table 4.1: </span>Tidy table</caption>
<thead>
<tr class="header">
<th align="right">id</th>
<th align="left">trial</th>
<th align="right">rt</th>
<th align="right">score</th>
<th align="left">total</th>
<th align="left">mean_rt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">1</td>
<td align="right">857</td>
<td align="right">4</td>
<td align="left">14</td>
<td align="left">869</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">2</td>
<td align="right">890</td>
<td align="right">3</td>
<td align="left">14</td>
<td align="left">869</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">3</td>
<td align="right">859</td>
<td align="right">7</td>
<td align="left">14</td>
<td align="left">869</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">1</td>
<td align="right">902</td>
<td align="right">3</td>
<td align="left">5</td>
<td align="left">920</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="left">2</td>
<td align="right">900</td>
<td align="right">1</td>
<td align="left">5</td>
<td align="left">920</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">3</td>
<td align="right">959</td>
<td align="right">1</td>
<td align="left">5</td>
<td align="left">920</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">1</td>
<td align="right">757</td>
<td align="right">2</td>
<td align="left">11</td>
<td align="left">827</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="left">2</td>
<td align="right">823</td>
<td align="right">5</td>
<td align="left">11</td>
<td align="left">827</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">3</td>
<td align="right">901</td>
<td align="right">4</td>
<td align="left">11</td>
<td align="left">827</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">1</td>
<td align="right">844</td>
<td align="right">6</td>
<td align="left">14</td>
<td align="left">752</td>
</tr>
<tr class="odd">
<td align="right">4</td>
<td align="left">2</td>
<td align="right">788</td>
<td align="right">2</td>
<td align="left">14</td>
<td align="left">752</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">3</td>
<td align="right">624</td>
<td align="right">6</td>
<td align="left">14</td>
<td align="left">752</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">1</td>
<td align="right">659</td>
<td align="right">1</td>
<td align="left">10</td>
<td align="left">704</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="left">2</td>
<td align="right">764</td>
<td align="right">7</td>
<td align="left">10</td>
<td align="left">704</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">3</td>
<td align="right">690</td>
<td align="right">2</td>
<td align="left">10</td>
<td align="left">704</td>
</tr>
</tbody>
</table>
</div>
<div id="wide_long" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Wide versus long</h3>
<p>Data tables can be in <a class='glossary' target='_blank' title='Data where all of the observations about one subject are in the same row' href='https://psyteachr.github.io/glossary/w#wide'>wide</a> format or <a class='glossary' target='_blank' title='Data where each observation is on a separate row' href='https://psyteachr.github.io/glossary/l#long'>long</a> format (and sometimes a mix of the two). Wide data are where all of the observations about one subject are in the same row, while long data are where each observation is on a separate row. You often need to convert between these formats to do different types of analyses or data processing.</p>
<p>Imagine a study where each subject completes a questionnaire with three items. Each answer is an <a class='glossary' target='_blank' title='All of the data about a single trial or question.' href='https://psyteachr.github.io/glossary/o#observation'>observation</a> of that subject. You are probably most familiar with data like this in a wide format, where the subject <code>id</code> is in one column, and each of the three item responses is in its own column.</p>
<table>
<caption><span id="tab:wide-data">Table 4.2: </span>Wide data</caption>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="right">Q1</th>
<th align="right">Q2</th>
<th align="right">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">A</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">6</td>
</tr>
</tbody>
</table>
<p>The same data can be represented in a long format by creating a new column that specifies what <code>item</code> the observation is from and a new column that specifies the <code>value</code> of that observation.</p>
<table>
<caption><span id="tab:long-data">Table 4.3: </span>Long data</caption>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">item</th>
<th align="right">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">A</td>
<td align="left">Q1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="left">Q1</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">A</td>
<td align="left">Q2</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="left">Q2</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="left">A</td>
<td align="left">Q3</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="left">Q3</td>
<td align="right">6</td>
</tr>
</tbody>
</table>
<div class="try">
<p>Create a long version of the following table.</p>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">fav_colour</th>
<th align="left">fav_animal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Lisa</td>
<td align="left">red</td>
<td align="left">echidna</td>
</tr>
<tr class="even">
<td align="left">Robbie</td>
<td align="left">orange</td>
<td align="left">babirusa</td>
</tr>
<tr class="odd">
<td align="left">Steven</td>
<td align="left">green</td>
<td align="left">frog</td>
</tr>
</tbody>
</table>
<div class="solution">
<button class>
Answer
</button>
<p>Your answer doesn’t need to have the same column headers or be in the same order.</p>
<table>
<thead>
<tr class="header">
<th align="left">id</th>
<th align="left">fav</th>
<th align="left">answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Lisa</td>
<td align="left">colour</td>
<td align="left">red</td>
</tr>
<tr class="even">
<td align="left">Lisa</td>
<td align="left">animal</td>
<td align="left">echidna</td>
</tr>
<tr class="odd">
<td align="left">Robbie</td>
<td align="left">colour</td>
<td align="left">orange</td>
</tr>
<tr class="even">
<td align="left">Robbie</td>
<td align="left">animal</td>
<td align="left">babirusa</td>
</tr>
<tr class="odd">
<td align="left">Steven</td>
<td align="left">colour</td>
<td align="left">green</td>
</tr>
<tr class="even">
<td align="left">Steven</td>
<td align="left">animal</td>
<td align="left">frog</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<div id="pivot" class="section level2">
<h2><span class="header-section-number">4.5</span> Pivot Functions</h2>
<p>The pivot functions allow you to transform a data table from wide to long or long to wide in one step.</p>
<div id="load-data" class="section level3">
<h3><span class="header-section-number">4.5.1</span> Load Data</h3>
<p>We will used the dataset <code>personality</code> from the dataskills package (or download the data from <a href="https://psyteachr.github.io/msc-data-skills/data/personality.csv">personality.csv</a>). These data are from a 5-factor (personality) personality questionnaire. Each question is labelled with the domain (Op = openness, Co = conscientiousness, Ex = extroversion, Ag = agreeableness, and Ne = neuroticism) and the question number.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="tidyr.html#cb182-1"></a><span class="kw">data</span>(<span class="st">&quot;personality&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;dataskills&quot;</span>)</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="4%" />
<col width="5%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
<col width="2%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">user_id</th>
<th align="left">date</th>
<th align="right">Op1</th>
<th align="right">Ne1</th>
<th align="right">Ne2</th>
<th align="right">Op2</th>
<th align="right">Ex1</th>
<th align="right">Ex2</th>
<th align="right">Co1</th>
<th align="right">Co2</th>
<th align="right">Ne3</th>
<th align="right">Ag1</th>
<th align="right">Ag2</th>
<th align="right">Ne4</th>
<th align="right">Ex3</th>
<th align="right">Co3</th>
<th align="right">Op3</th>
<th align="right">Ex4</th>
<th align="right">Op4</th>
<th align="right">Ex5</th>
<th align="right">Ag3</th>
<th align="right">Co4</th>
<th align="right">Co5</th>
<th align="right">Ne5</th>
<th align="right">Op5</th>
<th align="right">Ag4</th>
<th align="right">Op6</th>
<th align="right">Co6</th>
<th align="right">Ex6</th>
<th align="right">Ne6</th>
<th align="right">Co7</th>
<th align="right">Ag5</th>
<th align="right">Co8</th>
<th align="right">Ex7</th>
<th align="right">Ne7</th>
<th align="right">Co9</th>
<th align="right">Op7</th>
<th align="right">Ne8</th>
<th align="right">Ag6</th>
<th align="right">Ag7</th>
<th align="right">Co10</th>
<th align="right">Ex8</th>
<th align="right">Ex9</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="left">2006-03-23</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">NA</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">NA</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">2006-02-08</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="left">2005-10-24</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="left">2005-12-07</td>
<td align="right">6</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">5</td>
<td align="right">3</td>
<td align="right">5</td>
<td align="right">3</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="left">2006-07-27</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">6</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">5</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">3</td>
<td align="right">6</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">108</td>
<td align="left">2006-02-28</td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">3</td>
<td align="right">5</td>
<td align="right">4</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
</div>
<div id="pivot_longer" class="section level3">
<h3><span class="header-section-number">4.5.2</span> pivot_longer()</h3>
<p><code>pivot_longer()</code> converts a wide data table to long format by converting the headers from specified columns into the values of new columns, and combining the values of those columns into a new condensed column.</p>
<ul>
<li><code>cols</code> refers to the columns you want to make long You can refer to them by their names, like <code>col1, col2, col3, col4</code> or <code>col1:col4</code> or by their numbers, like <code>8, 9, 10</code> or <code>8:10</code>.</li>
<li><code>names_to</code> is what you want to call the new columns that the gathered column headers will go into; it’s “domain” and “qnumber” in this example.</li>
<li><code>names_sep</code> is an optional argument if you have more than one value for <code>names_to</code>. It specifies the characters or position to split the values of the <code>cols</code> headers.</li>
<li><code>values_to</code> is what you want to call the values in the columns <code>...</code>; they’re “score” in this example.</li>
</ul>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="tidyr.html#cb183-1"></a>personality_long &lt;-<span class="st"> </span><span class="kw">pivot_longer</span>(</span>
<span id="cb183-2"><a href="tidyr.html#cb183-2"></a>  <span class="dt">data =</span> personality, </span>
<span id="cb183-3"><a href="tidyr.html#cb183-3"></a>  <span class="dt">cols =</span> Op1<span class="op">:</span>Ex9,                    <span class="co"># columns to make long </span></span>
<span id="cb183-4"><a href="tidyr.html#cb183-4"></a>  <span class="dt">names_to =</span> <span class="kw">c</span>(<span class="st">&quot;domain&quot;</span>, <span class="st">&quot;qnumber&quot;</span>), <span class="co"># new column names for headers</span></span>
<span id="cb183-5"><a href="tidyr.html#cb183-5"></a>  <span class="dt">names_sep =</span> <span class="dv">2</span>,                     <span class="co"># how to split the headers</span></span>
<span id="cb183-6"><a href="tidyr.html#cb183-6"></a>  <span class="dt">values_to =</span> <span class="st">&quot;score&quot;</span>                <span class="co"># new column name for values</span></span>
<span id="cb183-7"><a href="tidyr.html#cb183-7"></a>) <span class="op">%&gt;%</span></span>
<span id="cb183-8"><a href="tidyr.html#cb183-8"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 615,000
## Columns: 5
## $ user_id &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ date    &lt;date&gt; 2006-03-23, 2006-03-23, 2006-03-23, 2006-03-23, 2006-03-23, …
## $ domain  &lt;chr&gt; &quot;Op&quot;, &quot;Ne&quot;, &quot;Ne&quot;, &quot;Op&quot;, &quot;Ex&quot;, &quot;Ex&quot;, &quot;Co&quot;, &quot;Co&quot;, &quot;Ne&quot;, &quot;Ag&quot;, &quot;…
## $ qnumber &lt;chr&gt; &quot;1&quot;, &quot;1&quot;, &quot;2&quot;, &quot;2&quot;, &quot;1&quot;, &quot;2&quot;, &quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;1&quot;, &quot;2&quot;, &quot;4&quot;, &quot;…
## $ score   &lt;dbl&gt; 3, 4, 0, 6, 3, 3, 3, 3, 0, 2, 1, 3, 3, 2, 2, 1, 3, 3, 1, 3, 0…</code></pre>
<div class="info">
<p>
You can pipe a data table to <code>glimpse()</code> at the end to have a quick look at it. It will still save to the object.
</p>
</div>
<div class="try">
<p>What would you set <code>names_sep</code> to in order to split the <code>cols</code> headers listed below into the results?</p>
<table>
<colgroup>
<col width="23%" />
<col width="38%" />
<col width="38%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><code>cols</code></th>
<th align="left"><code>names_to</code></th>
<th align="left"><code>names_sep</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>A_1</code>, <code>A_2</code>, <code>B_1</code>, <code>B_2</code></td>
<td align="left"><code>c("condition", "version")</code></td>
<td align="left"><select class='solveme' name='q_1' data-answer='["_"]'> <option></option> <option>A</option> <option>B</option> <option>1</option> <option>2</option> <option>_</option></select></td>
</tr>
<tr class="even">
<td align="left"><code>A1</code>, <code>A2</code>, <code>B1</code>, <code>B2</code></td>
<td align="left"><code>c("condition", "version")</code></td>
<td align="left"><select class='solveme' name='q_2' data-answer='["1"]'> <option></option> <option>A</option> <option>B</option> <option>1</option> <option>2</option> <option>_</option></select></td>
</tr>
<tr class="odd">
<td align="left"><code>cat-day&amp;pre</code>, <code>cat-day&amp;post</code>, <code>cat-night&amp;pre</code>, <code>cat-night&amp;post</code>, <code>dog-day&amp;pre</code>, <code>dog-day&amp;post</code>, <code>dog-night&amp;pre</code>, <code>dog-night&amp;post</code></td>
<td align="left"><code>c("pet", "time", "condition")</code></td>
<td align="left"><select class='solveme' name='q_3' data-answer='["-","-|&"]'> <option></option> <option>-</option> <option>&amp;</option> <option>-</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="pivot_wider" class="section level3">
<h3><span class="header-section-number">4.5.3</span> pivot_wider()</h3>
<p>We can also go from long to wide format using the <code>pivot_wider()</code> function.</p>
<ul>
<li><code>names_from</code> is the columns that contain your new column headers.</li>
<li><code>values_from</code> is the column that contains the values for the new columns.</li>
<li><code>names_sep</code> is the character string used to join names if <code>names_from</code> is more than one column.</li>
</ul>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="tidyr.html#cb185-1"></a>personality_wide &lt;-<span class="st"> </span><span class="kw">pivot_wider</span>(</span>
<span id="cb185-2"><a href="tidyr.html#cb185-2"></a>  <span class="dt">data =</span> personality_long,</span>
<span id="cb185-3"><a href="tidyr.html#cb185-3"></a>  <span class="dt">names_from =</span> <span class="kw">c</span>(domain, qnumber),</span>
<span id="cb185-4"><a href="tidyr.html#cb185-4"></a>  <span class="dt">values_from =</span> score,</span>
<span id="cb185-5"><a href="tidyr.html#cb185-5"></a>  <span class="dt">names_sep =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb185-6"><a href="tidyr.html#cb185-6"></a>) <span class="op">%&gt;%</span></span>
<span id="cb185-7"><a href="tidyr.html#cb185-7"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 15,000
## Columns: 43
## $ user_id &lt;dbl&gt; 0, 1, 2, 5, 8, 108, 233, 298, 426, 436, 685, 807, 871, 881, 9…
## $ date    &lt;date&gt; 2006-03-23, 2006-02-08, 2005-10-24, 2005-12-07, 2006-07-27, …
## $ Op1     &lt;dbl&gt; 3, 6, 6, 6, 6, 3, 3, 6, 6, 3, 4, 5, 5, 5, 6, 4, 1, 2, 5, 6, 4…
## $ Ne1     &lt;dbl&gt; 4, 0, 0, 4, 1, 2, 3, 4, 0, 3, 3, 3, 2, 1, 1, 3, 4, 5, 2, 4, 5…
## $ Ne2     &lt;dbl&gt; 0, 6, 6, 4, 2, 1, 2, 3, 1, 2, 5, 5, 3, 1, 1, 1, 1, 6, 1, 2, 5…
## $ Op2     &lt;dbl&gt; 6, 0, 0, 4, 6, 4, 4, 0, 0, 3, 4, 3, 3, 4, 5, 3, 3, 4, 1, 6, 6…
## $ Ex1     &lt;dbl&gt; 3, 0, 0, 2, 2, 4, 4, 3, 5, 4, 1, 1, 3, 3, 1, 3, 5, 1, 0, 4, 1…
## $ Ex2     &lt;dbl&gt; 3, 0, 0, 3, 3, 4, 5, 2, 5, 3, 4, 1, 3, 2, 1, 6, 5, 3, 4, 4, 1…
## $ Co1     &lt;dbl&gt; 3, 0, 0, 3, 5, 4, 3, 4, 5, 3, 3, 3, 1, 5, 5, 4, 4, 5, 6, 4, 2…
## $ Co2     &lt;dbl&gt; 3, 0, 0, 3, 4, 3, 3, 4, 5, 3, 5, 3, 3, 4, 5, 1, 5, 4, 5, 2, 5…
## $ Ne3     &lt;dbl&gt; 0, 0, 0, 1, 0, 1, 4, 4, 0, 4, 2, 5, 1, 2, 5, 5, 2, 2, 1, 2, 5…
## $ Ag1     &lt;dbl&gt; 2, 0, 0, 4, 6, 5, 5, 4, 2, 5, 4, 3, 2, 4, 5, 3, 5, 5, 5, 4, 4…
## $ Ag2     &lt;dbl&gt; 1, 6, 6, 0, 5, 4, 5, 3, 4, 3, 5, 1, 5, 4, 2, 6, 5, 5, 5, 5, 2…
## $ Ne4     &lt;dbl&gt; 3, 6, 6, 2, 3, 2, 3, 3, 0, 4, 4, 5, 5, 4, 5, 3, 2, 5, 2, 4, 5…
## $ Ex3     &lt;dbl&gt; 3, 6, 5, 5, 3, 3, 3, 0, 6, 1, 4, 2, 3, 2, 1, 2, 5, 1, 0, 5, 5…
## $ Co3     &lt;dbl&gt; 2, 0, 1, 3, 4, 4, 5, 4, 5, 3, 4, 3, 4, 4, 5, 4, 2, 4, 5, 2, 2…
## $ Op3     &lt;dbl&gt; 2, 6, 5, 5, 5, 4, 3, 2, 4, 3, 3, 6, 5, 5, 6, 5, 4, 4, 3, 6, 5…
## $ Ex4     &lt;dbl&gt; 1, 0, 1, 3, 3, 3, 4, 3, 5, 3, 2, 0, 3, 3, 1, 2, NA, 4, 4, 4, …
## $ Op4     &lt;dbl&gt; 3, 0, 1, 6, 6, 3, 3, 0, 6, 3, 4, 5, 4, 5, 6, 6, 2, 2, 4, 5, 5…
## $ Ex5     &lt;dbl&gt; 3, 0, 1, 6, 3, 3, 4, 2, 5, 2, 2, 4, 2, 3, 0, 4, 5, 2, 3, 1, 1…
## $ Ag3     &lt;dbl&gt; 1, 0, 1, 1, 0, 4, 4, 4, 3, 3, 4, 4, 3, 4, 4, 5, 5, 4, 5, 3, 4…
## $ Co4     &lt;dbl&gt; 3, 6, 5, 5, 5, 3, 2, 4, 3, 1, 4, 3, 1, 2, 4, 2, NA, 5, 6, 1, …
## $ Co5     &lt;dbl&gt; 0, 6, 5, 5, 5, 3, 3, 1, 5, 1, 2, 4, 4, 4, 2, 1, 6, 4, 3, 1, 3…
## $ Ne5     &lt;dbl&gt; 3, 0, 1, 4, 1, 1, 4, 5, 0, 3, 4, 6, 2, 0, 1, 1, 0, 4, 3, 1, 5…
## $ Op5     &lt;dbl&gt; 6, 6, 5, 2, 5, 4, 3, 2, 6, 6, 2, 4, 3, 4, 6, 6, 6, 5, 3, 3, 5…
## $ Ag4     &lt;dbl&gt; 1, 0, 1, 4, 6, 5, 5, 6, 6, 6, 4, 2, 4, 5, 4, 5, 6, 4, 5, 6, 5…
## $ Op6     &lt;dbl&gt; 0, 6, 5, 1, 6, 4, 6, 0, 0, 3, 5, 3, 5, 5, 5, 2, 5, 1, 1, 6, 2…
## $ Co6     &lt;dbl&gt; 6, 0, 1, 4, 6, 5, 6, 5, 4, 3, 5, 5, 4, 6, 6, 1, 3, 4, 5, 4, 6…
## $ Ex6     &lt;dbl&gt; 3, 6, 5, 3, 0, 4, 3, 1, 6, 3, 2, 1, 4, 2, 1, 5, 6, 2, 1, 2, 1…
## $ Ne6     &lt;dbl&gt; 1, 6, 5, 1, 0, 1, 3, 4, 0, 4, 4, 5, 2, 1, 5, 6, 1, 2, 2, 3, 5…
## $ Co7     &lt;dbl&gt; 3, 6, 5, 1, 3, 4, NA, 2, 3, 3, 2, 2, 4, 2, 5, 2, 5, 5, 3, 1, …
## $ Ag5     &lt;dbl&gt; 3, 6, 5, 0, 2, 5, 6, 2, 2, 3, 4, 1, 3, 5, 2, 6, 5, 6, 5, 3, 3…
## $ Co8     &lt;dbl&gt; 3, 0, 1, 1, 3, 4, 3, 0, 1, 3, 2, 2, 1, 2, 4, 3, 2, 4, 5, 2, 6…
## $ Ex7     &lt;dbl&gt; 3, 6, 5, 4, 1, 2, 5, 3, 6, 3, 4, 3, 5, 1, 1, 6, 6, 3, 1, 1, 3…
## $ Ne7     &lt;dbl&gt; NA, 0, 1, 2, 0, 2, 4, 4, 0, 3, 2, 5, 1, 2, 5, 2, 2, 4, 1, 3, …
## $ Co9     &lt;dbl&gt; 3, 6, 5, 4, 3, 4, 5, 3, 5, 3, 4, 3, 4, 4, 2, 4, 6, 5, 5, 2, 2…
## $ Op7     &lt;dbl&gt; 0, 6, 5, 5, 5, 4, 6, 2, 1, 3, 2, 4, 5, 5, 6, 3, 6, 5, 2, 6, 5…
## $ Ne8     &lt;dbl&gt; 2, 0, 1, 1, 1, 1, 5, 4, 0, 4, 4, 5, 1, 2, 5, 2, 1, 5, 1, 2, 5…
## $ Ag6     &lt;dbl&gt; NA, 6, 5, 2, 3, 4, 5, 6, 1, 3, 4, 2, 3, 5, 1, 6, 2, 6, 6, 5, …
## $ Ag7     &lt;dbl&gt; 3, 0, 1, 1, 1, 3, 3, 5, 0, 3, 2, 1, 2, 3, 5, 6, 4, 4, 6, 6, 2…
## $ Co10    &lt;dbl&gt; 1, 6, 5, 5, 3, 5, 1, 2, 5, 2, 4, 3, 4, 4, 3, 2, 5, 5, 5, 2, 2…
## $ Ex8     &lt;dbl&gt; 2, 0, 1, 4, 3, 4, 2, 4, 6, 2, 4, 0, 4, 4, 1, 3, 5, 4, 3, 1, 1…
## $ Ex9     &lt;dbl&gt; 4, 6, 5, 5, 5, 2, 3, 3, 6, 3, 3, 4, 4, 3, 2, 5, 5, 4, 4, 0, 4…</code></pre>
</div>
</div>
<div id="tidy-verbs" class="section level2">
<h2><span class="header-section-number">4.6</span> Tidy Verbs</h2>
<p>The pivot functions above are relatively new functions that combine the four basic tidy verbs. You can also convert data between long and wide formats using these functions. Many researchers still use these functions and older code will not use the pivot functions, so it is useful to know how to interpret these.</p>
<div id="gather" class="section level3">
<h3><span class="header-section-number">4.6.1</span> gather()</h3>
<p>Much like <code>pivot_longer()</code>, <code>gather()</code> makes a wide data table long by creating a column for the headers and a column for the values. The main difference is that you cannot turn the headers into more than one column.</p>
<ul>
<li><code>key</code> is what you want to call the new column that the gathered column headers will go into; it’s “question” in this example. It is like <code>names_to</code> in <code>pivot_longer()</code>, but can only take one value (multiple values need to be separated after <code>separate()</code>).</li>
<li><code>value</code> is what you want to call the values in the gathered columns; they’re “score” in this example. It is like <code>values_to</code> in <code>pivot_longer()</code>.</li>
<li><code>...</code> refers to the columns you want to gather. It is like <code>cols</code> in <code>pivot_longer()</code>.</li>
</ul>
<p>The <code>gather()</code> function converts <code>personality</code> from a wide data table to long format, with a row for each user/question observation. The resulting data table should have the columns: <code>user_id</code>, <code>date</code>, <code>question</code>, and <code>score</code>.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="tidyr.html#cb187-1"></a>personality_gathered &lt;-<span class="st"> </span><span class="kw">gather</span>(</span>
<span id="cb187-2"><a href="tidyr.html#cb187-2"></a>  <span class="dt">data =</span> personality, </span>
<span id="cb187-3"><a href="tidyr.html#cb187-3"></a>  <span class="dt">key =</span> <span class="st">&quot;question&quot;</span>, <span class="co"># new column name for gathered headers</span></span>
<span id="cb187-4"><a href="tidyr.html#cb187-4"></a>  <span class="dt">value =</span> <span class="st">&quot;score&quot;</span>,  <span class="co"># new column name for gathered values</span></span>
<span id="cb187-5"><a href="tidyr.html#cb187-5"></a>  Op1<span class="op">:</span>Ex9           <span class="co"># columns to gather</span></span>
<span id="cb187-6"><a href="tidyr.html#cb187-6"></a>) <span class="op">%&gt;%</span></span>
<span id="cb187-7"><a href="tidyr.html#cb187-7"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 615,000
## Columns: 4
## $ user_id  &lt;dbl&gt; 0, 1, 2, 5, 8, 108, 233, 298, 426, 436, 685, 807, 871, 881, …
## $ date     &lt;date&gt; 2006-03-23, 2006-02-08, 2005-10-24, 2005-12-07, 2006-07-27,…
## $ question &lt;chr&gt; &quot;Op1&quot;, &quot;Op1&quot;, &quot;Op1&quot;, &quot;Op1&quot;, &quot;Op1&quot;, &quot;Op1&quot;, &quot;Op1&quot;, &quot;Op1&quot;, &quot;Op1…
## $ score    &lt;dbl&gt; 3, 6, 6, 6, 6, 3, 3, 6, 6, 3, 4, 5, 5, 5, 6, 4, 1, 2, 5, 6, …</code></pre>
</div>
<div id="separate" class="section level3">
<h3><span class="header-section-number">4.6.2</span> separate()</h3>
<ul>
<li><code>col</code> is the column you want to separate</li>
<li><code>into</code> is a vector of new column names</li>
<li><code>sep</code> is the character(s) that separate your new columns. This defaults to anything that isn’t alphanumeric, like .<code>,_-/:</code> and is like the <code>names_sep</code> argument in <code>pivot_longer()</code>.</li>
</ul>
<p>Split the <code>question</code> column into two columns: <code>domain</code> and <code>qnumber</code>.</p>
<p>There is no character to split on, here, but you can separate a column after a specific number of characters by setting <code>sep</code> to an integer. For example, to split “abcde” after the third character, use <code>sep = 3</code>, which results in <code>c("abc", "de")</code>. You can also use negative number to split before the <em>n</em>th character from the right. For example, to split a column that has words of various lengths and 2-digit suffixes (like “lisa03”“,”amanda38"), you can use <code>sep = -2</code>.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="tidyr.html#cb189-1"></a>personality_sep &lt;-<span class="st"> </span><span class="kw">separate</span>(</span>
<span id="cb189-2"><a href="tidyr.html#cb189-2"></a>  <span class="dt">data =</span> personality_gathered, </span>
<span id="cb189-3"><a href="tidyr.html#cb189-3"></a>  <span class="dt">col =</span> question,                <span class="co"># column to separate</span></span>
<span id="cb189-4"><a href="tidyr.html#cb189-4"></a>  <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;domain&quot;</span>, <span class="st">&quot;qnumber&quot;</span>), <span class="co"># new column names</span></span>
<span id="cb189-5"><a href="tidyr.html#cb189-5"></a>  <span class="dt">sep =</span> <span class="dv">2</span>                        <span class="co"># where to separate</span></span>
<span id="cb189-6"><a href="tidyr.html#cb189-6"></a>) <span class="op">%&gt;%</span></span>
<span id="cb189-7"><a href="tidyr.html#cb189-7"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 615,000
## Columns: 5
## $ user_id &lt;dbl&gt; 0, 1, 2, 5, 8, 108, 233, 298, 426, 436, 685, 807, 871, 881, 9…
## $ date    &lt;date&gt; 2006-03-23, 2006-02-08, 2005-10-24, 2005-12-07, 2006-07-27, …
## $ domain  &lt;chr&gt; &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;Op&quot;, &quot;…
## $ qnumber &lt;chr&gt; &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;…
## $ score   &lt;dbl&gt; 3, 6, 6, 6, 6, 3, 3, 6, 6, 3, 4, 5, 5, 5, 6, 4, 1, 2, 5, 6, 4…</code></pre>
<div class="warning">
<p>If you want to separate just at full stops, you need to use <code>sep = "\\."</code>, not <code>sep = "."</code>. The two slashes <strong>escape</strong> the full stop, making it interpreted as a literal full stop and not the regular expression for any character.</p>
</div>
</div>
<div id="unite" class="section level3">
<h3><span class="header-section-number">4.6.3</span> unite()</h3>
<ul>
<li><code>col</code> is your new united column</li>
<li><code>...</code> refers to the columns you want to unite</li>
<li><code>sep</code> is the character(s) that will separate your united columns</li>
</ul>
<p>Put the domain and qnumber columns back together into a new column named <code>domain_n</code>. Make it in a format like “Op_Q1”.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="tidyr.html#cb191-1"></a>personality_unite &lt;-<span class="st"> </span><span class="kw">unite</span>(</span>
<span id="cb191-2"><a href="tidyr.html#cb191-2"></a>  <span class="dt">data =</span> personality_sep, </span>
<span id="cb191-3"><a href="tidyr.html#cb191-3"></a>  <span class="dt">col =</span> <span class="st">&quot;domain_n&quot;</span>, <span class="co"># new column name</span></span>
<span id="cb191-4"><a href="tidyr.html#cb191-4"></a>  domain, qnumber,  <span class="co"># columns to unite</span></span>
<span id="cb191-5"><a href="tidyr.html#cb191-5"></a>  <span class="dt">sep =</span> <span class="st">&quot;_Q&quot;</span>        <span class="co"># separation characters</span></span>
<span id="cb191-6"><a href="tidyr.html#cb191-6"></a>) <span class="op">%&gt;%</span></span>
<span id="cb191-7"><a href="tidyr.html#cb191-7"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 615,000
## Columns: 4
## $ user_id  &lt;dbl&gt; 0, 1, 2, 5, 8, 108, 233, 298, 426, 436, 685, 807, 871, 881, …
## $ date     &lt;date&gt; 2006-03-23, 2006-02-08, 2005-10-24, 2005-12-07, 2006-07-27,…
## $ domain_n &lt;chr&gt; &quot;Op_Q1&quot;, &quot;Op_Q1&quot;, &quot;Op_Q1&quot;, &quot;Op_Q1&quot;, &quot;Op_Q1&quot;, &quot;Op_Q1&quot;, &quot;Op_Q1…
## $ score    &lt;dbl&gt; 3, 6, 6, 6, 6, 3, 3, 6, 6, 3, 4, 5, 5, 5, 6, 4, 1, 2, 5, 6, …</code></pre>
</div>
<div id="spread" class="section level3">
<h3><span class="header-section-number">4.6.4</span> spread()</h3>
<p>You can reverse the processes above, as well. For example, you can convert data from long format into wide format.</p>
<ul>
<li><code>key</code> is the column that contains your new column headers. It is like <code>names_from</code> in <code>pivot_wider()</code>, but can only take one value (multiple values need to be merged first using <code>unite()</code>).</li>
<li><code>value</code> is the column that contains the values in the new spread columns. It is like <code>values_from</code> in <code>pivot_wider()</code>.</li>
</ul>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="tidyr.html#cb193-1"></a>personality_spread &lt;-<span class="st"> </span><span class="kw">spread</span>(</span>
<span id="cb193-2"><a href="tidyr.html#cb193-2"></a>  <span class="dt">data =</span> personality_unite,</span>
<span id="cb193-3"><a href="tidyr.html#cb193-3"></a>  <span class="dt">key =</span> domain_n, <span class="co"># column that contains new headers</span></span>
<span id="cb193-4"><a href="tidyr.html#cb193-4"></a>  <span class="dt">value =</span> score   <span class="co"># column that contains new values</span></span>
<span id="cb193-5"><a href="tidyr.html#cb193-5"></a>) <span class="op">%&gt;%</span></span>
<span id="cb193-6"><a href="tidyr.html#cb193-6"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 15,000
## Columns: 43
## $ user_id &lt;dbl&gt; 0, 1, 2, 5, 8, 108, 233, 298, 426, 436, 685, 807, 871, 881, 9…
## $ date    &lt;date&gt; 2006-03-23, 2006-02-08, 2005-10-24, 2005-12-07, 2006-07-27, …
## $ Ag_Q1   &lt;dbl&gt; 2, 0, 0, 4, 6, 5, 5, 4, 2, 5, 4, 3, 2, 4, 5, 3, 5, 5, 5, 4, 4…
## $ Ag_Q2   &lt;dbl&gt; 1, 6, 6, 0, 5, 4, 5, 3, 4, 3, 5, 1, 5, 4, 2, 6, 5, 5, 5, 5, 2…
## $ Ag_Q3   &lt;dbl&gt; 1, 0, 1, 1, 0, 4, 4, 4, 3, 3, 4, 4, 3, 4, 4, 5, 5, 4, 5, 3, 4…
## $ Ag_Q4   &lt;dbl&gt; 1, 0, 1, 4, 6, 5, 5, 6, 6, 6, 4, 2, 4, 5, 4, 5, 6, 4, 5, 6, 5…
## $ Ag_Q5   &lt;dbl&gt; 3, 6, 5, 0, 2, 5, 6, 2, 2, 3, 4, 1, 3, 5, 2, 6, 5, 6, 5, 3, 3…
## $ Ag_Q6   &lt;dbl&gt; NA, 6, 5, 2, 3, 4, 5, 6, 1, 3, 4, 2, 3, 5, 1, 6, 2, 6, 6, 5, …
## $ Ag_Q7   &lt;dbl&gt; 3, 0, 1, 1, 1, 3, 3, 5, 0, 3, 2, 1, 2, 3, 5, 6, 4, 4, 6, 6, 2…
## $ Co_Q1   &lt;dbl&gt; 3, 0, 0, 3, 5, 4, 3, 4, 5, 3, 3, 3, 1, 5, 5, 4, 4, 5, 6, 4, 2…
## $ Co_Q10  &lt;dbl&gt; 1, 6, 5, 5, 3, 5, 1, 2, 5, 2, 4, 3, 4, 4, 3, 2, 5, 5, 5, 2, 2…
## $ Co_Q2   &lt;dbl&gt; 3, 0, 0, 3, 4, 3, 3, 4, 5, 3, 5, 3, 3, 4, 5, 1, 5, 4, 5, 2, 5…
## $ Co_Q3   &lt;dbl&gt; 2, 0, 1, 3, 4, 4, 5, 4, 5, 3, 4, 3, 4, 4, 5, 4, 2, 4, 5, 2, 2…
## $ Co_Q4   &lt;dbl&gt; 3, 6, 5, 5, 5, 3, 2, 4, 3, 1, 4, 3, 1, 2, 4, 2, NA, 5, 6, 1, …
## $ Co_Q5   &lt;dbl&gt; 0, 6, 5, 5, 5, 3, 3, 1, 5, 1, 2, 4, 4, 4, 2, 1, 6, 4, 3, 1, 3…
## $ Co_Q6   &lt;dbl&gt; 6, 0, 1, 4, 6, 5, 6, 5, 4, 3, 5, 5, 4, 6, 6, 1, 3, 4, 5, 4, 6…
## $ Co_Q7   &lt;dbl&gt; 3, 6, 5, 1, 3, 4, NA, 2, 3, 3, 2, 2, 4, 2, 5, 2, 5, 5, 3, 1, …
## $ Co_Q8   &lt;dbl&gt; 3, 0, 1, 1, 3, 4, 3, 0, 1, 3, 2, 2, 1, 2, 4, 3, 2, 4, 5, 2, 6…
## $ Co_Q9   &lt;dbl&gt; 3, 6, 5, 4, 3, 4, 5, 3, 5, 3, 4, 3, 4, 4, 2, 4, 6, 5, 5, 2, 2…
## $ Ex_Q1   &lt;dbl&gt; 3, 0, 0, 2, 2, 4, 4, 3, 5, 4, 1, 1, 3, 3, 1, 3, 5, 1, 0, 4, 1…
## $ Ex_Q2   &lt;dbl&gt; 3, 0, 0, 3, 3, 4, 5, 2, 5, 3, 4, 1, 3, 2, 1, 6, 5, 3, 4, 4, 1…
## $ Ex_Q3   &lt;dbl&gt; 3, 6, 5, 5, 3, 3, 3, 0, 6, 1, 4, 2, 3, 2, 1, 2, 5, 1, 0, 5, 5…
## $ Ex_Q4   &lt;dbl&gt; 1, 0, 1, 3, 3, 3, 4, 3, 5, 3, 2, 0, 3, 3, 1, 2, NA, 4, 4, 4, …
## $ Ex_Q5   &lt;dbl&gt; 3, 0, 1, 6, 3, 3, 4, 2, 5, 2, 2, 4, 2, 3, 0, 4, 5, 2, 3, 1, 1…
## $ Ex_Q6   &lt;dbl&gt; 3, 6, 5, 3, 0, 4, 3, 1, 6, 3, 2, 1, 4, 2, 1, 5, 6, 2, 1, 2, 1…
## $ Ex_Q7   &lt;dbl&gt; 3, 6, 5, 4, 1, 2, 5, 3, 6, 3, 4, 3, 5, 1, 1, 6, 6, 3, 1, 1, 3…
## $ Ex_Q8   &lt;dbl&gt; 2, 0, 1, 4, 3, 4, 2, 4, 6, 2, 4, 0, 4, 4, 1, 3, 5, 4, 3, 1, 1…
## $ Ex_Q9   &lt;dbl&gt; 4, 6, 5, 5, 5, 2, 3, 3, 6, 3, 3, 4, 4, 3, 2, 5, 5, 4, 4, 0, 4…
## $ Ne_Q1   &lt;dbl&gt; 4, 0, 0, 4, 1, 2, 3, 4, 0, 3, 3, 3, 2, 1, 1, 3, 4, 5, 2, 4, 5…
## $ Ne_Q2   &lt;dbl&gt; 0, 6, 6, 4, 2, 1, 2, 3, 1, 2, 5, 5, 3, 1, 1, 1, 1, 6, 1, 2, 5…
## $ Ne_Q3   &lt;dbl&gt; 0, 0, 0, 1, 0, 1, 4, 4, 0, 4, 2, 5, 1, 2, 5, 5, 2, 2, 1, 2, 5…
## $ Ne_Q4   &lt;dbl&gt; 3, 6, 6, 2, 3, 2, 3, 3, 0, 4, 4, 5, 5, 4, 5, 3, 2, 5, 2, 4, 5…
## $ Ne_Q5   &lt;dbl&gt; 3, 0, 1, 4, 1, 1, 4, 5, 0, 3, 4, 6, 2, 0, 1, 1, 0, 4, 3, 1, 5…
## $ Ne_Q6   &lt;dbl&gt; 1, 6, 5, 1, 0, 1, 3, 4, 0, 4, 4, 5, 2, 1, 5, 6, 1, 2, 2, 3, 5…
## $ Ne_Q7   &lt;dbl&gt; NA, 0, 1, 2, 0, 2, 4, 4, 0, 3, 2, 5, 1, 2, 5, 2, 2, 4, 1, 3, …
## $ Ne_Q8   &lt;dbl&gt; 2, 0, 1, 1, 1, 1, 5, 4, 0, 4, 4, 5, 1, 2, 5, 2, 1, 5, 1, 2, 5…
## $ Op_Q1   &lt;dbl&gt; 3, 6, 6, 6, 6, 3, 3, 6, 6, 3, 4, 5, 5, 5, 6, 4, 1, 2, 5, 6, 4…
## $ Op_Q2   &lt;dbl&gt; 6, 0, 0, 4, 6, 4, 4, 0, 0, 3, 4, 3, 3, 4, 5, 3, 3, 4, 1, 6, 6…
## $ Op_Q3   &lt;dbl&gt; 2, 6, 5, 5, 5, 4, 3, 2, 4, 3, 3, 6, 5, 5, 6, 5, 4, 4, 3, 6, 5…
## $ Op_Q4   &lt;dbl&gt; 3, 0, 1, 6, 6, 3, 3, 0, 6, 3, 4, 5, 4, 5, 6, 6, 2, 2, 4, 5, 5…
## $ Op_Q5   &lt;dbl&gt; 6, 6, 5, 2, 5, 4, 3, 2, 6, 6, 2, 4, 3, 4, 6, 6, 6, 5, 3, 3, 5…
## $ Op_Q6   &lt;dbl&gt; 0, 6, 5, 1, 6, 4, 6, 0, 0, 3, 5, 3, 5, 5, 5, 2, 5, 1, 1, 6, 2…
## $ Op_Q7   &lt;dbl&gt; 0, 6, 5, 5, 5, 4, 6, 2, 1, 3, 2, 4, 5, 5, 6, 3, 6, 5, 2, 6, 5…</code></pre>
</div>
</div>
<div id="pipes" class="section level2">
<h2><span class="header-section-number">4.7</span> Pipes</h2>
<p><img src="images/04/pipe_sticker.png" style="width: 200px; float: right;"></p>
<p>Pipes are a way to order your code in a more readable format.</p>
<p>Let’s say you have a small data table with 10 participant IDs, two columns with variable type A, and 2 columns with variable type B. You want to calculate the mean of the A variables and the mean of the B variables and return a table with 10 rows (1 for each participant) and 3 columns (<code>id</code>, <code>A_mean</code> and <code>B_mean</code>).</p>
<p>One way you could do this is by creating a new object at every step and using that object in the next step. This is pretty clear, but you’ve created 6 unnecessary data objects in your environment. This can get confusing in very long scripts.</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="tidyr.html#cb195-1"></a><span class="co"># make a data table with 10 subjects</span></span>
<span id="cb195-2"><a href="tidyr.html#cb195-2"></a>data_original &lt;-<span class="st"> </span><span class="kw">tibble</span>(</span>
<span id="cb195-3"><a href="tidyr.html#cb195-3"></a>  <span class="dt">id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,</span>
<span id="cb195-4"><a href="tidyr.html#cb195-4"></a>  <span class="dt">A1 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">0</span>),</span>
<span id="cb195-5"><a href="tidyr.html#cb195-5"></a>  <span class="dt">A2 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">1</span>),</span>
<span id="cb195-6"><a href="tidyr.html#cb195-6"></a>  <span class="dt">B1 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">2</span>),</span>
<span id="cb195-7"><a href="tidyr.html#cb195-7"></a>  <span class="dt">B2 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">3</span>)</span>
<span id="cb195-8"><a href="tidyr.html#cb195-8"></a>)</span>
<span id="cb195-9"><a href="tidyr.html#cb195-9"></a></span>
<span id="cb195-10"><a href="tidyr.html#cb195-10"></a><span class="co"># gather columns A1 to B2 into &quot;variable&quot; and &quot;value&quot; columns</span></span>
<span id="cb195-11"><a href="tidyr.html#cb195-11"></a>data_gathered &lt;-<span class="st"> </span><span class="kw">gather</span>(data_original, variable, value, A1<span class="op">:</span>B2)</span>
<span id="cb195-12"><a href="tidyr.html#cb195-12"></a></span>
<span id="cb195-13"><a href="tidyr.html#cb195-13"></a><span class="co"># separate the variable column at the _ into &quot;var&quot; and &quot;var_n&quot; columns</span></span>
<span id="cb195-14"><a href="tidyr.html#cb195-14"></a>data_separated &lt;-<span class="st"> </span><span class="kw">separate</span>(data_gathered, variable, <span class="kw">c</span>(<span class="st">&quot;var&quot;</span>, <span class="st">&quot;var_n&quot;</span>), <span class="dt">sep =</span> <span class="dv">1</span>)</span>
<span id="cb195-15"><a href="tidyr.html#cb195-15"></a></span>
<span id="cb195-16"><a href="tidyr.html#cb195-16"></a><span class="co"># group the data by id and var</span></span>
<span id="cb195-17"><a href="tidyr.html#cb195-17"></a>data_grouped &lt;-<span class="st"> </span><span class="kw">group_by</span>(data_separated, id, var)</span>
<span id="cb195-18"><a href="tidyr.html#cb195-18"></a></span>
<span id="cb195-19"><a href="tidyr.html#cb195-19"></a><span class="co"># calculate the mean value for each id/var </span></span>
<span id="cb195-20"><a href="tidyr.html#cb195-20"></a>data_summarised &lt;-<span class="st"> </span><span class="kw">summarise</span>(data_grouped, <span class="dt">mean =</span> <span class="kw">mean</span>(value), <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span>
<span id="cb195-21"><a href="tidyr.html#cb195-21"></a></span>
<span id="cb195-22"><a href="tidyr.html#cb195-22"></a><span class="co"># spread the mean column into A and B columns</span></span>
<span id="cb195-23"><a href="tidyr.html#cb195-23"></a>data_spread &lt;-<span class="st"> </span><span class="kw">spread</span>(data_summarised, var, mean)</span>
<span id="cb195-24"><a href="tidyr.html#cb195-24"></a></span>
<span id="cb195-25"><a href="tidyr.html#cb195-25"></a><span class="co"># rename A and B to A_mean and B_mean</span></span>
<span id="cb195-26"><a href="tidyr.html#cb195-26"></a>data &lt;-<span class="st"> </span><span class="kw">rename</span>(data_spread, <span class="dt">A_mean =</span> A, <span class="dt">B_mean =</span> B)</span>
<span id="cb195-27"><a href="tidyr.html#cb195-27"></a></span>
<span id="cb195-28"><a href="tidyr.html#cb195-28"></a>data</span></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##       id  A_mean B_mean
##    &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1     1 -0.594   1.02 
##  2     2  0.744   2.72 
##  3     3  0.931   3.93 
##  4     4  0.720   1.97 
##  5     5 -0.0281  1.95 
##  6     6 -0.0983  3.21 
##  7     7  0.126   0.926
##  8     8  1.45    2.38 
##  9     9  0.298   1.66 
## 10    10  0.559   2.10</code></pre>
<div class="warning">
<p>
You <em>can</em> name each object <code>data</code> and keep replacing the old data object with the new one at each step. This will keep your environment clean, but I don’t recommend it because it makes it too easy to accidentally run your code out of order when you are running line-by-line for development or debugging.
</p>
</div>
<p>One way to avoid extra objects is to nest your functions, literally replacing each data object with the code that generated it in the previous step. This can be fine for very short chains.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="tidyr.html#cb197-1"></a>mean_petal_width &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">mean</span>(iris<span class="op">$</span>Petal.Width), <span class="dv">2</span>)</span></code></pre></div>
<p>But it gets extremely confusing for long chains:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="tidyr.html#cb198-1"></a><span class="co"># do not ever do this!!</span></span>
<span id="cb198-2"><a href="tidyr.html#cb198-2"></a>data &lt;-<span class="st"> </span><span class="kw">rename</span>(</span>
<span id="cb198-3"><a href="tidyr.html#cb198-3"></a>  <span class="kw">spread</span>(</span>
<span id="cb198-4"><a href="tidyr.html#cb198-4"></a>    <span class="kw">summarise</span>(</span>
<span id="cb198-5"><a href="tidyr.html#cb198-5"></a>      <span class="kw">group_by</span>(</span>
<span id="cb198-6"><a href="tidyr.html#cb198-6"></a>        <span class="kw">separate</span>(</span>
<span id="cb198-7"><a href="tidyr.html#cb198-7"></a>          <span class="kw">gather</span>(</span>
<span id="cb198-8"><a href="tidyr.html#cb198-8"></a>            <span class="kw">tibble</span>(</span>
<span id="cb198-9"><a href="tidyr.html#cb198-9"></a>              <span class="dt">id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,</span>
<span id="cb198-10"><a href="tidyr.html#cb198-10"></a>              <span class="dt">A1 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">0</span>),</span>
<span id="cb198-11"><a href="tidyr.html#cb198-11"></a>              <span class="dt">A2 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">1</span>),</span>
<span id="cb198-12"><a href="tidyr.html#cb198-12"></a>              <span class="dt">B1 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">2</span>),</span>
<span id="cb198-13"><a href="tidyr.html#cb198-13"></a>              <span class="dt">B2 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">3</span>)), </span>
<span id="cb198-14"><a href="tidyr.html#cb198-14"></a>            variable, value, A1<span class="op">:</span>B2), </span>
<span id="cb198-15"><a href="tidyr.html#cb198-15"></a>          variable, <span class="kw">c</span>(<span class="st">&quot;var&quot;</span>, <span class="st">&quot;var_n&quot;</span>), <span class="dt">sep =</span> <span class="dv">1</span>), </span>
<span id="cb198-16"><a href="tidyr.html#cb198-16"></a>        id, var), </span>
<span id="cb198-17"><a href="tidyr.html#cb198-17"></a>      <span class="dt">mean =</span> <span class="kw">mean</span>(value), <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>), </span>
<span id="cb198-18"><a href="tidyr.html#cb198-18"></a>    var, mean), </span>
<span id="cb198-19"><a href="tidyr.html#cb198-19"></a>  <span class="dt">A_mean =</span> A, <span class="dt">B_mean =</span> B)</span></code></pre></div>
<p>The pipe lets you “pipe” the result of each function into the next function, allowing you to put your code in a logical order without creating too many extra objects.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="tidyr.html#cb199-1"></a><span class="co"># calculate mean of A and B variables for each participant</span></span>
<span id="cb199-2"><a href="tidyr.html#cb199-2"></a>data &lt;-<span class="st"> </span><span class="kw">tibble</span>(</span>
<span id="cb199-3"><a href="tidyr.html#cb199-3"></a>  <span class="dt">id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,</span>
<span id="cb199-4"><a href="tidyr.html#cb199-4"></a>  <span class="dt">A1 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">0</span>),</span>
<span id="cb199-5"><a href="tidyr.html#cb199-5"></a>  <span class="dt">A2 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">1</span>),</span>
<span id="cb199-6"><a href="tidyr.html#cb199-6"></a>  <span class="dt">B1 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">2</span>),</span>
<span id="cb199-7"><a href="tidyr.html#cb199-7"></a>  <span class="dt">B2 =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">3</span>)</span>
<span id="cb199-8"><a href="tidyr.html#cb199-8"></a>) <span class="op">%&gt;%</span></span>
<span id="cb199-9"><a href="tidyr.html#cb199-9"></a><span class="st">  </span><span class="kw">gather</span>(variable, value, A1<span class="op">:</span>B2) <span class="op">%&gt;%</span></span>
<span id="cb199-10"><a href="tidyr.html#cb199-10"></a><span class="st">  </span><span class="kw">separate</span>(variable, <span class="kw">c</span>(<span class="st">&quot;var&quot;</span>, <span class="st">&quot;var_n&quot;</span>), <span class="dt">sep=</span><span class="dv">1</span>) <span class="op">%&gt;%</span></span>
<span id="cb199-11"><a href="tidyr.html#cb199-11"></a><span class="st">  </span><span class="kw">group_by</span>(id, var) <span class="op">%&gt;%</span></span>
<span id="cb199-12"><a href="tidyr.html#cb199-12"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(value), <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb199-13"><a href="tidyr.html#cb199-13"></a><span class="st">  </span><span class="kw">spread</span>(var, mean) <span class="op">%&gt;%</span></span>
<span id="cb199-14"><a href="tidyr.html#cb199-14"></a><span class="st">  </span><span class="kw">rename</span>(<span class="dt">A_mean =</span> A, <span class="dt">B_mean =</span> B)</span></code></pre></div>
<p>You can read this code from top to bottom as follows:</p>
<ol style="list-style-type: decimal">
<li>Make a tibble called <code>data</code> with
<ul>
<li>id of 1 to 10,</li>
<li>A1 of 10 random numbers from a normal distribution,</li>
<li>A2 of 10 random numbers from a normal distribution,</li>
<li>B1 of 10 random numbers from a normal distribution,</li>
<li>B2 of 10 random numbers from a normal distribution; and then</li>
</ul></li>
<li>Gather to create <code>variable</code> and <code>value</code> column from columns <code>A_1</code> to <code>B_2</code>; and then</li>
<li>Separate the column <code>variable</code> into 2 new columns called <code>var</code>and <code>var_n</code>, separate at character 1; and then</li>
<li>Group by columns <code>id</code> and <code>var</code>; and then</li>
<li>Summarise and new column called <code>mean</code> as the mean of the <code>value</code> column for each group and drop the grouping; and then</li>
<li>Spread to make new columns with the key names in <code>var</code> and values in <code>mean</code>; and then</li>
<li>Rename to make columns called <code>A_mean</code> (old <code>A</code>) and <code>B_mean</code> (old <code>B</code>)</li>
</ol>
<p>You can make intermediate objects whenever you need to break up your code because it’s getting too complicated or you need to debug something.</p>
<div class="info">
<p>
You can debug a pipe by highlighting from the beginning to just before the pipe you want to stop at. Try this by highlighting from <code>data &lt;-</code> to the end of the <code>separate</code> function and typing cmd-return. What does <code>data</code> look like now?
</p>
</div>
<p>Chain all the steps above using pipes.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="tidyr.html#cb200-1"></a>personality_reshaped &lt;-<span class="st"> </span>personality <span class="op">%&gt;%</span></span>
<span id="cb200-2"><a href="tidyr.html#cb200-2"></a><span class="st">  </span><span class="kw">gather</span>(<span class="st">&quot;question&quot;</span>, <span class="st">&quot;score&quot;</span>, Op1<span class="op">:</span>Ex9) <span class="op">%&gt;%</span></span>
<span id="cb200-3"><a href="tidyr.html#cb200-3"></a><span class="st">  </span><span class="kw">separate</span>(question, <span class="kw">c</span>(<span class="st">&quot;domain&quot;</span>, <span class="st">&quot;qnumber&quot;</span>), <span class="dt">sep =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span></span>
<span id="cb200-4"><a href="tidyr.html#cb200-4"></a><span class="st">  </span><span class="kw">unite</span>(<span class="st">&quot;domain_n&quot;</span>, domain, qnumber, <span class="dt">sep =</span> <span class="st">&quot;_Q&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb200-5"><a href="tidyr.html#cb200-5"></a><span class="st">  </span><span class="kw">spread</span>(domain_n, score)</span></code></pre></div>
</div>
<div id="more-complex-example" class="section level2">
<h2><span class="header-section-number">4.8</span> More Complex Example</h2>
<div id="load-data-1" class="section level3">
<h3><span class="header-section-number">4.8.1</span> Load Data</h3>
<p>Get data on infant and maternal mortality rates from the dataskills package. If you don’t have the package, you can download them here:</p>
<ul>
<li><a href="https://psyteachr.github.io/msc-data-skills/data/infmort.csv">infant mortality</a><br />
</li>
<li><a href="https://psyteachr.github.io/msc-data-skills/data/matmort.xls">maternal mortality</a></li>
</ul>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="tidyr.html#cb201-1"></a><span class="kw">data</span>(<span class="st">&quot;infmort&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;dataskills&quot;</span>)</span>
<span id="cb201-2"><a href="tidyr.html#cb201-2"></a><span class="kw">head</span>(infmort)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   Country     Year `Infant mortality rate (probability of dying between birth a…
##   &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;                                                        
## 1 Afghanist…  2015 66.3 [52.7-83.9]                                             
## 2 Afghanist…  2014 68.1 [55.7-83.6]                                             
## 3 Afghanist…  2013 69.9 [58.7-83.5]                                             
## 4 Afghanist…  2012 71.7 [61.6-83.7]                                             
## 5 Afghanist…  2011 73.4 [64.4-84.2]                                             
## 6 Afghanist…  2010 75.1 [66.9-85.1]</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="tidyr.html#cb203-1"></a><span class="kw">data</span>(<span class="st">&quot;matmort&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;dataskills&quot;</span>)</span>
<span id="cb203-2"><a href="tidyr.html#cb203-2"></a><span class="kw">head</span>(matmort)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   Country     `1990`               `2000`               `2015`           
##   &lt;chr&gt;       &lt;chr&gt;                &lt;chr&gt;                &lt;chr&gt;            
## 1 Afghanistan 1 340 [ 878 - 1 950] 1 100 [ 745 - 1 570] 396 [ 253 -  620]
## 2 Albania     71 [ 58 -  88]       43 [ 33 -  56]       29 [ 16 -  46]   
## 3 Algeria     216 [ 141 -  327]    170 [ 118 -  241]    140 [ 82 -  244] 
## 4 Angola      1 160 [ 627 - 2 020] 924 [ 472 - 1 730]   477 [ 221 -  988]
## 5 Argentina   72 [ 64 -  80]       60 [ 54 -  65]       52 [ 44 -  63]   
## 6 Armenia     58 [ 51 -  65]       40 [ 35 -  46]       25 [ 21 -  31]</code></pre>
</div>
<div id="wide-to-long" class="section level3">
<h3><span class="header-section-number">4.8.2</span> Wide to Long</h3>
<p><code>matmort</code> is in wide format, with a separate column for each year. Change it to long format, with a row for each Country/Year observation.</p>
<p>This example is complicated because the column names to gather <em>are</em> numbers. If the column names are non-standard (e.g., have spaces, start with numbers, or have special characters), you can enclose them in backticks (`) like the example below.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="tidyr.html#cb205-1"></a>matmort_long &lt;-<span class="st"> </span>matmort <span class="op">%&gt;%</span></span>
<span id="cb205-2"><a href="tidyr.html#cb205-2"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="st">`</span><span class="dt">1990</span><span class="st">`</span><span class="op">:</span><span class="st">`</span><span class="dt">2015</span><span class="st">`</span>,</span>
<span id="cb205-3"><a href="tidyr.html#cb205-3"></a>               <span class="dt">names_to =</span> <span class="st">&quot;Year&quot;</span>,</span>
<span id="cb205-4"><a href="tidyr.html#cb205-4"></a>               <span class="dt">values_to =</span> <span class="st">&quot;stats&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb205-5"><a href="tidyr.html#cb205-5"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 543
## Columns: 3
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Alba…
## $ Year    &lt;chr&gt; &quot;1990&quot;, &quot;2000&quot;, &quot;2015&quot;, &quot;1990&quot;, &quot;2000&quot;, &quot;2015&quot;, &quot;1990&quot;, &quot;2000…
## $ stats   &lt;chr&gt; &quot;1 340 [ 878 - 1 950]&quot;, &quot;1 100 [ 745 - 1 570]&quot;, &quot;396 [ 253 - …</code></pre>
<div class="info">
<p>
You can put <code>matmort</code> at the first argument to <code>pivot_longer()</code>; you don’t have to pipe it in. But when I’m working on data processing I often find myself needing to insert or rearrange steps and I constantly introduce errors by forgetting to take the first argument out of a pipe chain, so now I start with the original data table and pipe from there.
</p>
</div>
<p>Alternatively, you can use the <code>gather()</code> function.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="tidyr.html#cb207-1"></a>matmort_long &lt;-<span class="st"> </span>matmort <span class="op">%&gt;%</span></span>
<span id="cb207-2"><a href="tidyr.html#cb207-2"></a><span class="st">  </span><span class="kw">gather</span>(<span class="st">&quot;Year&quot;</span>, <span class="st">&quot;stats&quot;</span>, <span class="st">`</span><span class="dt">1990</span><span class="st">`</span><span class="op">:</span><span class="st">`</span><span class="dt">2015</span><span class="st">`</span>) <span class="op">%&gt;%</span></span>
<span id="cb207-3"><a href="tidyr.html#cb207-3"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 543
## Columns: 3
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;Angola&quot;, &quot;Argentina&quot;, &quot;…
## $ Year    &lt;chr&gt; &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990…
## $ stats   &lt;chr&gt; &quot;1 340 [ 878 - 1 950]&quot;, &quot;71 [ 58 -  88]&quot;, &quot;216 [ 141 -  327]&quot;…</code></pre>
</div>
<div id="one-piece-of-data-per-column" class="section level3">
<h3><span class="header-section-number">4.8.3</span> One Piece of Data per Column</h3>
<p>The data in the <code>stats</code> column is in an unusual format with some sort of confidence interval in brackets and lots of extra spaces. We don’t need any of the spaces, so first we’ll remove them with <code>mutate()</code>, which we’ll learn more about in the next lesson.</p>
<p>The <code>separate</code> function will separate your data on anything that is not a number or letter, so try it first without specifying the <code>sep</code> argument. The <code>into</code> argument is a list of the new column names.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="tidyr.html#cb209-1"></a>matmort_split &lt;-<span class="st"> </span>matmort_long <span class="op">%&gt;%</span></span>
<span id="cb209-2"><a href="tidyr.html#cb209-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">stats =</span> <span class="kw">gsub</span>(<span class="st">&quot; &quot;</span>, <span class="st">&quot;&quot;</span>, stats)) <span class="op">%&gt;%</span></span>
<span id="cb209-3"><a href="tidyr.html#cb209-3"></a><span class="st">  </span><span class="kw">separate</span>(stats, <span class="kw">c</span>(<span class="st">&quot;rate&quot;</span>, <span class="st">&quot;ci_low&quot;</span>, <span class="st">&quot;ci_hi&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb209-4"><a href="tidyr.html#cb209-4"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Warning: Expected 3 pieces. Additional pieces discarded in 543 rows [1, 2, 3, 4,
## 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].</code></pre>
<pre><code>## Rows: 543
## Columns: 5
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;Angola&quot;, &quot;Argentina&quot;, &quot;…
## $ Year    &lt;chr&gt; &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990…
## $ rate    &lt;chr&gt; &quot;1340&quot;, &quot;71&quot;, &quot;216&quot;, &quot;1160&quot;, &quot;72&quot;, &quot;58&quot;, &quot;8&quot;, &quot;8&quot;, &quot;64&quot;, &quot;46&quot;…
## $ ci_low  &lt;chr&gt; &quot;878&quot;, &quot;58&quot;, &quot;141&quot;, &quot;627&quot;, &quot;64&quot;, &quot;51&quot;, &quot;7&quot;, &quot;7&quot;, &quot;56&quot;, &quot;34&quot;, …
## $ ci_hi   &lt;chr&gt; &quot;1950&quot;, &quot;88&quot;, &quot;327&quot;, &quot;2020&quot;, &quot;80&quot;, &quot;65&quot;, &quot;9&quot;, &quot;10&quot;, &quot;74&quot;, &quot;61…</code></pre>
<div class="info">
<p>
The <code>gsub(pattern, replacement, x)</code> function is a flexible way to do search and replace. The example above replaces all occurances of the <code>pattern</code> " " (a space), with the <code>replacement</code> "" (nothing), in the string <code>x</code> (the <code>stats</code> column). Use <code>sub()</code> instead if you only want to replace the first occurance of a pattern. We only used a simple pattern here, but you can use more complicated <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/regex.html">regex</a> patterns to replace, for example, all even numbers (e.g., <code>gsub(“[:02468:]”, "<em>“,”id = 123456“)</code>) or all occurances of the word colour in US or UK spelling (e.g., <code>gsub(”colo(u)?r“,”</em>**“,”replace color, colour, or colours, but not collors")</code>).
</p>
</div>
<div id="extra" class="section level4">
<h4><span class="header-section-number">4.8.3.1</span> Handle spare columns with <code>extra</code></h4>
<div class="warning">
<p>
The previous example should have given you an error warning about “Additional pieces discarded in 543 rows”. This is because <code>separate</code> splits the column at the brackets and dashes, so the text <code>100[90-110]</code> would split into four values <code>c(“100”, “90”, “110”, "“)</code>, but we only specified 3 new columns. The fourth value is always empty (just the part after the last bracket), so we are happy to drop it, but <code>separate</code> generates a warning so you don’t do that accidentally. You can turn off the warning by adding the <code>extra</code> argument and setting it to “drop”. Look at the help for <code>??tidyr::separate</code> to see what the other options do.
</p>
</div>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="tidyr.html#cb212-1"></a>matmort_split &lt;-<span class="st"> </span>matmort_long <span class="op">%&gt;%</span></span>
<span id="cb212-2"><a href="tidyr.html#cb212-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">stats =</span> <span class="kw">gsub</span>(<span class="st">&quot; &quot;</span>, <span class="st">&quot;&quot;</span>, stats)) <span class="op">%&gt;%</span></span>
<span id="cb212-3"><a href="tidyr.html#cb212-3"></a><span class="st">  </span><span class="kw">separate</span>(stats, <span class="kw">c</span>(<span class="st">&quot;rate&quot;</span>, <span class="st">&quot;ci_low&quot;</span>, <span class="st">&quot;ci_hi&quot;</span>), <span class="dt">extra =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb212-4"><a href="tidyr.html#cb212-4"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 543
## Columns: 5
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;Angola&quot;, &quot;Argentina&quot;, &quot;…
## $ Year    &lt;chr&gt; &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990…
## $ rate    &lt;chr&gt; &quot;1340&quot;, &quot;71&quot;, &quot;216&quot;, &quot;1160&quot;, &quot;72&quot;, &quot;58&quot;, &quot;8&quot;, &quot;8&quot;, &quot;64&quot;, &quot;46&quot;…
## $ ci_low  &lt;chr&gt; &quot;878&quot;, &quot;58&quot;, &quot;141&quot;, &quot;627&quot;, &quot;64&quot;, &quot;51&quot;, &quot;7&quot;, &quot;7&quot;, &quot;56&quot;, &quot;34&quot;, …
## $ ci_hi   &lt;chr&gt; &quot;1950&quot;, &quot;88&quot;, &quot;327&quot;, &quot;2020&quot;, &quot;80&quot;, &quot;65&quot;, &quot;9&quot;, &quot;10&quot;, &quot;74&quot;, &quot;61…</code></pre>
</div>
<div id="sep" class="section level4">
<h4><span class="header-section-number">4.8.3.2</span> Set delimiters with <code>sep</code></h4>
<p>Now do the same with <code>infmort</code>. It’s already in long format, so you don’t need to use <code>gather</code>, but the third column has a ridiculously long name, so we can just refer to it by its column number (3).</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="tidyr.html#cb214-1"></a>infmort_split &lt;-<span class="st"> </span>infmort <span class="op">%&gt;%</span></span>
<span id="cb214-2"><a href="tidyr.html#cb214-2"></a><span class="st">  </span><span class="kw">separate</span>(<span class="dv">3</span>, <span class="kw">c</span>(<span class="st">&quot;rate&quot;</span>, <span class="st">&quot;ci_low&quot;</span>, <span class="st">&quot;ci_hi&quot;</span>), <span class="dt">extra =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb214-3"><a href="tidyr.html#cb214-3"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 5,044
## Columns: 5
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;…
## $ Year    &lt;dbl&gt; 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2…
## $ rate    &lt;chr&gt; &quot;66&quot;, &quot;68&quot;, &quot;69&quot;, &quot;71&quot;, &quot;73&quot;, &quot;75&quot;, &quot;76&quot;, &quot;78&quot;, &quot;80&quot;, &quot;82&quot;, &quot;…
## $ ci_low  &lt;chr&gt; &quot;3&quot;, &quot;1&quot;, &quot;9&quot;, &quot;7&quot;, &quot;4&quot;, &quot;1&quot;, &quot;8&quot;, &quot;6&quot;, &quot;4&quot;, &quot;3&quot;, &quot;4&quot;, &quot;7&quot;, &quot;…
## $ ci_hi   &lt;chr&gt; &quot;52&quot;, &quot;55&quot;, &quot;58&quot;, &quot;61&quot;, &quot;64&quot;, &quot;66&quot;, &quot;69&quot;, &quot;71&quot;, &quot;73&quot;, &quot;75&quot;, &quot;…</code></pre>
<p><strong>Wait, that didn’t work at all!</strong> It split the column on spaces, brackets, <em>and</em> full stops. We just want to split on the spaces, brackets and dashes. So we need to manually set <code>sep</code> to what the delimiters are. Also, once there are more than a few arguments specified for a function, it’s easier to read them if you put one argument on each line.</p>
{#regex}
<div class="warning">
<p>
You can use <a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/regex.html">regular expressions</a> to separate complex columns. Here, we want to separate on dashes and brackets. You can separate on a list of delimiters by putting them in parentheses, separated by “|”. It’s a little more complicated because brackets have a special meaning in regex, so you need to “escape” the left one with two backslashes “\”.
</p>
</div>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="tidyr.html#cb216-1"></a>infmort_split &lt;-<span class="st"> </span>infmort <span class="op">%&gt;%</span></span>
<span id="cb216-2"><a href="tidyr.html#cb216-2"></a><span class="st">  </span><span class="kw">separate</span>(</span>
<span id="cb216-3"><a href="tidyr.html#cb216-3"></a>    <span class="dt">col =</span> <span class="dv">3</span>, </span>
<span id="cb216-4"><a href="tidyr.html#cb216-4"></a>    <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;rate&quot;</span>, <span class="st">&quot;ci_low&quot;</span>, <span class="st">&quot;ci_hi&quot;</span>), </span>
<span id="cb216-5"><a href="tidyr.html#cb216-5"></a>    <span class="dt">extra =</span> <span class="st">&quot;drop&quot;</span>, </span>
<span id="cb216-6"><a href="tidyr.html#cb216-6"></a>    <span class="dt">sep =</span> <span class="st">&quot;(</span><span class="ch">\\</span><span class="st">[|-|])&quot;</span></span>
<span id="cb216-7"><a href="tidyr.html#cb216-7"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb216-8"><a href="tidyr.html#cb216-8"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 5,044
## Columns: 5
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;…
## $ Year    &lt;dbl&gt; 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2…
## $ rate    &lt;chr&gt; &quot;66.3 &quot;, &quot;68.1 &quot;, &quot;69.9 &quot;, &quot;71.7 &quot;, &quot;73.4 &quot;, &quot;75.1 &quot;, &quot;76.8 &quot;…
## $ ci_low  &lt;chr&gt; &quot;52.7&quot;, &quot;55.7&quot;, &quot;58.7&quot;, &quot;61.6&quot;, &quot;64.4&quot;, &quot;66.9&quot;, &quot;69.0&quot;, &quot;71.2…
## $ ci_hi   &lt;chr&gt; &quot;83.9&quot;, &quot;83.6&quot;, &quot;83.5&quot;, &quot;83.7&quot;, &quot;84.2&quot;, &quot;85.1&quot;, &quot;86.1&quot;, &quot;87.3…</code></pre>
</div>
<div id="convert" class="section level4">
<h4><span class="header-section-number">4.8.3.3</span> Fix data types with <code>convert</code></h4>
<p>That’s better. Notice the <em><chr></em> next to <code>Year</code>, <code>rate</code>, <code>ci_low</code> and <code>ci_hi</code>. That means these columns hold characters (like words), not numbers or integers. This can cause problems when you try to do thigs like average the numbers (you can’t average words), so we can fix it by adding the argument <code>convert</code> and setting it to <code>TRUE</code>.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="tidyr.html#cb218-1"></a>infmort_split &lt;-<span class="st"> </span>infmort <span class="op">%&gt;%</span></span>
<span id="cb218-2"><a href="tidyr.html#cb218-2"></a><span class="st">  </span><span class="kw">separate</span>(<span class="dt">col =</span> <span class="dv">3</span>, </span>
<span id="cb218-3"><a href="tidyr.html#cb218-3"></a>           <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;rate&quot;</span>, <span class="st">&quot;ci_low&quot;</span>, <span class="st">&quot;ci_hi&quot;</span>), </span>
<span id="cb218-4"><a href="tidyr.html#cb218-4"></a>           <span class="dt">extra =</span> <span class="st">&quot;drop&quot;</span>, </span>
<span id="cb218-5"><a href="tidyr.html#cb218-5"></a>           <span class="dt">sep =</span> <span class="st">&quot;(</span><span class="ch">\\</span><span class="st">[|-|])&quot;</span>, </span>
<span id="cb218-6"><a href="tidyr.html#cb218-6"></a>           <span class="dt">convert =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb218-7"><a href="tidyr.html#cb218-7"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 5,044
## Columns: 5
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;…
## $ Year    &lt;dbl&gt; 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2…
## $ rate    &lt;dbl&gt; 66.3, 68.1, 69.9, 71.7, 73.4, 75.1, 76.8, 78.6, 80.4, 82.3, 8…
## $ ci_low  &lt;dbl&gt; 52.7, 55.7, 58.7, 61.6, 64.4, 66.9, 69.0, 71.2, 73.4, 75.5, 7…
## $ ci_hi   &lt;dbl&gt; 83.9, 83.6, 83.5, 83.7, 84.2, 85.1, 86.1, 87.3, 88.9, 90.7, 9…</code></pre>
<p>Do the same for <code>matmort</code>.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="tidyr.html#cb220-1"></a>matmort_split &lt;-<span class="st"> </span>matmort_long <span class="op">%&gt;%</span></span>
<span id="cb220-2"><a href="tidyr.html#cb220-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">stats =</span> <span class="kw">gsub</span>(<span class="st">&quot; &quot;</span>, <span class="st">&quot;&quot;</span>, stats)) <span class="op">%&gt;%</span></span>
<span id="cb220-3"><a href="tidyr.html#cb220-3"></a><span class="st">  </span><span class="kw">separate</span>(<span class="dt">col =</span> stats, </span>
<span id="cb220-4"><a href="tidyr.html#cb220-4"></a>           <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;rate&quot;</span>, <span class="st">&quot;ci_low&quot;</span>, <span class="st">&quot;ci_hi&quot;</span>), </span>
<span id="cb220-5"><a href="tidyr.html#cb220-5"></a>           <span class="dt">extra =</span> <span class="st">&quot;drop&quot;</span>, </span>
<span id="cb220-6"><a href="tidyr.html#cb220-6"></a>           <span class="dt">convert =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb220-7"><a href="tidyr.html#cb220-7"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 543
## Columns: 5
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;Angola&quot;, &quot;Argentina&quot;, &quot;…
## $ Year    &lt;chr&gt; &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990…
## $ rate    &lt;int&gt; 1340, 71, 216, 1160, 72, 58, 8, 8, 64, 46, 26, 569, 58, 33, 9…
## $ ci_low  &lt;int&gt; 878, 58, 141, 627, 64, 51, 7, 7, 56, 34, 20, 446, 47, 28, 7, …
## $ ci_hi   &lt;int&gt; 1950, 88, 327, 2020, 80, 65, 9, 10, 74, 61, 33, 715, 72, 38, …</code></pre>
</div>
</div>
<div id="all-in-one-step" class="section level3">
<h3><span class="header-section-number">4.8.4</span> All in one step</h3>
<p>We can chain all the steps for <code>matmort</code> above together, since we don’t need those intermediate data tables.</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="tidyr.html#cb222-1"></a>matmort2&lt;-<span class="st"> </span>dataskills<span class="op">::</span>matmort <span class="op">%&gt;%</span></span>
<span id="cb222-2"><a href="tidyr.html#cb222-2"></a><span class="st">  </span><span class="kw">gather</span>(<span class="st">&quot;Year&quot;</span>, <span class="st">&quot;stats&quot;</span>, <span class="st">`</span><span class="dt">1990</span><span class="st">`</span><span class="op">:</span><span class="st">`</span><span class="dt">2015</span><span class="st">`</span>) <span class="op">%&gt;%</span></span>
<span id="cb222-3"><a href="tidyr.html#cb222-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">stats =</span> <span class="kw">gsub</span>(<span class="st">&quot; &quot;</span>, <span class="st">&quot;&quot;</span>, stats)) <span class="op">%&gt;%</span></span>
<span id="cb222-4"><a href="tidyr.html#cb222-4"></a><span class="st">  </span><span class="kw">separate</span>(</span>
<span id="cb222-5"><a href="tidyr.html#cb222-5"></a>    <span class="dt">col =</span> stats, </span>
<span id="cb222-6"><a href="tidyr.html#cb222-6"></a>    <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;rate&quot;</span>, <span class="st">&quot;ci_low&quot;</span>, <span class="st">&quot;ci_hi&quot;</span>), </span>
<span id="cb222-7"><a href="tidyr.html#cb222-7"></a>    <span class="dt">extra =</span> <span class="st">&quot;drop&quot;</span>, </span>
<span id="cb222-8"><a href="tidyr.html#cb222-8"></a>    <span class="dt">convert =</span> <span class="ot">TRUE</span></span>
<span id="cb222-9"><a href="tidyr.html#cb222-9"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb222-10"><a href="tidyr.html#cb222-10"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 543
## Columns: 5
## $ Country &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;Angola&quot;, &quot;Argentina&quot;, &quot;…
## $ Year    &lt;chr&gt; &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990&quot;, &quot;1990…
## $ rate    &lt;int&gt; 1340, 71, 216, 1160, 72, 58, 8, 8, 64, 46, 26, 569, 58, 33, 9…
## $ ci_low  &lt;int&gt; 878, 58, 141, 627, 64, 51, 7, 7, 56, 34, 20, 446, 47, 28, 7, …
## $ ci_hi   &lt;int&gt; 1950, 88, 327, 2020, 80, 65, 9, 10, 74, 61, 33, 715, 72, 38, …</code></pre>
</div>
<div id="columns-by-year" class="section level3">
<h3><span class="header-section-number">4.8.5</span> Columns by Year</h3>
<p>Spread out the maternal mortality rate by year.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="tidyr.html#cb224-1"></a>matmort_wide &lt;-<span class="st"> </span>matmort2 <span class="op">%&gt;%</span></span>
<span id="cb224-2"><a href="tidyr.html#cb224-2"></a><span class="st">  </span><span class="kw">spread</span>(<span class="dt">key =</span> Year, <span class="dt">value =</span> rate) <span class="op">%&gt;%</span></span>
<span id="cb224-3"><a href="tidyr.html#cb224-3"></a><span class="st">  </span><span class="kw">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 542 x 6
##    Country     ci_low ci_hi `1990` `2000` `2015`
##    &lt;chr&gt;        &lt;int&gt; &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
##  1 Afghanistan    253   620     NA     NA    396
##  2 Afghanistan    745  1570     NA   1100     NA
##  3 Afghanistan    878  1950   1340     NA     NA
##  4 Albania         16    46     NA     NA     29
##  5 Albania         33    56     NA     43     NA
##  6 Albania         58    88     71     NA     NA
##  7 Algeria         82   244     NA     NA    140
##  8 Algeria        118   241     NA    170     NA
##  9 Algeria        141   327    216     NA     NA
## 10 Angola         221   988     NA     NA    477
## # … with 532 more rows</code></pre>
<div class="warning">
<p>
Nope, that didn’t work at all, but it’s a really common mistake when spreading data. This is because <code>spread</code> matches on all the remaining columns, so Afghanistan with <code>ci_low</code> of 253 is treated as a different observation than Afghanistan with <code>ci_low</code> of 745.
</p>
</div>
<p>This is where <code>pivot_wider()</code> can be very useful. You can set <code>values_from</code> to multiple column names and their names will be added to the <code>names_from</code> values.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="tidyr.html#cb226-1"></a>matmort_wide &lt;-<span class="st"> </span>matmort2 <span class="op">%&gt;%</span></span>
<span id="cb226-2"><a href="tidyr.html#cb226-2"></a><span class="st">  </span><span class="kw">pivot_wider</span>(</span>
<span id="cb226-3"><a href="tidyr.html#cb226-3"></a>    <span class="dt">names_from =</span> Year,</span>
<span id="cb226-4"><a href="tidyr.html#cb226-4"></a>    <span class="dt">values_from =</span> <span class="kw">c</span>(rate, ci_low, ci_hi)</span>
<span id="cb226-5"><a href="tidyr.html#cb226-5"></a>  )</span>
<span id="cb226-6"><a href="tidyr.html#cb226-6"></a>              </span>
<span id="cb226-7"><a href="tidyr.html#cb226-7"></a><span class="kw">glimpse</span>(matmort_wide)</span></code></pre></div>
<pre><code>## Rows: 181
## Columns: 10
## $ Country     &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Albania&quot;, &quot;Algeria&quot;, &quot;Angola&quot;, &quot;Argentina…
## $ rate_1990   &lt;int&gt; 1340, 71, 216, 1160, 72, 58, 8, 8, 64, 46, 26, 569, 58, 3…
## $ rate_2000   &lt;int&gt; 1100, 43, 170, 924, 60, 40, 9, 5, 48, 61, 21, 399, 48, 26…
## $ rate_2015   &lt;int&gt; 396, 29, 140, 477, 52, 25, 6, 4, 25, 80, 15, 176, 27, 4, …
## $ ci_low_1990 &lt;int&gt; 878, 58, 141, 627, 64, 51, 7, 7, 56, 34, 20, 446, 47, 28,…
## $ ci_low_2000 &lt;int&gt; 745, 33, 118, 472, 54, 35, 8, 4, 42, 50, 18, 322, 38, 22,…
## $ ci_low_2015 &lt;int&gt; 253, 16, 82, 221, 44, 21, 5, 3, 17, 53, 12, 125, 19, 3, 5…
## $ ci_hi_1990  &lt;int&gt; 1950, 88, 327, 2020, 80, 65, 9, 10, 74, 61, 33, 715, 72, …
## $ ci_hi_2000  &lt;int&gt; 1570, 56, 241, 1730, 65, 46, 10, 6, 55, 74, 26, 496, 58, …
## $ ci_hi_2015  &lt;int&gt; 620, 46, 244, 988, 63, 31, 7, 5, 35, 124, 19, 280, 37, 6,…</code></pre>
</div>
<div id="experimentum-data" class="section level3">
<h3><span class="header-section-number">4.8.6</span> Experimentum Data</h3>
<p>Students in the Institute of Neuroscience and Psychology at the University of Glasgow can use the online experiment builder platform, <a href="https://debruine.github.io/experimentum/">Experimentum</a>. The platform is also <a href="https://github.com/debruine/experimentum">open source on github</a> for anyone who can install it on a web server. It allows you to group questionnaires and experiments into <strong>projects</strong> with randomisation and counterbalancing. Data for questionnaires and experiments are downloadable in long format, but researchers often need to put them in wide format for analysis.</p>
<p>Look at the help menu for built-in dataset <code>dataskills::experimentum_quests</code> to learn what each column is. Subjects are asked questions about dogs to test the different questionnaire response types.</p>
<ul>
<li>current: Do you own a dog? (yes/no)<br />
</li>
<li>past: Have you ever owned a dog? (yes/no)<br />
</li>
<li>name: What is the best name for a dog? (free short text)<br />
</li>
<li>good: How good are dogs? (1=pretty good:7=very good)<br />
</li>
<li>country: What country do borzois come from?<br />
</li>
<li>good_borzoi: How good are borzois? (0=pretty good:100=very good)<br />
</li>
<li>text: Write some text about dogs. (free long text)<br />
</li>
<li>time: What time is it? (time)</li>
</ul>
<p>To get the dataset into wide format, where each question is in a separate column, use the following code:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="tidyr.html#cb228-1"></a>q &lt;-<span class="st"> </span>dataskills<span class="op">::</span>experimentum_quests <span class="op">%&gt;%</span></span>
<span id="cb228-2"><a href="tidyr.html#cb228-2"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">id_cols =</span> session_id<span class="op">:</span>user_age,</span>
<span id="cb228-3"><a href="tidyr.html#cb228-3"></a>              <span class="dt">names_from =</span> q_name,</span>
<span id="cb228-4"><a href="tidyr.html#cb228-4"></a>              <span class="dt">values_from =</span> dv) <span class="op">%&gt;%</span></span>
<span id="cb228-5"><a href="tidyr.html#cb228-5"></a><span class="st">  </span><span class="kw">type.convert</span>(<span class="dt">as.is =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb228-6"><a href="tidyr.html#cb228-6"></a><span class="st">  </span><span class="kw">print</span>()</span></code></pre></div>
<pre><code>## # A tibble: 24 x 15
##    session_id project_id quest_id user_id user_sex user_status user_age current
##         &lt;int&gt;      &lt;int&gt;    &lt;int&gt;   &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;   &lt;int&gt;
##  1      34034          1        1   31105 female   guest           28.2       1
##  2      34104          1        1   31164 male     registered      19.4       1
##  3      34326          1        1   31392 female   guest           17         0
##  4      34343          1        1   31397 male     guest           22         1
##  5      34765          1        1   31770 female   guest           44         1
##  6      34796          1        1   31796 female   guest           35.9       0
##  7      34806          1        1   31798 female   guest           35         0
##  8      34822          1        1   31802 female   guest           58         1
##  9      34864          1        1   31820 male     guest           20         0
## 10      35014          1        1   31921 female   student         39.2       1
## # … with 14 more rows, and 7 more variables: past &lt;int&gt;, name &lt;chr&gt;,
## #   good &lt;int&gt;, country &lt;chr&gt;, text &lt;chr&gt;, good_borzoi &lt;int&gt;, time &lt;chr&gt;</code></pre>
<div class="info">
<p>
The responses in the <code>dv</code> column have multiple types (e.g., <code>r glossary(“integer”)</code>, <code>r glossary(“double”)</code>, and <code>r glossary(“character”)</code>), but they are all represented as character strings when they’re in the same column. After you spread the data to wide format, each column should be given the ocrrect data type. The function <code>type.convert()</code> makes a best guess at what type each new column should be and converts it. The argument <code>as.is = TRUE</code> converts columns where none of the numbers have decimal places to integers.
</p>
</div>
</div>
</div>
<div id="glossary4" class="section level2">
<h2><span class="header-section-number">4.9</span> Glossary</h2>
<table>
<colgroup>
<col width="60%" />
<col width="39%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="left">definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><a class='glossary' target='_blank' href='https://psyteachr.github.io/glossary/l#long'>long</a></td>
<td align="left">Data where each observation is on a separate row</td>
</tr>
<tr class="even">
<td align="left"><a class='glossary' target='_blank' href='https://psyteachr.github.io/glossary/o#observation'>observation</a></td>
<td align="left">All of the data about a single trial or question.</td>
</tr>
<tr class="odd">
<td align="left"><a class='glossary' target='_blank' href='https://psyteachr.github.io/glossary/v#value'>value</a></td>
<td align="left">A single number or piece of data.</td>
</tr>
<tr class="even">
<td align="left"><a class='glossary' target='_blank' href='https://psyteachr.github.io/glossary/v#variable'>variable</a></td>
<td align="left">A word that identifies and stores the value of some data for later use.</td>
</tr>
<tr class="odd">
<td align="left"><a class='glossary' target='_blank' href='https://psyteachr.github.io/glossary/w#wide'>wide</a></td>
<td align="left">Data where all of the observations about one subject are in the same row</td>
</tr>
</tbody>
</table>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">4.10</span> Exercises</h2>
<p>Download the <a href="exercises/04_tidyr_exercise.Rmd">exercises</a>. See the <a href="exercises/04_tidyr_answers.Rmd">answers</a> only after you’ve attempted all the questions.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="tidyr.html#cb230-1"></a><span class="co"># run this to access the exercise</span></span>
<span id="cb230-2"><a href="tidyr.html#cb230-2"></a>dataskills<span class="op">::</span><span class="kw">exercise</span>(<span class="dv">4</span>)</span>
<span id="cb230-3"><a href="tidyr.html#cb230-3"></a></span>
<span id="cb230-4"><a href="tidyr.html#cb230-4"></a><span class="co"># run this to access the answers</span></span>
<span id="cb230-5"><a href="tidyr.html#cb230-5"></a>dataskills<span class="op">::</span><span class="kw">exercise</span>(<span class="dv">4</span>, <span class="dt">answers =</span> <span class="ot">TRUE</span>)</span></code></pre></div>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol){
    var tol = JSON.parse(this.dataset.tol);  
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("correct");
    } else {
      cl.remove("correct");
    }  
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("correct");
    }  
  }
  
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="ggplot.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="dplyr.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
