---
title: "Data Visualisation"
author: "Me"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
library(tidyverse) # loads packages for data manipulation (dplyr/tidyr) and visualisation (ggplot2)
```

## Resources

* [Data Visualisation](https://psyteachr.github.io/msc-data-skills/ggplot.html) in Data Skills for Reproducible Science
* [Data Visualisation Cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)
* [Stub script for this lesson](https://psyteachr.github.io/msc-data-skills/stubs/3_viz.Rmd)


The code below creates a few data files for our examples.

```{r}
pets <- tibble(
  pet = sample(
    c("dog", "cat", "ferret", "bird", "fish"), 
    100, 
    TRUE, 
    c(0.45, 0.40, 0.05, 0.05, 0.05)
  )
)

pet_happy <- tibble(
  pet = rep(c("dog", "cat"), each = 500),
  happiness = c(rnorm(500, 55, 10), rnorm(500, 45, 10)),
  age = rpois(1000, 3) + 20
)

x_vs_y <- tibble(
  x = rnorm(100),
  y = x + rnorm(100, 0, 0.5)
)

overlap <- tibble(
  x = rbinom(1000, 10, 0.5),
  y = x + rbinom(1000, 20, 0.5)
)

overplot <- tibble(
  x = rnorm(10000),
  y = x + rnorm(10000, 0, 0.5)
)
```


## geom_bar()

```{r}

```

## geom_histogram()

```{r}

```

## geom_density()

```{r}

```

## geom_freqpoly()

```{r}

```



## geom_violin()

```{r}

```

## geom_boxplot()

```{r}

```

## geom_col()

```{r}

```

## geom_point()

```{r}

```

## geom_smooth()

```{r}

```

