<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 2 Introduction 2 | Data Skills</title>
  <meta name="description" content="This course provides an overview of skills needed for reproducible research and open science using the statistical programming language R. Students will learn about data visualisation, data tidying and wrangling, archiving, iteration and functions, probability and data simulations, general linear models, and reproducible workflows. Learning is reinforced through weekly assignments that involve working with different types of data.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 2 Introduction 2 | Data Skills" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This course provides an overview of skills needed for reproducible research and open science using the statistical programming language R. Students will learn about data visualisation, data tidying and wrangling, archiving, iteration and functions, probability and data simulations, general linear models, and reproducible workflows. Learning is reinforced through weekly assignments that involve working with different types of data." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Introduction 2 | Data Skills" />
  
  <meta name="twitter:description" content="This course provides an overview of skills needed for reproducible research and open science using the statistical programming language R. Students will learn about data visualisation, data tidying and wrangling, archiving, iteration and functions, probability and data simulations, general linear models, and reproducible workflows. Learning is reinforced through weekly assignments that involve working with different types of data." />
  

<meta name="author" content="Dale J Barr &amp; Lisa M. DeBruine">


<meta name="date" content="2019-01-26">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="intro.html">
<link rel="next" href="ggplot.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.8.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.39.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.39.2/plotly-latest.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Skills</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#course-aims"><i class="fa fa-check"></i><b>0.1</b> Course Aims</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#intended-learning-outcomes"><i class="fa fa-check"></i><b>0.2</b> Intended Learning Outcomes</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#formative-exercises"><i class="fa fa-check"></i><b>0.3</b> Formative Exercises</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#resources"><i class="fa fa-check"></i><b>0.4</b> Resources</a><ul>
<li class="chapter" data-level="0.4.1" data-path="index.html"><a href="index.html#online-tutorials"><i class="fa fa-check"></i><b>0.4.1</b> Online tutorials</a></li>
<li class="chapter" data-level="0.4.2" data-path="index.html"><a href="index.html#cheat-sheets"><i class="fa fa-check"></i><b>0.4.2</b> Cheat sheets</a></li>
<li class="chapter" data-level="0.4.3" data-path="index.html"><a href="index.html#other"><i class="fa fa-check"></i><b>0.4.3</b> Other</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#resources-1"><i class="fa fa-check"></i><b>1.2</b> Resources</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#what-is-r"><i class="fa fa-check"></i><b>1.3</b> What is R?</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#interacting-with-r"><i class="fa fa-check"></i><b>1.4</b> Interacting with R</a><ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#rconsole"><i class="fa fa-check"></i><b>1.4.1</b> The Base R Console</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#rstudio_ide"><i class="fa fa-check"></i><b>1.4.2</b> The RStudio Integrated Development Environment (IDE)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#developing-reproducible-scripts"><i class="fa fa-check"></i><b>1.5</b> Developing reproducible scripts</a><ul>
<li class="chapter" data-level="1.5.1" data-path="intro.html"><a href="intro.html#configure-rstudio-for-maximum-reproducibility"><i class="fa fa-check"></i><b>1.5.1</b> Configure RStudio for Maximum Reproducibility</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro.html"><a href="intro.html#rmarkdown"><i class="fa fa-check"></i><b>1.5.2</b> Reproducible reports with RStudio and RMarkdown</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#typing-in-commands"><i class="fa fa-check"></i><b>1.6</b> Typing in commands</a><ul>
<li class="chapter" data-level="1.6.1" data-path="intro.html"><a href="intro.html#rcalc"><i class="fa fa-check"></i><b>1.6.1</b> Warming up: Use R as a calculator</a></li>
<li class="chapter" data-level="1.6.2" data-path="intro.html"><a href="intro.html#vars"><i class="fa fa-check"></i><b>1.6.2</b> Storing results in a variable</a></li>
<li class="chapter" data-level="1.6.3" data-path="intro.html"><a href="intro.html#whitespace"><i class="fa fa-check"></i><b>1.6.3</b> Whitespace</a></li>
<li class="chapter" data-level="1.6.4" data-path="intro.html"><a href="intro.html#the-workspace"><i class="fa fa-check"></i><b>1.6.4</b> The workspace</a></li>
<li class="chapter" data-level="1.6.5" data-path="intro.html"><a href="intro.html#vectors"><i class="fa fa-check"></i><b>1.6.5</b> Vectors</a></li>
<li class="chapter" data-level="1.6.6" data-path="intro.html"><a href="intro.html#function_syx"><i class="fa fa-check"></i><b>1.6.6</b> Function syntax</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#data_types"><i class="fa fa-check"></i><b>1.7</b> Some basic data types</a></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#add-on-packages"><i class="fa fa-check"></i><b>1.8</b> Add-on packages</a></li>
<li class="chapter" data-level="1.9" data-path="intro.html"><a href="intro.html#getting-help"><i class="fa fa-check"></i><b>1.9</b> Getting help</a></li>
<li class="chapter" data-level="1.10" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>1.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro2.html"><a href="intro2.html"><i class="fa fa-check"></i><b>2</b> Introduction 2</a><ul>
<li class="chapter" data-level="2.1" data-path="intro2.html"><a href="intro2.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="intro2.html"><a href="intro2.html#resources-2"><i class="fa fa-check"></i><b>2.2</b> Resources</a></li>
<li class="chapter" data-level="2.3" data-path="intro2.html"><a href="intro2.html#project_org"><i class="fa fa-check"></i><b>2.3</b> Organizing a project</a><ul>
<li class="chapter" data-level="2.3.1" data-path="intro2.html"><a href="intro2.html#working-directory"><i class="fa fa-check"></i><b>2.3.1</b> Working Directory</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="intro2.html"><a href="intro2.html#script_struct"><i class="fa fa-check"></i><b>2.4</b> Structuring your script</a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#data_types"><i class="fa fa-check"></i><b>2.5</b> Basic data types</a></li>
<li class="chapter" data-level="2.6" data-path="intro2.html"><a href="intro2.html#containers"><i class="fa fa-check"></i><b>2.6</b> Basic container types</a><ul>
<li class="chapter" data-level="2.6.1" data-path="intro.html"><a href="intro.html#vectors"><i class="fa fa-check"></i><b>2.6.1</b> Vectors</a></li>
<li class="chapter" data-level="2.6.2" data-path="intro2.html"><a href="intro2.html#ex_vector"><i class="fa fa-check"></i><b>2.6.2</b> Exercises</a></li>
<li class="chapter" data-level="2.6.3" data-path="intro2.html"><a href="intro2.html#lists"><i class="fa fa-check"></i><b>2.6.3</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="intro2.html"><a href="intro2.html#tables"><i class="fa fa-check"></i><b>2.7</b> Tabular data</a><ul>
<li class="chapter" data-level="2.7.1" data-path="intro2.html"><a href="intro2.html#viewing-your-tibble"><i class="fa fa-check"></i><b>2.7.1</b> Viewing your tibble</a></li>
<li class="chapter" data-level="2.7.2" data-path="intro2.html"><a href="intro2.html#accessing-rows-and-columns"><i class="fa fa-check"></i><b>2.7.2</b> Accessing rows and columns</a></li>
<li class="chapter" data-level="2.7.3" data-path="intro2.html"><a href="intro2.html#ex_tibble"><i class="fa fa-check"></i><b>2.7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="intro2.html"><a href="intro2.html#import_data"><i class="fa fa-check"></i><b>2.8</b> Importing data</a><ul>
<li class="chapter" data-level="2.8.1" data-path="intro2.html"><a href="intro2.html#writing-data"><i class="fa fa-check"></i><b>2.8.1</b> Writing Data</a></li>
<li class="chapter" data-level="2.8.2" data-path="intro2.html"><a href="intro2.html#ex_import"><i class="fa fa-check"></i><b>2.8.2</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="intro2.html"><a href="intro2.html#pipes"><i class="fa fa-check"></i><b>2.9</b> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>3</b> Data Visualisation</a><ul>
<li class="chapter" data-level="3.1" data-path="ggplot.html"><a href="ggplot.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="3.1.1" data-path="ggplot.html"><a href="ggplot.html#basic"><i class="fa fa-check"></i><b>3.1.1</b> Basic</a></li>
<li class="chapter" data-level="3.1.2" data-path="ggplot.html"><a href="ggplot.html#intermediate"><i class="fa fa-check"></i><b>3.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="3.1.3" data-path="ggplot.html"><a href="ggplot.html#advanced"><i class="fa fa-check"></i><b>3.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="ggplot.html"><a href="ggplot.html#resources-3"><i class="fa fa-check"></i><b>3.2</b> Resources</a></li>
<li class="chapter" data-level="3.3" data-path="ggplot.html"><a href="ggplot.html#setup"><i class="fa fa-check"></i><b>3.3</b> Setup</a></li>
<li class="chapter" data-level="3.4" data-path="ggplot.html"><a href="ggplot.html#vartypes"><i class="fa fa-check"></i><b>3.4</b> Common Variable Combinations</a></li>
<li class="chapter" data-level="3.5" data-path="ggplot.html"><a href="ggplot.html#data"><i class="fa fa-check"></i><b>3.5</b> Data</a></li>
<li class="chapter" data-level="3.6" data-path="ggplot.html"><a href="ggplot.html#basic-plots"><i class="fa fa-check"></i><b>3.6</b> Basic Plots</a><ul>
<li class="chapter" data-level="3.6.1" data-path="ggplot.html"><a href="ggplot.html#geom_bar"><i class="fa fa-check"></i><b>3.6.1</b> Bar plot</a></li>
<li class="chapter" data-level="3.6.2" data-path="ggplot.html"><a href="ggplot.html#density-plot"><i class="fa fa-check"></i><b>3.6.2</b> Density plot</a></li>
<li class="chapter" data-level="3.6.3" data-path="ggplot.html"><a href="ggplot.html#geom_freqpoly"><i class="fa fa-check"></i><b>3.6.3</b> Frequency Polygons</a></li>
<li class="chapter" data-level="3.6.4" data-path="ggplot.html"><a href="ggplot.html#geom_histogram"><i class="fa fa-check"></i><b>3.6.4</b> Histogram</a></li>
<li class="chapter" data-level="3.6.5" data-path="ggplot.html"><a href="ggplot.html#geom_col"><i class="fa fa-check"></i><b>3.6.5</b> Column plot</a></li>
<li class="chapter" data-level="3.6.6" data-path="ggplot.html"><a href="ggplot.html#geom_boxplot"><i class="fa fa-check"></i><b>3.6.6</b> Boxplot</a></li>
<li class="chapter" data-level="3.6.7" data-path="ggplot.html"><a href="ggplot.html#geom_violin"><i class="fa fa-check"></i><b>3.6.7</b> Violin plot</a></li>
<li class="chapter" data-level="3.6.8" data-path="ggplot.html"><a href="ggplot.html#geom_point"><i class="fa fa-check"></i><b>3.6.8</b> Scatter plot</a></li>
<li class="chapter" data-level="3.6.9" data-path="ggplot.html"><a href="ggplot.html#geom_smooth"><i class="fa fa-check"></i><b>3.6.9</b> Line graph</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="ggplot.html"><a href="ggplot.html#save-as-file"><i class="fa fa-check"></i><b>3.7</b> Save as File</a></li>
<li class="chapter" data-level="3.8" data-path="ggplot.html"><a href="ggplot.html#combination-plots"><i class="fa fa-check"></i><b>3.8</b> Combination Plots</a><ul>
<li class="chapter" data-level="3.8.1" data-path="ggplot.html"><a href="ggplot.html#violinbox-plot"><i class="fa fa-check"></i><b>3.8.1</b> Violinbox plot</a></li>
<li class="chapter" data-level="3.8.2" data-path="ggplot.html"><a href="ggplot.html#violin-jitter-plot"><i class="fa fa-check"></i><b>3.8.2</b> Violin-jitter plot</a></li>
<li class="chapter" data-level="3.8.3" data-path="ggplot.html"><a href="ggplot.html#scatter-line-graph"><i class="fa fa-check"></i><b>3.8.3</b> Scatter-line graph</a></li>
<li class="chapter" data-level="3.8.4" data-path="ggplot.html"><a href="ggplot.html#cowplot"><i class="fa fa-check"></i><b>3.8.4</b> Grid of plots</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="ggplot.html"><a href="ggplot.html#overlap"><i class="fa fa-check"></i><b>3.9</b> Overlapping Data</a><ul>
<li class="chapter" data-level="3.9.1" data-path="ggplot.html"><a href="ggplot.html#discrete-data"><i class="fa fa-check"></i><b>3.9.1</b> Discrete Data</a></li>
<li class="chapter" data-level="3.9.2" data-path="ggplot.html"><a href="ggplot.html#viridis"><i class="fa fa-check"></i><b>3.9.2</b> Colours</a></li>
<li class="chapter" data-level="3.9.3" data-path="ggplot.html"><a href="ggplot.html#continuous-data"><i class="fa fa-check"></i><b>3.9.3</b> Continuous Data</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="ggplot.html"><a href="ggplot.html#geom_tile"><i class="fa fa-check"></i><b>3.10</b> Heat map</a></li>
<li class="chapter" data-level="3.11" data-path="ggplot.html"><a href="ggplot.html#plotly"><i class="fa fa-check"></i><b>3.11</b> Interactive Plots</a></li>
<li class="chapter" data-level="3.12" data-path="ggplot.html"><a href="ggplot.html#exercises-1"><i class="fa fa-check"></i><b>3.12</b> Exercises</a><ul>
<li class="chapter" data-level="3.12.1" data-path="ggplot.html"><a href="ggplot.html#common-plots"><i class="fa fa-check"></i><b>3.12.1</b> Common Plots</a></li>
<li class="chapter" data-level="3.12.2" data-path="ggplot.html"><a href="ggplot.html#two-continuous-variables"><i class="fa fa-check"></i><b>3.12.2</b> Two continuous variables</a></li>
<li class="chapter" data-level="3.12.3" data-path="ggplot.html"><a href="ggplot.html#many-correlated-variables"><i class="fa fa-check"></i><b>3.12.3</b> Many correlated variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tidyr.html"><a href="tidyr.html"><i class="fa fa-check"></i><b>4</b> Tidy Data</a><ul>
<li class="chapter" data-level="4.1" data-path="tidyr.html"><a href="tidyr.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="4.1.1" data-path="tidyr.html"><a href="tidyr.html#basic-1"><i class="fa fa-check"></i><b>4.1.1</b> Basic</a></li>
<li class="chapter" data-level="4.1.2" data-path="tidyr.html"><a href="tidyr.html#intermediate-1"><i class="fa fa-check"></i><b>4.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="4.1.3" data-path="tidyr.html"><a href="tidyr.html#advanced-1"><i class="fa fa-check"></i><b>4.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="tidyr.html"><a href="tidyr.html#resources-4"><i class="fa fa-check"></i><b>4.2</b> Resources</a></li>
<li class="chapter" data-level="4.3" data-path="tidyr.html"><a href="tidyr.html#setup-1"><i class="fa fa-check"></i><b>4.3</b> Setup</a></li>
<li class="chapter" data-level="4.4" data-path="tidyr.html"><a href="tidyr.html#load-data"><i class="fa fa-check"></i><b>4.4</b> Load Data</a></li>
<li class="chapter" data-level="4.5" data-path="intro2.html"><a href="intro2.html#pipes"><i class="fa fa-check"></i><b>4.5</b> Pipes</a></li>
<li class="chapter" data-level="4.6" data-path="tidyr.html"><a href="tidyr.html#gather"><i class="fa fa-check"></i><b>4.6</b> gather()</a></li>
<li class="chapter" data-level="4.7" data-path="tidyr.html"><a href="tidyr.html#separate"><i class="fa fa-check"></i><b>4.7</b> separate()</a><ul>
<li class="chapter" data-level="4.7.1" data-path="tidyr.html"><a href="tidyr.html#extra"><i class="fa fa-check"></i><b>4.7.1</b> Handle spare columns with <code>extra</code></a></li>
<li class="chapter" data-level="4.7.2" data-path="tidyr.html"><a href="tidyr.html#sep"><i class="fa fa-check"></i><b>4.7.2</b> Set delimiters with <code>sep</code></a></li>
<li class="chapter" data-level="4.7.3" data-path="tidyr.html"><a href="tidyr.html#convert"><i class="fa fa-check"></i><b>4.7.3</b> Fix data types with <code>convert</code></a></li>
<li class="chapter" data-level="4.7.4" data-path="tidyr.html"><a href="tidyr.html#all-in-one-step"><i class="fa fa-check"></i><b>4.7.4</b> All in one step</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="tidyr.html"><a href="tidyr.html#spread"><i class="fa fa-check"></i><b>4.8</b> spread()</a></li>
<li class="chapter" data-level="4.9" data-path="tidyr.html"><a href="tidyr.html#unite"><i class="fa fa-check"></i><b>4.9</b> unite()</a><ul>
<li class="chapter" data-level="4.9.1" data-path="tidyr.html"><a href="tidyr.html#control-separation-with-sep"><i class="fa fa-check"></i><b>4.9.1</b> Control separation with <code>sep</code></a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="tidyr.html"><a href="tidyr.html#exercises-2"><i class="fa fa-check"></i><b>4.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dplyr.html"><a href="dplyr.html"><i class="fa fa-check"></i><b>5</b> Data Wrangling</a><ul>
<li class="chapter" data-level="5.1" data-path="dplyr.html"><a href="dplyr.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="5.1.1" data-path="dplyr.html"><a href="dplyr.html#basic-2"><i class="fa fa-check"></i><b>5.1.1</b> Basic</a></li>
<li class="chapter" data-level="5.1.2" data-path="dplyr.html"><a href="dplyr.html#intermediate-2"><i class="fa fa-check"></i><b>5.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="5.1.3" data-path="dplyr.html"><a href="dplyr.html#advanced-2"><i class="fa fa-check"></i><b>5.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="dplyr.html"><a href="dplyr.html#resources-5"><i class="fa fa-check"></i><b>5.2</b> Resources</a></li>
<li class="chapter" data-level="5.3" data-path="dplyr.html"><a href="dplyr.html#setup-2"><i class="fa fa-check"></i><b>5.3</b> Setup</a></li>
<li class="chapter" data-level="5.4" data-path="dplyr.html"><a href="dplyr.html#the-disgust-dataset"><i class="fa fa-check"></i><b>5.4</b> The <code>disgust</code> dataset</a></li>
<li class="chapter" data-level="5.5" data-path="dplyr.html"><a href="dplyr.html#six-main-dplyr-verbs"><i class="fa fa-check"></i><b>5.5</b> Six main dplyr verbs</a><ul>
<li class="chapter" data-level="5.5.1" data-path="dplyr.html"><a href="dplyr.html#select"><i class="fa fa-check"></i><b>5.5.1</b> select()</a></li>
<li class="chapter" data-level="5.5.2" data-path="dplyr.html"><a href="dplyr.html#filter"><i class="fa fa-check"></i><b>5.5.2</b> filter()</a></li>
<li class="chapter" data-level="5.5.3" data-path="dplyr.html"><a href="dplyr.html#arrange"><i class="fa fa-check"></i><b>5.5.3</b> arrange()</a></li>
<li class="chapter" data-level="5.5.4" data-path="dplyr.html"><a href="dplyr.html#mutate"><i class="fa fa-check"></i><b>5.5.4</b> mutate()</a></li>
<li class="chapter" data-level="5.5.5" data-path="dplyr.html"><a href="dplyr.html#summarise"><i class="fa fa-check"></i><b>5.5.5</b> summarise()</a></li>
<li class="chapter" data-level="5.5.6" data-path="dplyr.html"><a href="dplyr.html#group_by"><i class="fa fa-check"></i><b>5.5.6</b> group_by()</a></li>
<li class="chapter" data-level="5.5.7" data-path="dplyr.html"><a href="dplyr.html#all-together"><i class="fa fa-check"></i><b>5.5.7</b> All Together</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="dplyr.html"><a href="dplyr.html#additional-dplyr-one-table-verbs"><i class="fa fa-check"></i><b>5.6</b> Additional dplyr one-table verbs</a><ul>
<li class="chapter" data-level="5.6.1" data-path="dplyr.html"><a href="dplyr.html#rename"><i class="fa fa-check"></i><b>5.6.1</b> rename()</a></li>
<li class="chapter" data-level="5.6.2" data-path="dplyr.html"><a href="dplyr.html#distinct"><i class="fa fa-check"></i><b>5.6.2</b> distinct()</a></li>
<li class="chapter" data-level="5.6.3" data-path="dplyr.html"><a href="dplyr.html#count"><i class="fa fa-check"></i><b>5.6.3</b> count()</a></li>
<li class="chapter" data-level="5.6.4" data-path="dplyr.html"><a href="dplyr.html#slide"><i class="fa fa-check"></i><b>5.6.4</b> slice()</a></li>
<li class="chapter" data-level="5.6.5" data-path="dplyr.html"><a href="dplyr.html#pull"><i class="fa fa-check"></i><b>5.6.5</b> pull()</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="dplyr.html"><a href="dplyr.html#exercises-3"><i class="fa fa-check"></i><b>5.7</b> Exercises</a><ul>
<li class="chapter" data-level="5.7.1" data-path="dplyr.html"><a href="dplyr.html#easy"><i class="fa fa-check"></i><b>5.7.1</b> Easy</a></li>
<li class="chapter" data-level="5.7.2" data-path="dplyr.html"><a href="dplyr.html#intermediate-3"><i class="fa fa-check"></i><b>5.7.2</b> Intermediate</a></li>
<li class="chapter" data-level="5.7.3" data-path="dplyr.html"><a href="dplyr.html#advanced-3"><i class="fa fa-check"></i><b>5.7.3</b> Advanced</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="joins.html"><a href="joins.html"><i class="fa fa-check"></i><b>6</b> Data Relations</a><ul>
<li class="chapter" data-level="6.1" data-path="joins.html"><a href="joins.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="joins.html"><a href="joins.html#resources-6"><i class="fa fa-check"></i><b>6.2</b> Resources</a></li>
<li class="chapter" data-level="6.3" data-path="joins.html"><a href="joins.html#setup-3"><i class="fa fa-check"></i><b>6.3</b> Setup</a><ul>
<li class="chapter" data-level="6.3.1" data-path="joins.html"><a href="joins.html#data-1"><i class="fa fa-check"></i><b>6.3.1</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="joins.html"><a href="joins.html#mutating-joins"><i class="fa fa-check"></i><b>6.4</b> Mutating Joins</a><ul>
<li class="chapter" data-level="6.4.1" data-path="joins.html"><a href="joins.html#left_join"><i class="fa fa-check"></i><b>6.4.1</b> left_join()</a></li>
<li class="chapter" data-level="6.4.2" data-path="joins.html"><a href="joins.html#right_join"><i class="fa fa-check"></i><b>6.4.2</b> right_join()</a></li>
<li class="chapter" data-level="6.4.3" data-path="joins.html"><a href="joins.html#inner_join"><i class="fa fa-check"></i><b>6.4.3</b> inner_join()</a></li>
<li class="chapter" data-level="6.4.4" data-path="joins.html"><a href="joins.html#full_join"><i class="fa fa-check"></i><b>6.4.4</b> full_join()</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="joins.html"><a href="joins.html#filtering-joins"><i class="fa fa-check"></i><b>6.5</b> Filtering Joins</a><ul>
<li class="chapter" data-level="6.5.1" data-path="joins.html"><a href="joins.html#semi_join"><i class="fa fa-check"></i><b>6.5.1</b> semi_join()</a></li>
<li class="chapter" data-level="6.5.2" data-path="joins.html"><a href="joins.html#anti_join"><i class="fa fa-check"></i><b>6.5.2</b> anti_join()</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="joins.html"><a href="joins.html#binding-joins"><i class="fa fa-check"></i><b>6.6</b> Binding Joins</a><ul>
<li class="chapter" data-level="6.6.1" data-path="joins.html"><a href="joins.html#bind_rows"><i class="fa fa-check"></i><b>6.6.1</b> bind_rows()</a></li>
<li class="chapter" data-level="6.6.2" data-path="joins.html"><a href="joins.html#bind_cols"><i class="fa fa-check"></i><b>6.6.2</b> bind_cols()</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="joins.html"><a href="joins.html#set-operations"><i class="fa fa-check"></i><b>6.7</b> Set Operations</a><ul>
<li class="chapter" data-level="6.7.1" data-path="joins.html"><a href="joins.html#intersect"><i class="fa fa-check"></i><b>6.7.1</b> intersect()</a></li>
<li class="chapter" data-level="6.7.2" data-path="joins.html"><a href="joins.html#union"><i class="fa fa-check"></i><b>6.7.2</b> union()</a></li>
<li class="chapter" data-level="6.7.3" data-path="joins.html"><a href="joins.html#setdiff"><i class="fa fa-check"></i><b>6.7.3</b> setdiff()</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="joins.html"><a href="joins.html#exercises-4"><i class="fa fa-check"></i><b>6.8</b> Exercises</a><ul>
<li class="chapter" data-level="6.8.1" data-path="joins.html"><a href="joins.html#mutating-joins-1"><i class="fa fa-check"></i><b>6.8.1</b> Mutating joins</a></li>
<li class="chapter" data-level="6.8.2" data-path="joins.html"><a href="joins.html#filtering-joins-1"><i class="fa fa-check"></i><b>6.8.2</b> Filtering joins</a></li>
<li class="chapter" data-level="6.8.3" data-path="joins.html"><a href="joins.html#binding-and-sets"><i class="fa fa-check"></i><b>6.8.3</b> Binding and sets</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="func.html"><a href="func.html"><i class="fa fa-check"></i><b>7</b> Iteration &amp; Functions</a><ul>
<li class="chapter" data-level="7.1" data-path="func.html"><a href="func.html#learning-objectives-6"><i class="fa fa-check"></i><b>7.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="7.1.1" data-path="func.html"><a href="func.html#basic-3"><i class="fa fa-check"></i><b>7.1.1</b> Basic</a></li>
<li class="chapter" data-level="7.1.2" data-path="func.html"><a href="func.html#intermediate-4"><i class="fa fa-check"></i><b>7.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="7.1.3" data-path="func.html"><a href="func.html#advanced-4"><i class="fa fa-check"></i><b>7.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="func.html"><a href="func.html#prep"><i class="fa fa-check"></i><b>7.2</b> Prep</a></li>
<li class="chapter" data-level="7.3" data-path="func.html"><a href="func.html#resources-7"><i class="fa fa-check"></i><b>7.3</b> Resources</a></li>
<li class="chapter" data-level="7.4" data-path="func.html"><a href="func.html#formative-exercises-1"><i class="fa fa-check"></i><b>7.4</b> Formative exercises</a></li>
<li class="chapter" data-level="7.5" data-path="func.html"><a href="func.html#class-notes"><i class="fa fa-check"></i><b>7.5</b> Class Notes</a><ul>
<li class="chapter" data-level="7.5.1" data-path="func.html"><a href="func.html#iteration-functions"><i class="fa fa-check"></i><b>7.5.1</b> Iteration functions</a></li>
<li class="chapter" data-level="7.5.2" data-path="func.html"><a href="func.html#custom-functions"><i class="fa fa-check"></i><b>7.5.2</b> Custom functions</a></li>
<li class="chapter" data-level="7.5.3" data-path="func.html"><a href="func.html#iterating-your-own-functions"><i class="fa fa-check"></i><b>7.5.3</b> Iterating your own functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="sim.html"><a href="sim.html"><i class="fa fa-check"></i><b>8</b> Probability &amp; Simulation</a><ul>
<li class="chapter" data-level="8.1" data-path="sim.html"><a href="sim.html#learning-objectives-7"><i class="fa fa-check"></i><b>8.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="8.1.1" data-path="sim.html"><a href="sim.html#basic-4"><i class="fa fa-check"></i><b>8.1.1</b> Basic</a></li>
<li class="chapter" data-level="8.1.2" data-path="sim.html"><a href="sim.html#intermediate-5"><i class="fa fa-check"></i><b>8.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="8.1.3" data-path="sim.html"><a href="sim.html#advanced-5"><i class="fa fa-check"></i><b>8.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="sim.html"><a href="sim.html#prep-1"><i class="fa fa-check"></i><b>8.2</b> Prep</a></li>
<li class="chapter" data-level="8.3" data-path="sim.html"><a href="sim.html#resources-8"><i class="fa fa-check"></i><b>8.3</b> Resources</a></li>
<li class="chapter" data-level="8.4" data-path="sim.html"><a href="sim.html#formative-exercises-2"><i class="fa fa-check"></i><b>8.4</b> Formative exercises</a></li>
<li class="chapter" data-level="8.5" data-path="sim.html"><a href="sim.html#class-notes-1"><i class="fa fa-check"></i><b>8.5</b> Class Notes</a><ul>
<li class="chapter" data-level="8.5.1" data-path="sim.html"><a href="sim.html#uniform-distribution"><i class="fa fa-check"></i><b>8.5.1</b> Uniform Distribution</a></li>
<li class="chapter" data-level="8.5.2" data-path="sim.html"><a href="sim.html#binomial-distribution"><i class="fa fa-check"></i><b>8.5.2</b> Binomial Distribution</a></li>
<li class="chapter" data-level="8.5.3" data-path="sim.html"><a href="sim.html#normal-distribution"><i class="fa fa-check"></i><b>8.5.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="8.5.4" data-path="sim.html"><a href="sim.html#multivariate-normal"><i class="fa fa-check"></i><b>8.5.4</b> Multivariate Normal</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="sim.html"><a href="sim.html#example"><i class="fa fa-check"></i><b>8.6</b> Example</a><ul>
<li class="chapter" data-level="8.6.1" data-path="sim.html"><a href="sim.html#load-wrangle"><i class="fa fa-check"></i><b>8.6.1</b> Load &amp; wrangle</a></li>
<li class="chapter" data-level="8.6.2" data-path="sim.html"><a href="sim.html#plot"><i class="fa fa-check"></i><b>8.6.2</b> Plot</a></li>
<li class="chapter" data-level="8.6.3" data-path="sim.html"><a href="sim.html#get-means-and-sds"><i class="fa fa-check"></i><b>8.6.3</b> Get means and SDs</a></li>
<li class="chapter" data-level="8.6.4" data-path="sim.html"><a href="sim.html#simulate-a-population"><i class="fa fa-check"></i><b>8.6.4</b> Simulate a population</a></li>
<li class="chapter" data-level="8.6.5" data-path="sim.html"><a href="sim.html#analyse-simulated-data"><i class="fa fa-check"></i><b>8.6.5</b> Analyse simulated data</a></li>
<li class="chapter" data-level="8.6.6" data-path="sim.html"><a href="sim.html#replicate-simulation"><i class="fa fa-check"></i><b>8.6.6</b> Replicate simulation</a></li>
<li class="chapter" data-level="8.6.7" data-path="sim.html"><a href="sim.html#one-tailed-prediction"><i class="fa fa-check"></i><b>8.6.7</b> One-tailed prediction</a></li>
<li class="chapter" data-level="8.6.8" data-path="sim.html"><a href="sim.html#range-of-sample-sizes"><i class="fa fa-check"></i><b>8.6.8</b> Range of sample sizes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>9</b> Introduction to GLM</a><ul>
<li class="chapter" data-level="9.1" data-path="glm.html"><a href="glm.html#learning-objectives-8"><i class="fa fa-check"></i><b>9.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="9.1.1" data-path="glm.html"><a href="glm.html#basic-5"><i class="fa fa-check"></i><b>9.1.1</b> Basic</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="glm.html"><a href="glm.html#resources-9"><i class="fa fa-check"></i><b>9.2</b> Resources</a></li>
<li class="chapter" data-level="9.3" data-path="glm.html"><a href="glm.html#class-notes-2"><i class="fa fa-check"></i><b>9.3</b> Class Notes</a></li>
<li class="chapter" data-level="9.4" data-path="glm.html"><a href="glm.html#additional-take-home-formative-exercises"><i class="fa fa-check"></i><b>9.4</b> Additional Take-Home Formative Exercises</a></li>
<li class="chapter" data-level="9.5" data-path="glm.html"><a href="glm.html#in-class-exercises"><i class="fa fa-check"></i><b>9.5</b> In-Class Exercises</a><ul>
<li class="chapter" data-level="9.5.1" data-path="glm.html"><a href="glm.html#relationship-between-t-test-anova-and-linear-regression"><i class="fa fa-check"></i><b>9.5.1</b> Relationship between t-test, ANOVA, and linear regression</a></li>
<li class="chapter" data-level="9.5.2" data-path="glm.html"><a href="glm.html#understanding-decomposition-matrices"><i class="fa fa-check"></i><b>9.5.2</b> Understanding decomposition matrices</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="repro.html"><a href="repro.html"><i class="fa fa-check"></i><b>10</b> Reproducible Workflows</a><ul>
<li class="chapter" data-level="10.1" data-path="repro.html"><a href="repro.html#learning-objectives-9"><i class="fa fa-check"></i><b>10.1</b> Learning Objectives</a><ul>
<li class="chapter" data-level="10.1.1" data-path="repro.html"><a href="repro.html#basic-6"><i class="fa fa-check"></i><b>10.1.1</b> Basic</a></li>
<li class="chapter" data-level="10.1.2" data-path="repro.html"><a href="repro.html#intermediate-6"><i class="fa fa-check"></i><b>10.1.2</b> Intermediate</a></li>
<li class="chapter" data-level="10.1.3" data-path="repro.html"><a href="repro.html#advanced-6"><i class="fa fa-check"></i><b>10.1.3</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="repro.html"><a href="repro.html#prep-2"><i class="fa fa-check"></i><b>10.2</b> Prep</a></li>
<li class="chapter" data-level="10.3" data-path="repro.html"><a href="repro.html#resources-10"><i class="fa fa-check"></i><b>10.3</b> Resources</a></li>
<li class="chapter" data-level="10.4" data-path="repro.html"><a href="repro.html#class-notes-3"><i class="fa fa-check"></i><b>10.4</b> Class Notes</a><ul>
<li class="chapter" data-level="10.4.1" data-path="repro.html"><a href="repro.html#r-markdown"><i class="fa fa-check"></i><b>10.4.1</b> R Markdown</a></li>
<li class="chapter" data-level="10.4.2" data-path="repro.html"><a href="repro.html#knitr-options"><i class="fa fa-check"></i><b>10.4.2</b> knitr options</a></li>
<li class="chapter" data-level="10.4.3" data-path="repro.html"><a href="repro.html#yaml-header"><i class="fa fa-check"></i><b>10.4.3</b> YAML Header</a></li>
<li class="chapter" data-level="10.4.4" data-path="repro.html"><a href="repro.html#toc-and-document-headers"><i class="fa fa-check"></i><b>10.4.4</b> TOC and Document Headers</a></li>
<li class="chapter" data-level="10.4.5" data-path="repro.html"><a href="repro.html#code-chunks"><i class="fa fa-check"></i><b>10.4.5</b> Code Chunks</a></li>
<li class="chapter" data-level="10.4.6" data-path="repro.html"><a href="repro.html#bibliography"><i class="fa fa-check"></i><b>10.4.6</b> Bibliography</a></li>
<li class="chapter" data-level="10.4.7" data-path="repro.html"><a href="repro.html#output-formats"><i class="fa fa-check"></i><b>10.4.7</b> Output Formats</a></li>
<li class="chapter" data-level="10.4.8" data-path="repro.html"><a href="repro.html#computational-reproducibility"><i class="fa fa-check"></i><b>10.4.8</b> Computational Reproducibility</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="repro.html"><a href="repro.html#references"><i class="fa fa-check"></i><b>10.5</b> References</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="installing-r.html"><a href="installing-r.html"><i class="fa fa-check"></i><b>A</b> Installing <code>R</code></a><ul>
<li class="chapter" data-level="A.1" data-path="installing-r.html"><a href="installing-r.html#installing-base-r"><i class="fa fa-check"></i><b>A.1</b> Installing Base R</a></li>
<li class="chapter" data-level="A.2" data-path="installing-r.html"><a href="installing-r.html#installing-rstudio"><i class="fa fa-check"></i><b>A.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="A.3" data-path="installing-r.html"><a href="installing-r.html#additional-tweaks-you-might-want-to-try"><i class="fa fa-check"></i><b>A.3</b> Additional tweaks you might want to try</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="ukbabynames.html"><a href="ukbabynames.html"><i class="fa fa-check"></i><b>B</b> ukbabynames Live Coding</a></li>
<li class="divider"></li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Skills</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro2" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Introduction 2</h1>
<div id="learning-objectives-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Learning Objectives</h2>
<ol style="list-style-type: decimal">
<li><a href="intro2.html#project_org">Organizing a project</a>: directory structure and working directory</li>
<li>Appropriately <a href="intro2.html#script_struct">structure an R script or RMarkdown file</a></li>
<li>Understand the use the <a href="intro.html#data_types">basic data types</a> (integer, double, character, factor)</li>
<li>Understand and use the <a href="intro2.html#containers">basic container types</a> (list, vector)</li>
<li>Create a simple <a href="intro2.html#tables">data table</a></li>
<li><a href="intro2.html#import_data">Import data</a> from a CSV and Excel files</li>
<li>Combining analysis steps using the <code>magrittr</code> <a href="intro2.html#pipes">pipe <code>%&gt;%</code></a></li>
</ol>
</div>
<div id="resources-2" class="section level2">
<h2><span class="header-section-number">2.2</span> Resources</h2>
<ul>
<li><a href="http://r4ds.had.co.nz/data-import.html">Chapter 11: Data Import</a> in <em>R for Data Science</em></li>
<li><a href="https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-import-cheatsheet.pdf">RStudio Data Import Cheatsheet</a></li>
<li><a href="https://www.nrscotland.gov.uk/files//statistics/babies-first-names-full-list/summary-records/babies-names16-all-names-years.csv">Scottish Babynames</a></li>
<li><a href="https://www.youtube.com/watch?v=lAaVPMcMs1w">Developing an analysis in R/RStudio: Scottish babynames (1/2)</a></li>
<li><a href="https://www.youtube.com/watch?v=lzdTHCcClqo">Developing an analysis in R/RStudio: Scottish babynames (2/2)</a></li>
</ul>
</div>
<div id="project_org" class="section level2">
<h2><span class="header-section-number">2.3</span> Organizing a project</h2>
<div id="working-directory" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Working Directory</h3>
<p>Where should I put all my files?</p>
<p>When developing an analysis, you usually want to have all of your scripts and data files in one subtree of your computer's directory structure. Usually there is a single <em>working directory</em> where your data and scripts are stored. For the purpose of this class, to minimize problems, please store your files on your network drive (usually something like the M: drive or U: drive on a Windows machine.)</p>
<p>Your script should only reference files in three locations, using the appropriate format.</p>
<table style="width:96%;">
<colgroup>
<col width="62%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Where</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>on the web</td>
<td>&quot;<a href="https://github.com/gupsych/data_skills/blob/master/02_intro.Rmd" class="uri">https://github.com/gupsych/data_skills/blob/master/02_intro.Rmd</a>&quot;</td>
</tr>
<tr class="even">
<td>in the working directory</td>
<td>&quot;my_file2.csv&quot;</td>
</tr>
<tr class="odd">
<td>in a subdirectory</td>
<td>&quot;subdir/my_file2.csv&quot;</td>
</tr>
</tbody>
</table>
<div class="warning">
<p>
Never set or change your working directory in a script; always store your main script file in the top-level directory and manually set your working directory to that location. This means you'll have to reset the working directory each time you open RStudio, but this is a small price to pay for reproducibility (alternatively, learn about <a href="https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects">R Projects</a>).
</p>
</div>
<p>For instance, if on a Windows machine your data and scripts live in the directory <code>C:\Carla's_files\thesis2\my_thesis\new_analysis</code>, you will set your working directory to <code>new_analysis</code> in one of two ways: (1) by going to the <code>Session</code> pull down menu in RStudio and choosing <code>Set Working Directory</code>, or (2) by typing <code>setwd(&quot;C:\Carla's_files\thesis2\my_thesis\new_analysis&quot;)</code> in the console window. If you 'knit' an RMarkdown file, your working directory is automatically set to the same directory where the Rmd file is located during the knitting process. But if you're planning on running the code chunks individually, you'll need to manually set the directory.</p>
<div class="warning">
<p>
It's tempting to make your life simple by putting the <code>setwd()</code> command in your script. Don't do this! Others will not have the same directory tree as you (and when your laptop dies and you get a new one, neither will you). <em>When manually setting the working directory, always do so by using the <code>Session | Set Working Directory</code> pull-down option or by typing <code>setwd()</code> in the console.</em>
</p>
</div>
<p>If your script needs a file in a subdirectory of <code>new_analysis</code>, say, <code>analysis2/dat.rds</code>, load it in using a relative path:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;analysis2/dat.rds&quot;</span>)  <span class="co"># right way</span></code></pre></div>
<p>Do not load it in using an absolute path:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;C:/Carla&#39;s_files/thesis22/my_thesis/new_analysis/analysis2/dat.rds&quot;</span>)   <span class="co"># wrong</span></code></pre></div>
<div class="info">
<p>
Also note the convention of using forward slashes, unlike the Windows specific convention of using backward slashes. This is to make references to files platform independent.
</p>
</div>
</div>
</div>
<div id="script_struct" class="section level2">
<h2><span class="header-section-number">2.4</span> Structuring your script</h2>
<p>If you structure your R script or RMarkdown file in a predictable way, it will make your life much easier. All scripts should have the following structure:</p>
<ol style="list-style-type: decimal">
<li>Load any add-on packages you will need</li>
<li>Define any custom functions</li>
<li>Import data</li>
<li>Perform the analysis</li>
</ol>
<p>Consider, for instance, the script that we created in the last session:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load the add-on packages</span>
<span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)
<span class="kw">library</span>(<span class="st">&quot;ukbabynames&quot;</span>)

<span class="co"># If we had created any functions (we didn&#39;t) we would put them here. We will</span>
<span class="co"># learn about creating functions later in the course.</span>

<span class="co"># Import the data</span>
nam0 &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;PSYCH5077 Grades-20180921_0719-comma_separated.csv&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="dt">name =</span> <span class="st">`</span><span class="dt">First name</span><span class="st">`</span>) <span class="co"># rename the column</span>

<span class="co"># The rest of the script performs the analysis</span>
nam1 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">name =</span> <span class="kw">c</span>(<span class="st">&quot;Dale&quot;</span>, <span class="st">&quot;Lisa&quot;</span>, <span class="st">&quot;Rebecca&quot;</span>))

nam_uk &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(nam0, nam1) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(ukbabynames, <span class="st">&quot;name&quot;</span>) 

<span class="kw">ggplot</span>(nam_uk, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y=</span> n,
                   <span class="dt">colour =</span> sex)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>name, <span class="dt">scales =</span> <span class="st">&quot;free_y&quot;</span>)</code></pre></div>
<p>Often when you are working on a script, you will realize that you need to load another add-on package. Don't bury the call to <code>library(package_I_need)</code> way down in the script. Put it in the top, so the user has an overview of what packages are needed.</p>
<p>When structuring an RMarkdown file, it is generally a good idea to have a single code chunk for each output that is produced in the report; for instance, the above code could all be in a single chunk since the only output we care about is the graph at the end. It is also a good idea to suppress any warnings or messages in the report so that they don't confuse the reader. You can suppress messages or warnings by using the code chunk options <code>message=FALSE</code> and <code>warning=FALSE</code>.</p>
</div>
<div id="data_types" class="section level2">
<h2><span class="header-section-number">2.5</span> Basic data types</h2>
<p>There are four main basic data types in R (there are more, but these are the critical ones you need to know about).</p>
<table>
<thead>
<tr class="header">
<th>type</th>
<th>examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>character</code></td>
<td>&quot;hello&quot;, &quot;ABCDE1&quot;, &quot;12 45&quot;, &quot;123.45&quot;</td>
</tr>
<tr class="even">
<td><code>integer</code></td>
<td>10L, 50L, 1L, -20L</td>
</tr>
<tr class="odd">
<td><code>double</code> aka <code>numeric</code></td>
<td>10, 3.1415, -99.7, 0.001, -3.5e6</td>
</tr>
<tr class="even">
<td><code>logical</code></td>
<td><code>TRUE</code>, <code>FALSE</code></td>
</tr>
</tbody>
</table>
<p>There is also a specific data type called a <code>factor</code> which will probably give you a headache sooner or later, but we can get by for now without them.</p>
<p>Character strings can include basically anything, including quotes, but if you want a quote to be included you have to 'escape' it using a backslash:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">my_string &lt;-<span class="st"> &quot;The instructor said, </span><span class="ch">\&quot;</span><span class="st">R is cool,</span><span class="ch">\&quot;</span><span class="st"> and the class agreed.&quot;</span>
my_string</code></pre></div>
<pre><code>## [1] &quot;The instructor said, \&quot;R is cool,\&quot; and the class agreed.&quot;</code></pre>
<p>Note that if you just type a plain number such as <code>10</code> it is stored as a double, even if it doesn't have a decimal point. If you want it to be an exact integer, use the <code>L</code> suffix (10L).</p>
<p>If you ever want to know the data type of something, use the class function. There is also the <code>mode</code> function which is specifically for vectors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(<span class="dv">10</span>) <span class="co"># numeric</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(10L) <span class="co"># integer</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(<span class="st">&quot;10&quot;</span>) <span class="co"># string</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(10L <span class="op">==</span><span class="st"> </span>11L) <span class="co"># logical</span></code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mode</span>(<span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] &quot;logical&quot;</code></pre>
</div>
<div id="containers" class="section level2">
<h2><span class="header-section-number">2.6</span> Basic container types</h2>
<div id="vectors" class="section level3">
<h3><span class="header-section-number">2.6.1</span> Vectors</h3>
<p>OK, here's a question. When you type a single number in the console, it spits it back out to you, like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">3L</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Why is there a <code>[1]</code> there? i.e., what does the <code>[1]</code> in the <code>[1] 3</code> refer to?</p>
<p>We'll eventually get to the answer, but let's see if you can discover it yourself through experiment. There is an operator <code>:</code> that, when placed between two integers <code>x</code> and <code>y</code> like so: <code>x:y</code> will yield the sequence of integers from x to y inclusive. Let's make a big long vector of numbers and print it out.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vec &lt;-<span class="st"> </span><span class="dv">200</span><span class="op">:</span><span class="dv">400</span>
vec</code></pre></div>
<pre><code>##   [1] 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
##  [18] 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
##  [35] 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250
##  [52] 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267
##  [69] 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284
##  [86] 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301
## [103] 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318
## [120] 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335
## [137] 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352
## [154] 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369
## [171] 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386
## [188] 387 388 389 390 391 392 393 394 395 396 397 398 399 400</code></pre>
<p>Note the number in square brackets on the left hand side of the output. Note that <code>vec</code> is a vector: an ordered container of 200 elements, in this case, the integers from 200 to 400. The bracked number on the left hand side tells you the numeric index (i.e., element number) corresponding to the first value in that row. So the first value is 200, the 19th value is 218, the 37th value is 236, etc.</p>
<p>Recall from the last class that another way to create a vector is to use the <code>c()</code> operator. (This is the easiest way, but you can also use the <code>vector()</code> function.) If we wanted to pick specific values out of the vector by position, we can make a vector of numbers like so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(1L, 19L, 37L, 55L)</code></pre></div>
<pre><code>## [1]  1 19 37 55</code></pre>
<p>And then pull them out using the <code>[]</code> operator, which is the <em>extraction</em> operator, on the variable <code>vec</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vec[<span class="kw">c</span>(1L, 19L, 37L, 55L)]</code></pre></div>
<pre><code>## [1] 200 218 236 254</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## note also:
index &lt;-<span class="st"> </span><span class="kw">c</span>(1L, 19L, 37L, 55L)
vec[index]</code></pre></div>
<pre><code>## [1] 200 218 236 254</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vec[<span class="kw">c</span>(1L, 1L, 19L, 19L, 19L, 19L)]</code></pre></div>
<pre><code>## [1] 200 200 218 218 218 218</code></pre>
<p>OK let's return to our original question: why did we get <code>[1] 3</code> when we just typed <code>3L</code>? The answer should now be clear: when we entered a single number, R created a vector with a single element.</p>
<p>You can also create 'named' vectors, where each elements has a name. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vec2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dt">first =</span> <span class="fl">77.9</span>, <span class="dt">second =</span> <span class="op">-</span><span class="fl">13.2</span>, <span class="dt">third =</span> <span class="fl">100.1</span>)
vec2</code></pre></div>
<pre><code>##  first second  third 
##   77.9  -13.2  100.1</code></pre>
<p>We can then access elements by name using a character vector within the square brackets. We can put them in any order we want, and we can repeat elements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vec2[<span class="kw">c</span>(<span class="st">&quot;third&quot;</span>, <span class="st">&quot;second&quot;</span>, <span class="st">&quot;second&quot;</span>)]</code></pre></div>
<pre><code>##  third second second 
##  100.1  -13.2  -13.2</code></pre>
<p>We can get the vector of names using the <code>names()</code> function, and we can set or change them using something like <code>names(vec2) &lt;- c(&quot;n1&quot;, &quot;n2&quot;, &quot;n3&quot;)</code>.</p>
<p>Another way to access elements is by using a logical vector within the square brackets. This will pull out the elements of the vector for which the corresponding element of the logical vector is <code>TRUE</code>. The logical vector must have the same length as the original. You can find out how long a vector is using the <code>length()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(vec2)</code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vec2[<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">TRUE</span>)]</code></pre></div>
<pre><code>## first third 
##  77.9 100.1</code></pre>
<p>Here are some useful tricks to save typing when creating vectors. Recall that in the command <code>x:y</code> the <code>:</code> operator would give you the sequence of integers from <code>x:y</code>.</p>
<p>What if you want to repeat a vector many times? You could either type it out (painful) or use the <code>rep()</code> function, which can repeat vectors in different ways.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># ten zeroes</span>
<span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>)</code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># alternating 1 and 3, 7 times</span>
<span class="kw">rep</span>(<span class="kw">c</span>(1L, 3L), <span class="dv">7</span>)</code></pre></div>
<pre><code>##  [1] 1 3 1 3 1 3 1 3 1 3 1 3 1 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>), <span class="dv">2</span>)</code></pre></div>
<pre><code>## [1]  TRUE FALSE  TRUE FALSE</code></pre>
<p>What if you want to create a sequence but with something other than integer steps? You can use the <code>seq()</code> function. You can learn about this in the exercises below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Repeat a vector</span>
<span class="co"># See the ?rep function</span>
<span class="kw">rep</span>(<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>), <span class="dv">3</span>)</code></pre></div>
<pre><code>## [1]  TRUE FALSE  TRUE FALSE  TRUE FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Get every other (odd) element of vec</span>
vec[<span class="kw">rep</span>(<span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">FALSE</span>), <span class="dv">100</span>)]</code></pre></div>
<pre><code>##   [1] 200 202 204 206 208 210 212 214 216 218 220 222 224 226 228 230 232
##  [18] 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264 266
##  [35] 268 270 272 274 276 278 280 282 284 286 288 290 292 294 296 298 300
##  [52] 302 304 306 308 310 312 314 316 318 320 322 324 326 328 330 332 334
##  [69] 336 338 340 342 344 346 348 350 352 354 356 358 360 362 364 366 368
##  [86] 370 372 374 376 378 380 382 384 386 388 390 392 394 396 398 400</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># We can also store the logical vector in a variable and use that</span>
evens &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="ot">FALSE</span>, <span class="ot">TRUE</span>), <span class="dv">100</span>)</code></pre></div>
<div class="warning">
<p>
You can't mix data types in a vector; all elements of the vector must be the same data type. If you mix them, R will coerce them so that they are all the same.
</p>
</div>
</div>
<div id="ex_vector" class="section level3">
<h3><span class="header-section-number">2.6.2</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>The built-in vector <code>letters</code> contains the letters of the English alphabet. Use an indexing vector of integers to extract the letters that spell 'cat'.</p></li>
<li><p>The function <code>colors()</code> returns all of the color names that R is aware of. What is the length of the vector returned by this function? (Use code to find the answer.)</p></li>
<li><p>The function call <code>runif(1000, 0, 1)</code> will draw 1000 numbers from a uniform distribution from 0 to 1, which simulates the p-values that you would get from 1000 experiments where the null hypothesis is true. Store the result of this call in <code>pvals</code>. Create a logical vector called <code>is_sig</code> that is <code>TRUE</code> if the corresponding element of <code>pvals</code> is less than .05, <code>FALSE</code> otherwise (hint: vectorized operations from the last lession), then use this logical vector to pull out those p-values. Finally, calculate the proportion of those p-values that were significant.</p></li>
</ol>
</div>
<div id="lists" class="section level3">
<h3><span class="header-section-number">2.6.3</span> Lists</h3>
<p>Recall that vectors can contain data of only one type. What if you want to store a collection of data of different data types? For that purpose you would use a <code>list</code>. Define a list using the <code>list()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">albums &lt;-<span class="st"> </span>
<span class="st">  </span><span class="kw">list</span>(
    <span class="dt">Michael_Jackson =</span> <span class="kw">c</span>(
      <span class="st">&quot;Off the Wall&quot;</span>,
      <span class="st">&quot;Thriller&quot;</span>,
      <span class="st">&quot;Bad&quot;</span>,
      <span class="st">&quot;Dangerous&quot;</span>
    ),
    <span class="dt">Nirvana =</span> <span class="kw">c</span>(
      <span class="st">&quot;Bleach&quot;</span>,
      <span class="st">&quot;Nevermind&quot;</span>,
      <span class="st">&quot;In Utero&quot;</span>
    )
  )  

<span class="kw">names</span>(albums)
<span class="kw">length</span>(albums)</code></pre></div>
<p>You can refer to elements of a list by</p>
<div class="info">
<p>
Fun fact: tabular data, stored in <code>data.frame</code> or <code>tibble</code> objects, which you will learn about in the next section, are a special type of list. That means you can access the columns of one of these object using <code>tablename$column</code> syntax, which is sometimes useful.
</p>
</div>
</div>
</div>
<div id="tables" class="section level2">
<h2><span class="header-section-number">2.7</span> Tabular data</h2>
<p>Most of what you will be working with in this course is <em>tabular data</em>, data arranged in the form of a table.</p>
<p>Tabular data structures, like lists, allow for a collection of data of different types (characters, integers, logical, etc.) but subject to the constraint that each &quot;column&quot; of the table (element of the list) must have the same number of elements. The base R version of a table is called a <code>data.frame</code> while the 'tidyverse' version is called a <code>tibble</code>. Tibbles are far easier to work with, so we'll be using those. To learn more about differences between these two data structures, see <code>vignette(&quot;tibble&quot;)</code>.</p>
<p>Tabular data becomes especially important for when we talk about <em>tidy data</em> in <a href="04_wrangling.Rmd">lesson 4</a>, which consists of a set of simple principles for structuring data.</p>
<p>If we are creating a tibble from scratch, we can use the <code>tibble()</code> function, and type the data right in. Note that if we want a value to repeat multiple times, we only have to specify a one-element vector; R will expand out the vector to fill out the table. All columns in the tibble must have the same lengths or be of length 1.</p>
<p>If we want to use the <code>tibble()</code> function, we either need to load the tibble package or the tidyverse package (which will itself load tibble in addition to other packages). Let's do the latter.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</code></pre></div>
<p>We can get information about the table dimensions using the functions <code>ncol()</code> (number of columns), <code>nrow()</code> (number of rows), or <code>dim()</code> (a vector with the number of rows and number of columns).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">months &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">ID =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">12</span>,
                 <span class="dt">name =</span> <span class="kw">c</span>(<span class="st">&quot;Jan&quot;</span>, <span class="st">&quot;Feb&quot;</span>, <span class="st">&quot;Mar&quot;</span>, <span class="st">&quot;Apr&quot;</span>,
                          <span class="st">&quot;May&quot;</span>, <span class="st">&quot;Jun&quot;</span>, <span class="st">&quot;Jul&quot;</span>, <span class="st">&quot;Aug&quot;</span>,
                          <span class="st">&quot;Sep&quot;</span>, <span class="st">&quot;Oct&quot;</span>, <span class="st">&quot;Nov&quot;</span>, <span class="st">&quot;Dec&quot;</span>))

<span class="co"># print it</span>
months

<span class="co"># how many rows?</span>
<span class="kw">nrow</span>(months)

<span class="co"># how many columns?</span>
<span class="kw">ncol</span>(months)</code></pre></div>
<div id="viewing-your-tibble" class="section level3">
<h3><span class="header-section-number">2.7.1</span> Viewing your tibble</h3>
<p>Always, always, always, look at your data once you've created the table and load it in. Also look at it after each step that transforms your tibble.</p>
<p>There are three ways to look at your tibble: <code>View()</code> [*NB: capital 'V'], <code>print()</code>, and <code>glimpse()</code>. Note that it is also rare that you want to print your data in a script; that is something you usually are doing for a sanity check, and you should just do it in the console.</p>
<p>The <code>print()</code> method can be run explicitly, but is more commonly called by just typing the variable name on the blank line. Usually we only call <code>print()</code> if we want fine control of how the information is displayed.</p>
<p>Note that the default is not to print the entire table, but just the first 10 rows. Let's look at the <code>starwars</code> table that is built into the tidyverse.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">starwars</code></pre></div>
<pre><code>## # A tibble: 87 x 13
##    name  height  mass hair_color skin_color eye_color birth_year gender
##    &lt;chr&gt;  &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; 
##  1 Luke…    172    77 blond      fair       blue            19   male  
##  2 C-3PO    167    75 &lt;NA&gt;       gold       yellow         112   &lt;NA&gt;  
##  3 R2-D2     96    32 &lt;NA&gt;       white, bl… red             33   &lt;NA&gt;  
##  4 Dart…    202   136 none       white      yellow          41.9 male  
##  5 Leia…    150    49 brown      light      brown           19   female
##  6 Owen…    178   120 brown, gr… light      blue            52   male  
##  7 Beru…    165    75 brown      light      blue            47   female
##  8 R5-D4     97    32 &lt;NA&gt;       white, red red             NA   &lt;NA&gt;  
##  9 Bigg…    183    84 black      light      brown           24   male  
## 10 Obi-…    182    77 auburn, w… fair       blue-gray       57   male  
## # … with 77 more rows, and 5 more variables: homeworld &lt;chr&gt;,
## #   species &lt;chr&gt;, films &lt;list&gt;, vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>You can see that this is a 87 rows by 13 column table, and we can only see the first 10 rows and first 8 columns.</p>
<p>If I want to see all 87 rows for some reason, I would use an explicit call to <code>print()</code>, and set the argument <code>n</code> to the number of rows I want to see. If I want all of them, just use <code>+Inf</code>, the symbol for 'infinite' rows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(starwars, <span class="dt">n =</span> <span class="op">+</span><span class="ot">Inf</span>) <span class="co"># try this in the console</span></code></pre></div>
<p>But we still can't see all the columns. If this is important to us, we can use <code>glimpse()</code>, which gives a sideways version of the tibble.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(starwars)</code></pre></div>
<pre><code>## Observations: 87
## Variables: 13
## $ name       &lt;chr&gt; &quot;Luke Skywalker&quot;, &quot;C-3PO&quot;, &quot;R2-D2&quot;, &quot;Darth Vader&quot;, &quot;L…
## $ height     &lt;int&gt; 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, …
## $ mass       &lt;dbl&gt; 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.…
## $ hair_color &lt;chr&gt; &quot;blond&quot;, NA, NA, &quot;none&quot;, &quot;brown&quot;, &quot;brown, grey&quot;, &quot;bro…
## $ skin_color &lt;chr&gt; &quot;fair&quot;, &quot;gold&quot;, &quot;white, blue&quot;, &quot;white&quot;, &quot;light&quot;, &quot;lig…
## $ eye_color  &lt;chr&gt; &quot;blue&quot;, &quot;yellow&quot;, &quot;red&quot;, &quot;yellow&quot;, &quot;brown&quot;, &quot;blue&quot;, &quot;…
## $ birth_year &lt;dbl&gt; 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, …
## $ gender     &lt;chr&gt; &quot;male&quot;, NA, NA, &quot;male&quot;, &quot;female&quot;, &quot;male&quot;, &quot;female&quot;, N…
## $ homeworld  &lt;chr&gt; &quot;Tatooine&quot;, &quot;Tatooine&quot;, &quot;Naboo&quot;, &quot;Tatooine&quot;, &quot;Alderaa…
## $ species    &lt;chr&gt; &quot;Human&quot;, &quot;Droid&quot;, &quot;Droid&quot;, &quot;Human&quot;, &quot;Human&quot;, &quot;Human&quot;,…
## $ films      &lt;list&gt; [&lt;&quot;Revenge of the Sith&quot;, &quot;Return of the Jedi&quot;, &quot;The …
## $ vehicles   &lt;list&gt; [&lt;&quot;Snowspeeder&quot;, &quot;Imperial Speeder Bike&quot;&gt;, &lt;&gt;, &lt;&gt;, &lt;…
## $ starships  &lt;list&gt; [&lt;&quot;X-wing&quot;, &quot;Imperial shuttle&quot;&gt;, &lt;&gt;, &lt;&gt;, &quot;TIE Advanc…</code></pre>
<p>The other way to look at the table is a more graphical spreadsheet-like version given by <code>View()</code> (capital 'V'). It can be useful in the console, but don't ever put this one in a script because it will create an annoying pop-up window when the user goes to run it.</p>
<p>Note that <code>data.frame</code> objects are printed out in different ways from <code>tibble</code> objects. If you print a <code>data.frame</code> object with thousands or millions of rows, you won't just get a preview... you will spam your console with row upon row of data. If you want to make a data.frame into a tibble so that it prints out nicely, just use the <code>as_tibble()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mtcars <span class="co"># prints out way too many rows; TMI</span>

<span class="kw">as_tibble</span>(mtcars) <span class="co"># much cleaner</span>
mtcars2 &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(mtcars) <span class="co"># store it</span></code></pre></div>
</div>
<div id="accessing-rows-and-columns" class="section level3">
<h3><span class="header-section-number">2.7.2</span> Accessing rows and columns</h3>
<p>There are various base R ways of accessing specific columns or rows from a table that are useful to know about, but you'll be learning easier (and more readable) ways when we get to the lecture on <a href="04_wrangling.Rmd">data wrangling</a>. Examples of these base R accessing functions are provided here for reference.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">months[<span class="dv">1</span>, ] <span class="co"># first row</span>

months[, <span class="dv">2</span>] <span class="co"># second column (position)</span>

months[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, ] <span class="co"># first 3 months</span>

months[, <span class="kw">c</span>(<span class="st">&quot;Month&quot;</span>)] <span class="co"># access column by name</span>

months<span class="op">$</span>month  <span class="co"># by column name</span></code></pre></div>
<p>You'll learn about data frame operations in the <a href="tidyr.html#tidyr">tidyr</a> and <a href="dplyr.html#dplyr">dplyr</a> lessons.</p>
</div>
<div id="ex_tibble" class="section level3">
<h3><span class="header-section-number">2.7.3</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Create a tibble with the name, age, and sex of 3-5 people whose names, ages, and sex you know.</p></li>
<li><p>Convert the built-in base R <code>iris</code> dataset to a tibble, and store it in the variable <code>iris2</code>.</p></li>
<li><p>Create a tibble that has the structure of the table below, using the minimum typing possible. (Hint: <code>rep()</code>). Store it in the variable <code>my_tbl</code>.</p>
<pre><code>## # A tibble: 8 x 4
##      ID A     B     C    
##   &lt;int&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1     1 A1    B1    C1   
## 2     2 A1    B2    C1   
## 3     3 A1    B1    C1   
## 4     4 A1    B2    C1   
## 5     5 A2    B1    C1   
## 6     6 A2    B2    C1   
## 7     7 A2    B1    C1   
## 8     8 A2    B2    C1</code></pre></li>
</ol>
</div>
</div>
<div id="import_data" class="section level2">
<h2><span class="header-section-number">2.8</span> Importing data</h2>
<p>There are many different types of files that you might work with when doing data analysis. These different file types are usually distinguished by the three letter <em>extension</em> following a period at the end of the file name. Here are some examples of different types of files and the functions you would use to read them in or write them out.</p>
<table>
<thead>
<tr class="header">
<th>Extension</th>
<th>File Type</th>
<th>Reading</th>
<th>Writing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.csv</td>
<td>Comma-separated values</td>
<td><code>readr::read_csv()</code></td>
<td><code>readr::write_csv()</code></td>
</tr>
<tr class="even">
<td>.xls, .xlsx</td>
<td>Excel workbook</td>
<td><code>readxl::read_excel()</code></td>
<td>N/A</td>
</tr>
<tr class="odd">
<td>.rds</td>
<td>R binary file</td>
<td><code>readRDS()</code></td>
<td><code>saveRDS()</code></td>
</tr>
<tr class="even">
<td>.RData</td>
<td>R binary file</td>
<td><code>load()</code></td>
<td><code>save()</code></td>
</tr>
</tbody>
</table>
<p>Note: following the conventions introduced above in the section about add-on packages, <code>readr::read_csv()</code> refers to the <code>read_csv()</code> function in the <code>readr</code> package, and <code>readxl::read_excel()</code> refers to the function <code>read_excel()</code> in the package <code>readxl</code>.</p>
<p>Probably the most common file type you will encounter is <code>.csv</code> (comma-separated values). As the name suggests, a CSV file distinguishes which values go with which variable by separating them with commas, and text values are sometimes enclosed in double quotes. The first line of a file usually provides the names of the variables. For example, here are the first few lines of a CSV containing Scottish baby names (see <a href="http://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/vital-events/names/babies-first-names/babies-first-names-summary-records-comma-separated-value-csv-format">the page at National Records Scotland</a>):</p>
<pre><code>yr,sex,FirstForename,number,rank,position
1974,B,David,1794,1,1
1974,B,John,1528,2,2
1974,B,Paul,1260,3,3
1974,B,Mark,1234,4,4
1974,B,James,1202,5,5
1974,B,Andrew,1067,6,6
1974,B,Scott,1060,7,7
1974,B,Steven,1020,8,8
1974,B,Robert,885,9,9
1974,B,Stephen,866,10,10</code></pre>
<p>There are six variables in this dataset, and their names are given in the first line of the file: <code>yr</code>, <code>sex</code>, <code>FirstForename</code>, <code>number</code>, <code>rank</code>, and <code>position</code>. You can see that the values for each of these variables are given in order, separated by commas, on each subsequent line of the file.</p>
<p>When you read in CSV files, it is best practice to use the <code>readr::read_csv()</code> function. The <code>readr</code> package is automatically loaaded as part of the <code>tidyverse</code> package, which we will be using in almost every script. Note that you would normally want to store the result of the <code>read_csv()</code> function to a variable, as so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;my_data_file.csv&quot;</span>)</code></pre></div>
<p>Once loaded, you can view your data using the data viewer. In the upper right hand window of RStudio, under the Environment tab, you will see the object <code>dat</code> listed.</p>
<div class="figure">
<img src="images/01_walkthrough/my_data.png" />

</div>
<p>If you click on the View icon (<img src="images/01_walkthrough/table_icon.png" />), it will bring up a table view of the data you loaded in the top left pane of RStudio.</p>
<div class="figure">
<img src="images/01_walkthrough/View.png" />

</div>
<p>This allows you to check that the data have been loaded in properly. You can close the tab when you’re done looking at it—it won't remove the object.</p>
<div id="writing-data" class="section level3">
<h3><span class="header-section-number">2.8.1</span> Writing Data</h3>
<p>If you have data that you want to save your data to a CSV file, use <code>readr::write_csv()</code>, as follows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write_csv</span>(dat, <span class="st">&quot;my_data_file2.csv&quot;</span>)</code></pre></div>
<p>This will save the data in CSV format to your working directory.</p>
</div>
<div id="ex_import" class="section level3">
<h3><span class="header-section-number">2.8.2</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Download the dataset <a href="data/disgust_scores.csv">disgust_scores.csv</a> and read it into a table.</p></li>
<li><p>Override the default column specifications to skip the <code>id</code> column.</p></li>
<li><p>How many rows and columns are in the dataset from question 3?</p></li>
</ol>
</div>
</div>
<div id="pipes" class="section level2">
<h2><span class="header-section-number">2.9</span> Pipes</h2>
<p>Pipes (<code>%&gt;%</code>) are very useful for stringing together a sequence of commands in R. They might be a bit confusing at first but they are worth learning because they will make your code more readable and efficient. Because pipes are a recent innovation, they are not part of base R. That means you need to load an add-on package to use them. Although the &quot;home&quot; package of the pipe operator is a package called magrittr, more commonly you will gain access to them by loading the tidyverse package (<code>library(&quot;tidyverse&quot;)</code>). If you get either of the following errors in your script:</p>
<p><code>Error: unexpected SPECIAL in &quot;%&gt;%&quot;</code><br />
or<br />
<code>Error: could not find function &quot;%&gt;%&quot;</code></p>
<p>you tried to use <code>%&gt;%</code> before doing <code>library(&quot;tidyverse&quot;)</code>.</p>
<p>It is easiest to understand how to use pipes through an example. Let's say that we want to sample 5 random integers between 1 and 10 (with replacement), figure out which unique numbers were sampled, and then sort them in descending order. We will need to call three functions in a sequence: <code>sample()</code> to generate the integers, <code>unique()</code> to figure out which unique integers were sampled (because the same integer may have been sampled multiple times), and then <code>sort()</code> with <code>decreasing = TRUE</code> to put them in descending order. So we might write code like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">5</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)
y &lt;-<span class="st"> </span><span class="kw">unique</span>(x)
<span class="kw">sort</span>(y, <span class="ot">TRUE</span>) <span class="co"># set second argument to &#39;TRUE&#39; so that sort order is descending</span></code></pre></div>
<pre><code>## [1] 7 5 3 1</code></pre>
<p>While there is nothing wrong with this code, it required us to define variables x and y which we won't ever need again, and which clutter up our environment. To avoid this you could rewrite this code using nested function calls like so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sort</span>(
  <span class="kw">unique</span>(
    <span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">5</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)
    )
  , <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 7 6 5 3 1</code></pre>
<p>(If the above call looks confusing, it should!) The call to <code>sample()</code> is embedded within a call to <code>unique()</code> which in turn is embedded within a call to <code>sort()</code>. The functions are executed from most embedded (the &quot;bottom&quot;) to least embedded (the &quot;top&quot;), starting with the function <code>sample()</code>, whose result is then passed in as the first argument to <code>unique()</code>, whose result in turn is passed in as the first argument to <code>sort()</code>; notice the second argument of sort (<code>TRUE</code>) is all the way at the end of the statement, making it hard to figure out which of the three functions it belongs to. We read from left to right; however, understanding this code requires us to work our way from right to left, and therefore unnatural. Moreover it is simply an ugly line of code.</p>
<p>This is where pipes come in. You can re-write the original code using pipes like so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">5</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">unique</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">sort</span>(<span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 9 7 6 5</code></pre>
<p>R will calculate the result of <code>sample(1:10, 5, replace = TRUE)</code> and then pass this result as the first argument of <code>unique()</code>; then, the result of <code>unique()</code> will in turn be passed along as the first argument of <code>sort()</code> with the second argument set to <code>TRUE</code>. The thing to note here is that for any function call on the right hand side of a pipe, you should omit the first argument and start with the second, because the pipe automatically places the result of the call on the left as the first argument of the next function call.</p>
<div id="ex_pipes" class="section level4">
<h4><span class="header-section-number">2.9.0.1</span> Exercises</h4>
<ol style="list-style-type: decimal">
<li><p>Re-write the following sequence of commands into a single 'pipeline'.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">20</span> <span class="co"># integers from 1:20</span>
y &lt;-<span class="st"> </span><span class="kw">rep</span>(x, <span class="dv">2</span>) <span class="co"># then repeat them twice</span>
z &lt;-<span class="st"> </span><span class="kw">sum</span>(y) <span class="co"># and then take the sum</span></code></pre></div></li>
<li><p>Deconstruct the pipeline below back into separate commands.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">LETTERS[<span class="kw">c</span>(<span class="dv">18</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">12</span>)] <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rev</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">paste</span>(<span class="dt">collapse =</span> <span class="st">&quot;&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;LAGER&quot;</code></pre></li>
</ol>
<p><a href="formative_exercises/02_intro_stub.Rmd">Download the formative exercises.</a></p>

</div>
</div>
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ggplot.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
